/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  APIError,
  CLIAuthorizeResponse,
  CLIRefreshTokenRequest,
  CLITokenRequest,
  CLITokenResponse,
  CreateAPIKeyRequest,
  CreateAPIKeyResponse,
  DataPlaneAppResponse,
} from '../models/index';
import {
    APIErrorFromJSON,
    APIErrorToJSON,
    CLIAuthorizeResponseFromJSON,
    CLIAuthorizeResponseToJSON,
    CLIRefreshTokenRequestFromJSON,
    CLIRefreshTokenRequestToJSON,
    CLITokenRequestFromJSON,
    CLITokenRequestToJSON,
    CLITokenResponseFromJSON,
    CLITokenResponseToJSON,
    CreateAPIKeyRequestFromJSON,
    CreateAPIKeyRequestToJSON,
    CreateAPIKeyResponseFromJSON,
    CreateAPIKeyResponseToJSON,
    DataPlaneAppResponseFromJSON,
    DataPlaneAppResponseToJSON,
} from '../models/index';

export interface CliAuthorizeRequest {
    clientId: string;
    redirectUri: string;
    responseType: string;
    state: string;
    codeChallenge: string;
    codeChallengeMethod: string;
}

export interface CliTokenExchangeRequest {
    request: CLITokenRequest;
}

export interface CliTokenRefreshRequest {
    request: CLIRefreshTokenRequest;
}

export interface CreateApiKeyRequest {
    orgId: string;
    request: CreateAPIKeyRequest;
}

/**
 * 
 */
export class McpCliApi extends runtime.BaseAPI {

    /**
     * Creates request options for cliAuthorize without sending the request
     */
    async cliAuthorizeRequestOpts(requestParameters: CliAuthorizeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['clientId'] == null) {
            throw new runtime.RequiredError(
                'clientId',
                'Required parameter "clientId" was null or undefined when calling cliAuthorize().'
            );
        }

        if (requestParameters['redirectUri'] == null) {
            throw new runtime.RequiredError(
                'redirectUri',
                'Required parameter "redirectUri" was null or undefined when calling cliAuthorize().'
            );
        }

        if (requestParameters['responseType'] == null) {
            throw new runtime.RequiredError(
                'responseType',
                'Required parameter "responseType" was null or undefined when calling cliAuthorize().'
            );
        }

        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling cliAuthorize().'
            );
        }

        if (requestParameters['codeChallenge'] == null) {
            throw new runtime.RequiredError(
                'codeChallenge',
                'Required parameter "codeChallenge" was null or undefined when calling cliAuthorize().'
            );
        }

        if (requestParameters['codeChallengeMethod'] == null) {
            throw new runtime.RequiredError(
                'codeChallengeMethod',
                'Required parameter "codeChallengeMethod" was null or undefined when calling cliAuthorize().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['clientId'] != null) {
            queryParameters['client_id'] = requestParameters['clientId'];
        }

        if (requestParameters['redirectUri'] != null) {
            queryParameters['redirect_uri'] = requestParameters['redirectUri'];
        }

        if (requestParameters['responseType'] != null) {
            queryParameters['response_type'] = requestParameters['responseType'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['codeChallenge'] != null) {
            queryParameters['code_challenge'] = requestParameters['codeChallenge'];
        }

        if (requestParameters['codeChallengeMethod'] != null) {
            queryParameters['code_challenge_method'] = requestParameters['codeChallengeMethod'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/cli/authorize`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Issues a CLI OAuth authorization code for the authenticated user
     * CLI OAuth Authorization
     */
    async cliAuthorizeRaw(requestParameters: CliAuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CLIAuthorizeResponse>> {
        const requestOptions = await this.cliAuthorizeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CLIAuthorizeResponseFromJSON(jsonValue));
    }

    /**
     * Issues a CLI OAuth authorization code for the authenticated user
     * CLI OAuth Authorization
     */
    async cliAuthorize(requestParameters: CliAuthorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CLIAuthorizeResponse> {
        const response = await this.cliAuthorizeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cliTokenExchange without sending the request
     */
    async cliTokenExchangeRequestOpts(requestParameters: CliTokenExchangeRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling cliTokenExchange().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/cli/token`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CLITokenRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Exchanges authorization code for access and refresh tokens
     * CLI OAuth Token Exchange
     */
    async cliTokenExchangeRaw(requestParameters: CliTokenExchangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CLITokenResponse>> {
        const requestOptions = await this.cliTokenExchangeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CLITokenResponseFromJSON(jsonValue));
    }

    /**
     * Exchanges authorization code for access and refresh tokens
     * CLI OAuth Token Exchange
     */
    async cliTokenExchange(requestParameters: CliTokenExchangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CLITokenResponse> {
        const response = await this.cliTokenExchangeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cliTokenRefresh without sending the request
     */
    async cliTokenRefreshRequestOpts(requestParameters: CliTokenRefreshRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling cliTokenRefresh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/cli/token/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CLIRefreshTokenRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Refreshes an access token using a refresh token
     * CLI OAuth Token Refresh
     */
    async cliTokenRefreshRaw(requestParameters: CliTokenRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CLITokenResponse>> {
        const requestOptions = await this.cliTokenRefreshRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CLITokenResponseFromJSON(jsonValue));
    }

    /**
     * Refreshes an access token using a refresh token
     * CLI OAuth Token Refresh
     */
    async cliTokenRefresh(requestParameters: CliTokenRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CLITokenResponse> {
        const response = await this.cliTokenRefreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createApiKey without sending the request
     */
    async createApiKeyRequestOpts(requestParameters: CreateApiKeyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['orgId'] == null) {
            throw new runtime.RequiredError(
                'orgId',
                'Required parameter "orgId" was null or undefined when calling createApiKey().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling createApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/dashboard/organizations/{orgId}/api-keys`;
        urlPath = urlPath.replace(`{${"orgId"}}`, encodeURIComponent(String(requestParameters['orgId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAPIKeyRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Create a new API key for the organization. Returns the full key value only once.
     * Create API key
     */
    async createApiKeyRaw(requestParameters: CreateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAPIKeyResponse>> {
        const requestOptions = await this.createApiKeyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAPIKeyResponseFromJSON(jsonValue));
    }

    /**
     * Create a new API key for the organization. Returns the full key value only once.
     * Create API key
     */
    async createApiKey(requestParameters: CreateApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAPIKeyResponse> {
        const response = await this.createApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listApps without sending the request
     */
    async listAppsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/dashboard/apps`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all applications belonging to the authenticated organization
     * List applications
     */
    async listAppsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DataPlaneAppResponse>>> {
        const requestOptions = await this.listAppsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DataPlaneAppResponseFromJSON));
    }

    /**
     * List all applications belonging to the authenticated organization
     * List applications
     */
    async listApps(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DataPlaneAppResponse>> {
        const response = await this.listAppsRaw(initOverrides);
        return await response.value();
    }

}
