/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddMemberRequest
 */
export interface AddMemberRequest {
    /**
     * 
     * @type {string}
     * @memberof AddMemberRequest
     */
    email: string;
    /**
     * 
     * @type {AddMemberRequestRoleEnum}
     * @memberof AddMemberRequest
     */
    role?: AddMemberRequestRoleEnum;
}


/**
 * @export
 */
export const AddMemberRequestRoleEnum = {
    Admin: 'admin',
    Member: 'member'
} as const;
export type AddMemberRequestRoleEnum = typeof AddMemberRequestRoleEnum[keyof typeof AddMemberRequestRoleEnum];


/**
 * Check if a given object implements the AddMemberRequest interface.
 */
export function instanceOfAddMemberRequest(value: object): value is AddMemberRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AddMemberRequestFromJSON(json: any): AddMemberRequest {
    return AddMemberRequestFromJSONTyped(json, false);
}

export function AddMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function AddMemberRequestToJSON(json: any): AddMemberRequest {
    return AddMemberRequestToJSONTyped(json, false);
}

export function AddMemberRequestToJSONTyped(value?: AddMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'role': value['role'],
    };
}

