/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocationCount } from './LocationCount';
import {
    LocationCountFromJSON,
    LocationCountFromJSONTyped,
    LocationCountToJSON,
    LocationCountToJSONTyped,
} from './LocationCount';

/**
 * 
 * @export
 * @interface AdminStatsResponse
 */
export interface AdminStatsResponse {
    /**
     * ActiveSubs is the number of organizations with an active paid subscription.
     * @type {number}
     * @memberof AdminStatsResponse
     */
    activeSubs?: number;
    /**
     * AdminUsers is the number of users with platform admin privileges.
     * @type {number}
     * @memberof AdminStatsResponse
     */
    adminUsers?: number;
    /**
     * FreeUsers is the number of users on a free plan.
     * @type {number}
     * @memberof AdminStatsResponse
     */
    freeUsers?: number;
    /**
     * PaidUsers is the number of users on a paid plan.
     * @type {number}
     * @memberof AdminStatsResponse
     */
    paidUsers?: number;
    /**
     * TopLocations is the ranked list of countries by user count.
     * @type {Array<LocationCount>}
     * @memberof AdminStatsResponse
     */
    topLocations?: Array<LocationCount>;
    /**
     * TotalUsers is the total number of registered user accounts on the platform.
     * @type {number}
     * @memberof AdminStatsResponse
     */
    totalUsers?: number;
    /**
     * TrialExhausted is the number of users whose trial credits are fully consumed.
     * @type {number}
     * @memberof AdminStatsResponse
     */
    trialExhausted?: number;
}

/**
 * Check if a given object implements the AdminStatsResponse interface.
 */
export function instanceOfAdminStatsResponse(value: object): value is AdminStatsResponse {
    return true;
}

export function AdminStatsResponseFromJSON(json: any): AdminStatsResponse {
    return AdminStatsResponseFromJSONTyped(json, false);
}

export function AdminStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'activeSubs': json['active_subs'] == null ? undefined : json['active_subs'],
        'adminUsers': json['admin_users'] == null ? undefined : json['admin_users'],
        'freeUsers': json['free_users'] == null ? undefined : json['free_users'],
        'paidUsers': json['paid_users'] == null ? undefined : json['paid_users'],
        'topLocations': json['top_locations'] == null ? undefined : ((json['top_locations'] as Array<any>).map(LocationCountFromJSON)),
        'totalUsers': json['total_users'] == null ? undefined : json['total_users'],
        'trialExhausted': json['trial_exhausted'] == null ? undefined : json['trial_exhausted'],
    };
}

export function AdminStatsResponseToJSON(json: any): AdminStatsResponse {
    return AdminStatsResponseToJSONTyped(json, false);
}

export function AdminStatsResponseToJSONTyped(value?: AdminStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_subs': value['activeSubs'],
        'admin_users': value['adminUsers'],
        'free_users': value['freeUsers'],
        'paid_users': value['paidUsers'],
        'top_locations': value['topLocations'] == null ? undefined : ((value['topLocations'] as Array<any>).map(LocationCountToJSON)),
        'total_users': value['totalUsers'],
        'trial_exhausted': value['trialExhausted'],
    };
}

