/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminOrgResponse
 */
export interface AdminOrgResponse {
    /**
     * ActiveMemberCount is the number of active members in the organization.
     * @type {number}
     * @memberof AdminOrgResponse
     */
    activeMemberCount?: number;
    /**
     * BlockedMemberCount is the number of blocked/suspended members.
     * @type {number}
     * @memberof AdminOrgResponse
     */
    blockedMemberCount?: number;
    /**
     * CountryCode is the ISO 3166-1 alpha-2 country code for the organization.
     * @type {string}
     * @memberof AdminOrgResponse
     */
    countryCode?: string;
    /**
     * CreatedAt is when the organization was created.
     * @type {string}
     * @memberof AdminOrgResponse
     */
    createdAt?: string;
    /**
     * ID is the organization's unique identifier.
     * @type {string}
     * @memberof AdminOrgResponse
     */
    id?: string;
    /**
     * MemCreditsGranted is the total memory credits granted for the current period.
     * @type {number}
     * @memberof AdminOrgResponse
     */
    memCreditsGranted?: number;
    /**
     * MemCreditsUsed is the memory credits consumed in the current period.
     * @type {number}
     * @memberof AdminOrgResponse
     */
    memCreditsUsed?: number;
    /**
     * MemUsagePct is the memory credit usage percentage (0.0-100.0).
     * @type {number}
     * @memberof AdminOrgResponse
     */
    memUsagePct?: number;
    /**
     * Name is the organization's display name.
     * @type {string}
     * @memberof AdminOrgResponse
     */
    name?: string;
    /**
     * PendingInviteCount is the number of outstanding invitations.
     * @type {number}
     * @memberof AdminOrgResponse
     */
    pendingInviteCount?: number;
    /**
     * PlanID is the ID of the plan this organization is subscribed to.
     * @type {string}
     * @memberof AdminOrgResponse
     */
    planId?: string;
    /**
     * PlanName is the human-readable name of the plan.
     * @type {string}
     * @memberof AdminOrgResponse
     */
    planName?: string;
    /**
     * PlanSlug is the URL-safe identifier of the plan.
     * @type {string}
     * @memberof AdminOrgResponse
     */
    planSlug?: string;
    /**
     * Slug is the URL-safe identifier for the organization.
     * @type {string}
     * @memberof AdminOrgResponse
     */
    slug?: string;
    /**
     * SrchCreditsGranted is the total search credits granted for the current period.
     * @type {number}
     * @memberof AdminOrgResponse
     */
    srchCreditsGranted?: number;
    /**
     * SrchCreditsUsed is the search credits consumed in the current period.
     * @type {number}
     * @memberof AdminOrgResponse
     */
    srchCreditsUsed?: number;
    /**
     * SrchUsagePct is the search credit usage percentage (0.0-100.0).
     * @type {number}
     * @memberof AdminOrgResponse
     */
    srchUsagePct?: number;
    /**
     * Status is the organization's current status (e.g., "active", "suspended").
     * @type {string}
     * @memberof AdminOrgResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the AdminOrgResponse interface.
 */
export function instanceOfAdminOrgResponse(value: object): value is AdminOrgResponse {
    return true;
}

export function AdminOrgResponseFromJSON(json: any): AdminOrgResponse {
    return AdminOrgResponseFromJSONTyped(json, false);
}

export function AdminOrgResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminOrgResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'activeMemberCount': json['active_member_count'] == null ? undefined : json['active_member_count'],
        'blockedMemberCount': json['blocked_member_count'] == null ? undefined : json['blocked_member_count'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'memCreditsGranted': json['mem_credits_granted'] == null ? undefined : json['mem_credits_granted'],
        'memCreditsUsed': json['mem_credits_used'] == null ? undefined : json['mem_credits_used'],
        'memUsagePct': json['mem_usage_pct'] == null ? undefined : json['mem_usage_pct'],
        'name': json['name'] == null ? undefined : json['name'],
        'pendingInviteCount': json['pending_invite_count'] == null ? undefined : json['pending_invite_count'],
        'planId': json['plan_id'] == null ? undefined : json['plan_id'],
        'planName': json['plan_name'] == null ? undefined : json['plan_name'],
        'planSlug': json['plan_slug'] == null ? undefined : json['plan_slug'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'srchCreditsGranted': json['srch_credits_granted'] == null ? undefined : json['srch_credits_granted'],
        'srchCreditsUsed': json['srch_credits_used'] == null ? undefined : json['srch_credits_used'],
        'srchUsagePct': json['srch_usage_pct'] == null ? undefined : json['srch_usage_pct'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AdminOrgResponseToJSON(json: any): AdminOrgResponse {
    return AdminOrgResponseToJSONTyped(json, false);
}

export function AdminOrgResponseToJSONTyped(value?: AdminOrgResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_member_count': value['activeMemberCount'],
        'blocked_member_count': value['blockedMemberCount'],
        'country_code': value['countryCode'],
        'created_at': value['createdAt'],
        'id': value['id'],
        'mem_credits_granted': value['memCreditsGranted'],
        'mem_credits_used': value['memCreditsUsed'],
        'mem_usage_pct': value['memUsagePct'],
        'name': value['name'],
        'pending_invite_count': value['pendingInviteCount'],
        'plan_id': value['planId'],
        'plan_name': value['planName'],
        'plan_slug': value['planSlug'],
        'slug': value['slug'],
        'srch_credits_granted': value['srchCreditsGranted'],
        'srch_credits_used': value['srchCreditsUsed'],
        'srch_usage_pct': value['srchUsagePct'],
        'status': value['status'],
    };
}

