/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminStaleAppResponse
 */
export interface AdminStaleAppResponse {
    /**
     * AppID is the app's identifier.
     * @type {string}
     * @memberof AdminStaleAppResponse
     */
    appId?: string;
    /**
     * CreatedAt is the creation timestamp.
     * @type {string}
     * @memberof AdminStaleAppResponse
     */
    createdAt?: string;
    /**
     * DataPlaneID is the data plane where the app was pinned.
     * @type {string}
     * @memberof AdminStaleAppResponse
     */
    dataPlaneId?: string;
    /**
     * DeletedAt is the soft-delete timestamp.
     * @type {string}
     * @memberof AdminStaleAppResponse
     */
    deletedAt?: string;
    /**
     * ID is the unique identifier for the org-app association.
     * @type {string}
     * @memberof AdminStaleAppResponse
     */
    id?: string;
    /**
     * OrganizationID is the organization that owned the app.
     * @type {string}
     * @memberof AdminStaleAppResponse
     */
    organizationId?: string;
    /**
     * SyncStatus is the last known sync status (e.g., "synced").
     * @type {string}
     * @memberof AdminStaleAppResponse
     */
    syncStatus?: string;
    /**
     * UpdatedAt is the last update timestamp.
     * @type {string}
     * @memberof AdminStaleAppResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the AdminStaleAppResponse interface.
 */
export function instanceOfAdminStaleAppResponse(value: object): value is AdminStaleAppResponse {
    return true;
}

export function AdminStaleAppResponseFromJSON(json: any): AdminStaleAppResponse {
    return AdminStaleAppResponseFromJSONTyped(json, false);
}

export function AdminStaleAppResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminStaleAppResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'dataPlaneId': json['data_plane_id'] == null ? undefined : json['data_plane_id'],
        'deletedAt': json['deleted_at'] == null ? undefined : json['deleted_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'syncStatus': json['sync_status'] == null ? undefined : json['sync_status'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function AdminStaleAppResponseToJSON(json: any): AdminStaleAppResponse {
    return AdminStaleAppResponseToJSONTyped(json, false);
}

export function AdminStaleAppResponseToJSONTyped(value?: AdminStaleAppResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'created_at': value['createdAt'],
        'data_plane_id': value['dataPlaneId'],
        'deleted_at': value['deletedAt'],
        'id': value['id'],
        'organization_id': value['organizationId'],
        'sync_status': value['syncStatus'],
        'updated_at': value['updatedAt'],
    };
}

