/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdminAPIKeyResponse
 */
export interface AdminAPIKeyResponse {
    /**
     * AppID is the smritea app this key is scoped to.
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    appId?: string;
    /**
     * AppName is the display name of the associated smritea app.
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    appName?: string;
    /**
     * CreatedAt is when the API key was created.
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    createdAt?: string;
    /**
     * CreatedByID is the user ID of the platform user who created this key.
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    createdById?: string;
    /**
     * ExpiresAt is the optional expiry timestamp for this key.
     * Nil if the key has no expiry.
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    expiresAt?: string;
    /**
     * ID is the API key's unique identifier.
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    id?: string;
    /**
     * KeyPrefix is the non-secret prefix of the API key.
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    keyPrefix?: string;
    /**
     * LastUsed is the timestamp of the most recent authenticated request using this key.
     * Nil if the key has never been used.
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    lastUsed?: string;
    /**
     * Name is the human-readable label for this API key.
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    name?: string;
    /**
     * OrgID is the organization that owns this API key.
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    orgId?: string;
    /**
     * OrgName is the display name of the owning organization.
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    orgName?: string;
    /**
     * Status is the key's current status (e.g., "active", "revoked").
     * @type {string}
     * @memberof AdminAPIKeyResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the AdminAPIKeyResponse interface.
 */
export function instanceOfAdminAPIKeyResponse(value: object): value is AdminAPIKeyResponse {
    return true;
}

export function AdminAPIKeyResponseFromJSON(json: any): AdminAPIKeyResponse {
    return AdminAPIKeyResponseFromJSONTyped(json, false);
}

export function AdminAPIKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminAPIKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'appName': json['app_name'] == null ? undefined : json['app_name'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'createdById': json['created_by_id'] == null ? undefined : json['created_by_id'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'keyPrefix': json['key_prefix'] == null ? undefined : json['key_prefix'],
        'lastUsed': json['last_used'] == null ? undefined : json['last_used'],
        'name': json['name'] == null ? undefined : json['name'],
        'orgId': json['org_id'] == null ? undefined : json['org_id'],
        'orgName': json['org_name'] == null ? undefined : json['org_name'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AdminAPIKeyResponseToJSON(json: any): AdminAPIKeyResponse {
    return AdminAPIKeyResponseToJSONTyped(json, false);
}

export function AdminAPIKeyResponseToJSONTyped(value?: AdminAPIKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'app_name': value['appName'],
        'created_at': value['createdAt'],
        'created_by_id': value['createdById'],
        'expires_at': value['expiresAt'],
        'id': value['id'],
        'key_prefix': value['keyPrefix'],
        'last_used': value['lastUsed'],
        'name': value['name'],
        'org_id': value['orgId'],
        'org_name': value['orgName'],
        'status': value['status'],
    };
}

