/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIKeyDetails
 */
export interface APIKeyDetails {
    /**
     * 
     * @type {string}
     * @memberof APIKeyDetails
     */
    appId?: string;
    /**
     * Application name (fetched via JOIN for UI convenience)
     * @type {string}
     * @memberof APIKeyDetails
     */
    appName?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyDetails
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyDetails
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyDetails
     */
    expiresAt?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyDetails
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyDetails
     */
    keyPrefix?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyDetails
     */
    lastUsed?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyDetails
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof APIKeyDetails
     */
    organizationId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof APIKeyDetails
     */
    scopes?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof APIKeyDetails
     */
    status?: string;
}

/**
 * Check if a given object implements the APIKeyDetails interface.
 */
export function instanceOfAPIKeyDetails(value: object): value is APIKeyDetails {
    return true;
}

export function APIKeyDetailsFromJSON(json: any): APIKeyDetails {
    return APIKeyDetailsFromJSONTyped(json, false);
}

export function APIKeyDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIKeyDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'appName': json['app_name'] == null ? undefined : json['app_name'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'keyPrefix': json['key_prefix'] == null ? undefined : json['key_prefix'],
        'lastUsed': json['last_used'] == null ? undefined : json['last_used'],
        'name': json['name'] == null ? undefined : json['name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function APIKeyDetailsToJSON(json: any): APIKeyDetails {
    return APIKeyDetailsToJSONTyped(json, false);
}

export function APIKeyDetailsToJSONTyped(value?: APIKeyDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'app_name': value['appName'],
        'created_at': value['createdAt'],
        'created_by': value['createdBy'],
        'expires_at': value['expiresAt'],
        'id': value['id'],
        'key_prefix': value['keyPrefix'],
        'last_used': value['lastUsed'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'scopes': value['scopes'],
        'status': value['status'],
    };
}

