/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppAIProviderStatus } from './AppAIProviderStatus';
import {
    AppAIProviderStatusFromJSON,
    AppAIProviderStatusFromJSONTyped,
    AppAIProviderStatusToJSON,
    AppAIProviderStatusToJSONTyped,
} from './AppAIProviderStatus';

/**
 * 
 * @export
 * @interface AppAIConfigStatus
 */
export interface AppAIConfigStatus {
    /**
     * Configured indicates whether AI config has been set for this app
     * @type {boolean}
     * @memberof AppAIConfigStatus
     */
    configured?: boolean;
    /**
     * Embedding shows the configured embedding provider status (nil if not configured)
     * @type {AppAIProviderStatus}
     * @memberof AppAIConfigStatus
     */
    embedding?: AppAIProviderStatus;
    /**
     * LLM shows the configured LLM provider status (nil if not configured)
     * @type {AppAIProviderStatus}
     * @memberof AppAIConfigStatus
     */
    llm?: AppAIProviderStatus;
    /**
     * Reranker shows the configured reranker provider status (nil if not configured)
     * @type {AppAIProviderStatus}
     * @memberof AppAIConfigStatus
     */
    reranker?: AppAIProviderStatus;
}

/**
 * Check if a given object implements the AppAIConfigStatus interface.
 */
export function instanceOfAppAIConfigStatus(value: object): value is AppAIConfigStatus {
    return true;
}

export function AppAIConfigStatusFromJSON(json: any): AppAIConfigStatus {
    return AppAIConfigStatusFromJSONTyped(json, false);
}

export function AppAIConfigStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppAIConfigStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'configured': json['configured'] == null ? undefined : json['configured'],
        'embedding': json['embedding'] == null ? undefined : AppAIProviderStatusFromJSON(json['embedding']),
        'llm': json['llm'] == null ? undefined : AppAIProviderStatusFromJSON(json['llm']),
        'reranker': json['reranker'] == null ? undefined : AppAIProviderStatusFromJSON(json['reranker']),
    };
}

export function AppAIConfigStatusToJSON(json: any): AppAIConfigStatus {
    return AppAIConfigStatusToJSONTyped(json, false);
}

export function AppAIConfigStatusToJSONTyped(value?: AppAIConfigStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configured': value['configured'],
        'embedding': AppAIProviderStatusToJSON(value['embedding']),
        'llm': AppAIProviderStatusToJSON(value['llm']),
        'reranker': AppAIProviderStatusToJSON(value['reranker']),
    };
}

