/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppConfigKind = {
    AppConfigKindExtraction: 'extraction',
    AppConfigKindSearch: 'search',
    AppConfigKindDirective: 'directive'
} as const;
export type AppConfigKind = typeof AppConfigKind[keyof typeof AppConfigKind];


export function instanceOfAppConfigKind(value: any): boolean {
    for (const key in AppConfigKind) {
        if (Object.prototype.hasOwnProperty.call(AppConfigKind, key)) {
            if (AppConfigKind[key as keyof typeof AppConfigKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppConfigKindFromJSON(json: any): AppConfigKind {
    return AppConfigKindFromJSONTyped(json, false);
}

export function AppConfigKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppConfigKind {
    return json as AppConfigKind;
}

export function AppConfigKindToJSON(value?: AppConfigKind | null): any {
    return value as any;
}

export function AppConfigKindToJSONTyped(value: any, ignoreDiscriminator: boolean): AppConfigKind {
    return value as AppConfigKind;
}

