/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppEmbeddingConnection
 */
export interface AppEmbeddingConnection {
    /**
     * APIKey is the API credential for the provider.
     * Masked in JSON output and logs; access the real value via .Value().
     * Not required for ollama (self-hosted, no API key needed).
     * @type {string}
     * @memberof AppEmbeddingConnection
     */
    apiKey?: string;
    /**
     * BaseURL is the custom endpoint for openai_custom provider variant.
     * Must be a valid URL. Required for openai_custom.
     * Leave empty for standard hosted providers.
     * @type {string}
     * @memberof AppEmbeddingConnection
     */
    baseUrl?: string;
    /**
     * Dimensions is the output dimensionality of the embedding vectors.
     * Defaults to 2048 when not specified (voyage-4). Must be between 1 and 4096.
     * Once set for an app, this value must not be changed as it is tied
     * to the existing vector index and stored embeddings.
     * @type {number}
     * @memberof AppEmbeddingConnection
     */
    dimensions?: number;
    /**
     * Model is the specific embedding model name (e.g., "text-embedding-3-small").
     * When empty, the provider's configured default model is used.
     * Required for "_custom" providers.
     * @type {string}
     * @memberof AppEmbeddingConnection
     */
    model?: string;
    /**
     * Provider is the embedding provider identifier.
     * @type {AppEmbeddingConnectionProviderEnum}
     * @memberof AppEmbeddingConnection
     */
    provider: AppEmbeddingConnectionProviderEnum;
}


/**
 * @export
 */
export const AppEmbeddingConnectionProviderEnum = {
    Openai: 'openai',
    Voyageai: 'voyageai',
    Ollama: 'ollama',
    OpenaiCustom: 'openai_custom'
} as const;
export type AppEmbeddingConnectionProviderEnum = typeof AppEmbeddingConnectionProviderEnum[keyof typeof AppEmbeddingConnectionProviderEnum];


/**
 * Check if a given object implements the AppEmbeddingConnection interface.
 */
export function instanceOfAppEmbeddingConnection(value: object): value is AppEmbeddingConnection {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function AppEmbeddingConnectionFromJSON(json: any): AppEmbeddingConnection {
    return AppEmbeddingConnectionFromJSONTyped(json, false);
}

export function AppEmbeddingConnectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppEmbeddingConnection {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'baseUrl': json['base_url'] == null ? undefined : json['base_url'],
        'dimensions': json['dimensions'] == null ? undefined : json['dimensions'],
        'model': json['model'] == null ? undefined : json['model'],
        'provider': json['provider'],
    };
}

export function AppEmbeddingConnectionToJSON(json: any): AppEmbeddingConnection {
    return AppEmbeddingConnectionToJSONTyped(json, false);
}

export function AppEmbeddingConnectionToJSONTyped(value?: AppEmbeddingConnection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': value['apiKey'],
        'base_url': value['baseUrl'],
        'dimensions': value['dimensions'],
        'model': value['model'],
        'provider': value['provider'],
    };
}

