/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuditEntryResponse } from './AuditEntryResponse';
import {
    AuditEntryResponseFromJSON,
    AuditEntryResponseFromJSONTyped,
    AuditEntryResponseToJSON,
    AuditEntryResponseToJSONTyped,
} from './AuditEntryResponse';

/**
 * Audit query response
 * @export
 * @interface AuditQueryResponse
 */
export interface AuditQueryResponse {
    /**
     * 
     * @type {Array<AuditEntryResponse>}
     * @memberof AuditQueryResponse
     */
    entries?: Array<AuditEntryResponse>;
    /**
     * 
     * @type {number}
     * @memberof AuditQueryResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof AuditQueryResponse
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof AuditQueryResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the AuditQueryResponse interface.
 */
export function instanceOfAuditQueryResponse(value: object): value is AuditQueryResponse {
    return true;
}

export function AuditQueryResponseFromJSON(json: any): AuditQueryResponse {
    return AuditQueryResponseFromJSONTyped(json, false);
}

export function AuditQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': json['entries'] == null ? undefined : ((json['entries'] as Array<any>).map(AuditEntryResponseFromJSON)),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function AuditQueryResponseToJSON(json: any): AuditQueryResponse {
    return AuditQueryResponseToJSONTyped(json, false);
}

export function AuditQueryResponseToJSONTyped(value?: AuditQueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entries': value['entries'] == null ? undefined : ((value['entries'] as Array<any>).map(AuditEntryResponseToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

