/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Audit entry response
 * @export
 * @interface AuditEntryResponse
 */
export interface AuditEntryResponse {
    /**
     * 
     * @type {string}
     * @memberof AuditEntryResponse
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditEntryResponse
     */
    actorId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditEntryResponse
     */
    appId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditEntryResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof AuditEntryResponse
     */
    details?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof AuditEntryResponse
     */
    errorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditEntryResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditEntryResponse
     */
    ipAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditEntryResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuditEntryResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the AuditEntryResponse interface.
 */
export function instanceOfAuditEntryResponse(value: object): value is AuditEntryResponse {
    return true;
}

export function AuditEntryResponseFromJSON(json: any): AuditEntryResponse {
    return AuditEntryResponseFromJSONTyped(json, false);
}

export function AuditEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditEntryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'actorId': json['actor_id'] == null ? undefined : json['actor_id'],
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'details': json['details'] == null ? undefined : json['details'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'id': json['id'] == null ? undefined : json['id'],
        'ipAddress': json['ip_address'] == null ? undefined : json['ip_address'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function AuditEntryResponseToJSON(json: any): AuditEntryResponse {
    return AuditEntryResponseToJSONTyped(json, false);
}

export function AuditEntryResponseToJSONTyped(value?: AuditEntryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'actor_id': value['actorId'],
        'app_id': value['appId'],
        'created_at': value['createdAt'],
        'details': value['details'],
        'error_message': value['errorMessage'],
        'id': value['id'],
        'ip_address': value['ipAddress'],
        'request_id': value['requestId'],
        'success': value['success'],
    };
}

