/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthChangePasswordRequest
 */
export interface AuthChangePasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthChangePasswordRequest
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof AuthChangePasswordRequest
     */
    oldPassword: string;
}

/**
 * Check if a given object implements the AuthChangePasswordRequest interface.
 */
export function instanceOfAuthChangePasswordRequest(value: object): value is AuthChangePasswordRequest {
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('oldPassword' in value) || value['oldPassword'] === undefined) return false;
    return true;
}

export function AuthChangePasswordRequestFromJSON(json: any): AuthChangePasswordRequest {
    return AuthChangePasswordRequestFromJSONTyped(json, false);
}

export function AuthChangePasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthChangePasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newPassword': json['new_password'],
        'oldPassword': json['old_password'],
    };
}

export function AuthChangePasswordRequestToJSON(json: any): AuthChangePasswordRequest {
    return AuthChangePasswordRequestToJSONTyped(json, false);
}

export function AuthChangePasswordRequestToJSONTyped(value?: AuthChangePasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_password': value['newPassword'],
        'old_password': value['oldPassword'],
    };
}

