/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSetPasswordRequest
 */
export interface AuthSetPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthSetPasswordRequest
     */
    newPassword: string;
}

/**
 * Check if a given object implements the AuthSetPasswordRequest interface.
 */
export function instanceOfAuthSetPasswordRequest(value: object): value is AuthSetPasswordRequest {
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    return true;
}

export function AuthSetPasswordRequestFromJSON(json: any): AuthSetPasswordRequest {
    return AuthSetPasswordRequestFromJSONTyped(json, false);
}

export function AuthSetPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSetPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newPassword': json['new_password'],
    };
}

export function AuthSetPasswordRequestToJSON(json: any): AuthSetPasswordRequest {
    return AuthSetPasswordRequestToJSONTyped(json, false);
}

export function AuthSetPasswordRequestToJSONTyped(value?: AuthSetPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_password': value['newPassword'],
    };
}

