/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckoutPayloadResponse } from './CheckoutPayloadResponse';
import {
    CheckoutPayloadResponseFromJSON,
    CheckoutPayloadResponseFromJSONTyped,
    CheckoutPayloadResponseToJSON,
    CheckoutPayloadResponseToJSONTyped,
} from './CheckoutPayloadResponse';

/**
 * 
 * @export
 * @interface CheckoutResponse
 */
export interface CheckoutResponse {
    /**
     * 
     * @type {CheckoutPayloadResponse}
     * @memberof CheckoutResponse
     */
    checkout?: CheckoutPayloadResponse;
    /**
     * 
     * @type {string}
     * @memberof CheckoutResponse
     */
    orderId?: string;
}

/**
 * Check if a given object implements the CheckoutResponse interface.
 */
export function instanceOfCheckoutResponse(value: object): value is CheckoutResponse {
    return true;
}

export function CheckoutResponseFromJSON(json: any): CheckoutResponse {
    return CheckoutResponseFromJSONTyped(json, false);
}

export function CheckoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'checkout': json['checkout'] == null ? undefined : CheckoutPayloadResponseFromJSON(json['checkout']),
        'orderId': json['order_id'] == null ? undefined : json['order_id'],
    };
}

export function CheckoutResponseToJSON(json: any): CheckoutResponse {
    return CheckoutResponseToJSONTyped(json, false);
}

export function CheckoutResponseToJSONTyped(value?: CheckoutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checkout': CheckoutPayloadResponseToJSON(value['checkout']),
        'order_id': value['orderId'],
    };
}

