/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CLIAuthorizeResponse
 */
export interface CLIAuthorizeResponse {
    /**
     * RedirectURL is the full localhost callback URL with auth code and state params.
     * @type {string}
     * @memberof CLIAuthorizeResponse
     */
    redirectUrl?: string;
}

/**
 * Check if a given object implements the CLIAuthorizeResponse interface.
 */
export function instanceOfCLIAuthorizeResponse(value: object): value is CLIAuthorizeResponse {
    return true;
}

export function CLIAuthorizeResponseFromJSON(json: any): CLIAuthorizeResponse {
    return CLIAuthorizeResponseFromJSONTyped(json, false);
}

export function CLIAuthorizeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CLIAuthorizeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectUrl': json['redirect_url'] == null ? undefined : json['redirect_url'],
    };
}

export function CLIAuthorizeResponseToJSON(json: any): CLIAuthorizeResponse {
    return CLIAuthorizeResponseToJSONTyped(json, false);
}

export function CLIAuthorizeResponseToJSONTyped(value?: CLIAuthorizeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect_url': value['redirectUrl'],
    };
}

