/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CLITokenRequest
 */
export interface CLITokenRequest {
    /**
     * ClientID identifies the CLI client application.
     * Must be "smritea-plugin" for the official Smritea CLI plugin.
     * @type {CLITokenRequestClientIdEnum}
     * @memberof CLITokenRequest
     */
    clientId: CLITokenRequestClientIdEnum;
    /**
     * Code is the authorization code received from the authorize endpoint.
     * @type {string}
     * @memberof CLITokenRequest
     */
    code: string;
    /**
     * CodeVerifier is the original plaintext code verifier used to generate code_challenge.
     * Must be 43-128 characters with sufficient entropy.
     * @type {string}
     * @memberof CLITokenRequest
     */
    codeVerifier: string;
    /**
     * GrantType must be "authorization_code" for this flow.
     * @type {CLITokenRequestGrantTypeEnum}
     * @memberof CLITokenRequest
     */
    grantType: CLITokenRequestGrantTypeEnum;
    /**
     * RedirectURI must match the redirect_uri used in the authorization request.
     * @type {string}
     * @memberof CLITokenRequest
     */
    redirectUri: string;
}


/**
 * @export
 */
export const CLITokenRequestClientIdEnum = {
    SmriteaPlugin: 'smritea-plugin'
} as const;
export type CLITokenRequestClientIdEnum = typeof CLITokenRequestClientIdEnum[keyof typeof CLITokenRequestClientIdEnum];

/**
 * @export
 */
export const CLITokenRequestGrantTypeEnum = {
    AuthorizationCode: 'authorization_code'
} as const;
export type CLITokenRequestGrantTypeEnum = typeof CLITokenRequestGrantTypeEnum[keyof typeof CLITokenRequestGrantTypeEnum];


/**
 * Check if a given object implements the CLITokenRequest interface.
 */
export function instanceOfCLITokenRequest(value: object): value is CLITokenRequest {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('codeVerifier' in value) || value['codeVerifier'] === undefined) return false;
    if (!('grantType' in value) || value['grantType'] === undefined) return false;
    if (!('redirectUri' in value) || value['redirectUri'] === undefined) return false;
    return true;
}

export function CLITokenRequestFromJSON(json: any): CLITokenRequest {
    return CLITokenRequestFromJSONTyped(json, false);
}

export function CLITokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CLITokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'code': json['code'],
        'codeVerifier': json['code_verifier'],
        'grantType': json['grant_type'],
        'redirectUri': json['redirect_uri'],
    };
}

export function CLITokenRequestToJSON(json: any): CLITokenRequest {
    return CLITokenRequestToJSONTyped(json, false);
}

export function CLITokenRequestToJSONTyped(value?: CLITokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'code': value['code'],
        'code_verifier': value['codeVerifier'],
        'grant_type': value['grantType'],
        'redirect_uri': value['redirectUri'],
    };
}

