/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CLITokenResponse
 */
export interface CLITokenResponse {
    /**
     * AccessToken is the bearer token for API authentication.
     * @type {string}
     * @memberof CLITokenResponse
     */
    accessToken?: string;
    /**
     * Email is the authenticated user's email address.
     * @type {string}
     * @memberof CLITokenResponse
     */
    email?: string;
    /**
     * ExpiresIn is the access token lifetime in seconds.
     * @type {number}
     * @memberof CLITokenResponse
     */
    expiresIn?: number;
    /**
     * OrganizationID is the user's default organization identifier.
     * @type {string}
     * @memberof CLITokenResponse
     */
    organizationId?: string;
    /**
     * RefreshToken can be used to obtain new access tokens.
     * @type {string}
     * @memberof CLITokenResponse
     */
    refreshToken?: string;
    /**
     * TokenType is always "Bearer" for this implementation.
     * @type {string}
     * @memberof CLITokenResponse
     */
    tokenType?: string;
    /**
     * UserID is the authenticated user's unique identifier.
     * @type {string}
     * @memberof CLITokenResponse
     */
    userId?: string;
}

/**
 * Check if a given object implements the CLITokenResponse interface.
 */
export function instanceOfCLITokenResponse(value: object): value is CLITokenResponse {
    return true;
}

export function CLITokenResponseFromJSON(json: any): CLITokenResponse {
    return CLITokenResponseFromJSONTyped(json, false);
}

export function CLITokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CLITokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'email': json['email'] == null ? undefined : json['email'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function CLITokenResponseToJSON(json: any): CLITokenResponse {
    return CLITokenResponseToJSONTyped(json, false);
}

export function CLITokenResponseToJSONTyped(value?: CLITokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'email': value['email'],
        'expires_in': value['expiresIn'],
        'organization_id': value['organizationId'],
        'refresh_token': value['refreshToken'],
        'token_type': value['tokenType'],
        'user_id': value['userId'],
    };
}

