/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { PlanResponse } from './PlanResponse';
import {
    PlanResponseFromJSON,
    PlanResponseFromJSONTyped,
    PlanResponseToJSON,
    PlanResponseToJSONTyped,
} from './PlanResponse';

/**
 * 
 * @export
 * @interface CommondtoPaginatedResponsePlanResponse
 */
export interface CommondtoPaginatedResponsePlanResponse {
    /**
     * Data contains the paginated items
     * @type {Array<PlanResponse>}
     * @memberof CommondtoPaginatedResponsePlanResponse
     */
    data?: Array<PlanResponse>;
    /**
     * Meta contains pagination metadata
     * @type {PaginationMeta}
     * @memberof CommondtoPaginatedResponsePlanResponse
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the CommondtoPaginatedResponsePlanResponse interface.
 */
export function instanceOfCommondtoPaginatedResponsePlanResponse(value: object): value is CommondtoPaginatedResponsePlanResponse {
    return true;
}

export function CommondtoPaginatedResponsePlanResponseFromJSON(json: any): CommondtoPaginatedResponsePlanResponse {
    return CommondtoPaginatedResponsePlanResponseFromJSONTyped(json, false);
}

export function CommondtoPaginatedResponsePlanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommondtoPaginatedResponsePlanResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PlanResponseFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function CommondtoPaginatedResponsePlanResponseToJSON(json: any): CommondtoPaginatedResponsePlanResponse {
    return CommondtoPaginatedResponsePlanResponseToJSONTyped(json, false);
}

export function CommondtoPaginatedResponsePlanResponseToJSONTyped(value?: CommondtoPaginatedResponsePlanResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PlanResponseToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

