/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { StudioAuditEntryResponse } from './StudioAuditEntryResponse';
import {
    StudioAuditEntryResponseFromJSON,
    StudioAuditEntryResponseFromJSONTyped,
    StudioAuditEntryResponseToJSON,
    StudioAuditEntryResponseToJSONTyped,
} from './StudioAuditEntryResponse';

/**
 * 
 * @export
 * @interface CommondtoPaginatedResponseStudioAuditEntryResponse
 */
export interface CommondtoPaginatedResponseStudioAuditEntryResponse {
    /**
     * Data contains the paginated items
     * @type {Array<StudioAuditEntryResponse>}
     * @memberof CommondtoPaginatedResponseStudioAuditEntryResponse
     */
    data?: Array<StudioAuditEntryResponse>;
    /**
     * Meta contains pagination metadata
     * @type {PaginationMeta}
     * @memberof CommondtoPaginatedResponseStudioAuditEntryResponse
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the CommondtoPaginatedResponseStudioAuditEntryResponse interface.
 */
export function instanceOfCommondtoPaginatedResponseStudioAuditEntryResponse(value: object): value is CommondtoPaginatedResponseStudioAuditEntryResponse {
    return true;
}

export function CommondtoPaginatedResponseStudioAuditEntryResponseFromJSON(json: any): CommondtoPaginatedResponseStudioAuditEntryResponse {
    return CommondtoPaginatedResponseStudioAuditEntryResponseFromJSONTyped(json, false);
}

export function CommondtoPaginatedResponseStudioAuditEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommondtoPaginatedResponseStudioAuditEntryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(StudioAuditEntryResponseFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function CommondtoPaginatedResponseStudioAuditEntryResponseToJSON(json: any): CommondtoPaginatedResponseStudioAuditEntryResponse {
    return CommondtoPaginatedResponseStudioAuditEntryResponseToJSONTyped(json, false);
}

export function CommondtoPaginatedResponseStudioAuditEntryResponseToJSONTyped(value?: CommondtoPaginatedResponseStudioAuditEntryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(StudioAuditEntryResponseToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

