/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminUserResponse } from './AdminUserResponse';
import {
    AdminUserResponseFromJSON,
    AdminUserResponseFromJSONTyped,
    AdminUserResponseToJSON,
    AdminUserResponseToJSONTyped,
} from './AdminUserResponse';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * 
 * @export
 * @interface CommondtoPaginatedResponseAdminUserResponse
 */
export interface CommondtoPaginatedResponseAdminUserResponse {
    /**
     * Data contains the paginated items
     * @type {Array<AdminUserResponse>}
     * @memberof CommondtoPaginatedResponseAdminUserResponse
     */
    data?: Array<AdminUserResponse>;
    /**
     * Meta contains pagination metadata
     * @type {PaginationMeta}
     * @memberof CommondtoPaginatedResponseAdminUserResponse
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the CommondtoPaginatedResponseAdminUserResponse interface.
 */
export function instanceOfCommondtoPaginatedResponseAdminUserResponse(value: object): value is CommondtoPaginatedResponseAdminUserResponse {
    return true;
}

export function CommondtoPaginatedResponseAdminUserResponseFromJSON(json: any): CommondtoPaginatedResponseAdminUserResponse {
    return CommondtoPaginatedResponseAdminUserResponseFromJSONTyped(json, false);
}

export function CommondtoPaginatedResponseAdminUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommondtoPaginatedResponseAdminUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AdminUserResponseFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function CommondtoPaginatedResponseAdminUserResponseToJSON(json: any): CommondtoPaginatedResponseAdminUserResponse {
    return CommondtoPaginatedResponseAdminUserResponseToJSONTyped(json, false);
}

export function CommondtoPaginatedResponseAdminUserResponseToJSONTyped(value?: CommondtoPaginatedResponseAdminUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AdminUserResponseToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

