/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeamInvitationDetails } from './TeamInvitationDetails';
import {
    TeamInvitationDetailsFromJSON,
    TeamInvitationDetailsFromJSONTyped,
    TeamInvitationDetailsToJSON,
    TeamInvitationDetailsToJSONTyped,
} from './TeamInvitationDetails';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * 
 * @export
 * @interface CommondtoPaginatedResponseTeamInvitationDetails
 */
export interface CommondtoPaginatedResponseTeamInvitationDetails {
    /**
     * Data contains the paginated items
     * @type {Array<TeamInvitationDetails>}
     * @memberof CommondtoPaginatedResponseTeamInvitationDetails
     */
    data?: Array<TeamInvitationDetails>;
    /**
     * Meta contains pagination metadata
     * @type {PaginationMeta}
     * @memberof CommondtoPaginatedResponseTeamInvitationDetails
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the CommondtoPaginatedResponseTeamInvitationDetails interface.
 */
export function instanceOfCommondtoPaginatedResponseTeamInvitationDetails(value: object): value is CommondtoPaginatedResponseTeamInvitationDetails {
    return true;
}

export function CommondtoPaginatedResponseTeamInvitationDetailsFromJSON(json: any): CommondtoPaginatedResponseTeamInvitationDetails {
    return CommondtoPaginatedResponseTeamInvitationDetailsFromJSONTyped(json, false);
}

export function CommondtoPaginatedResponseTeamInvitationDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommondtoPaginatedResponseTeamInvitationDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(TeamInvitationDetailsFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function CommondtoPaginatedResponseTeamInvitationDetailsToJSON(json: any): CommondtoPaginatedResponseTeamInvitationDetails {
    return CommondtoPaginatedResponseTeamInvitationDetailsToJSONTyped(json, false);
}

export function CommondtoPaginatedResponseTeamInvitationDetailsToJSONTyped(value?: CommondtoPaginatedResponseTeamInvitationDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(TeamInvitationDetailsToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

