/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { AdminAPIKeyResponse } from './AdminAPIKeyResponse';
import {
    AdminAPIKeyResponseFromJSON,
    AdminAPIKeyResponseFromJSONTyped,
    AdminAPIKeyResponseToJSON,
    AdminAPIKeyResponseToJSONTyped,
} from './AdminAPIKeyResponse';

/**
 * 
 * @export
 * @interface CommondtoPaginatedResponseAdminAPIKeyResponse
 */
export interface CommondtoPaginatedResponseAdminAPIKeyResponse {
    /**
     * Data contains the paginated items
     * @type {Array<AdminAPIKeyResponse>}
     * @memberof CommondtoPaginatedResponseAdminAPIKeyResponse
     */
    data?: Array<AdminAPIKeyResponse>;
    /**
     * Meta contains pagination metadata
     * @type {PaginationMeta}
     * @memberof CommondtoPaginatedResponseAdminAPIKeyResponse
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the CommondtoPaginatedResponseAdminAPIKeyResponse interface.
 */
export function instanceOfCommondtoPaginatedResponseAdminAPIKeyResponse(value: object): value is CommondtoPaginatedResponseAdminAPIKeyResponse {
    return true;
}

export function CommondtoPaginatedResponseAdminAPIKeyResponseFromJSON(json: any): CommondtoPaginatedResponseAdminAPIKeyResponse {
    return CommondtoPaginatedResponseAdminAPIKeyResponseFromJSONTyped(json, false);
}

export function CommondtoPaginatedResponseAdminAPIKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommondtoPaginatedResponseAdminAPIKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(AdminAPIKeyResponseFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function CommondtoPaginatedResponseAdminAPIKeyResponseToJSON(json: any): CommondtoPaginatedResponseAdminAPIKeyResponse {
    return CommondtoPaginatedResponseAdminAPIKeyResponseToJSONTyped(json, false);
}

export function CommondtoPaginatedResponseAdminAPIKeyResponseToJSONTyped(value?: CommondtoPaginatedResponseAdminAPIKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(AdminAPIKeyResponseToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

