/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { APIKeyDetails } from './APIKeyDetails';
import {
    APIKeyDetailsFromJSON,
    APIKeyDetailsFromJSONTyped,
    APIKeyDetailsToJSON,
    APIKeyDetailsToJSONTyped,
} from './APIKeyDetails';

/**
 * 
 * @export
 * @interface CommondtoPaginatedResponseAPIKeyDetails
 */
export interface CommondtoPaginatedResponseAPIKeyDetails {
    /**
     * Data contains the paginated items
     * @type {Array<APIKeyDetails>}
     * @memberof CommondtoPaginatedResponseAPIKeyDetails
     */
    data?: Array<APIKeyDetails>;
    /**
     * Meta contains pagination metadata
     * @type {PaginationMeta}
     * @memberof CommondtoPaginatedResponseAPIKeyDetails
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the CommondtoPaginatedResponseAPIKeyDetails interface.
 */
export function instanceOfCommondtoPaginatedResponseAPIKeyDetails(value: object): value is CommondtoPaginatedResponseAPIKeyDetails {
    return true;
}

export function CommondtoPaginatedResponseAPIKeyDetailsFromJSON(json: any): CommondtoPaginatedResponseAPIKeyDetails {
    return CommondtoPaginatedResponseAPIKeyDetailsFromJSONTyped(json, false);
}

export function CommondtoPaginatedResponseAPIKeyDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommondtoPaginatedResponseAPIKeyDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(APIKeyDetailsFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function CommondtoPaginatedResponseAPIKeyDetailsToJSON(json: any): CommondtoPaginatedResponseAPIKeyDetails {
    return CommondtoPaginatedResponseAPIKeyDetailsToJSONTyped(json, false);
}

export function CommondtoPaginatedResponseAPIKeyDetailsToJSONTyped(value?: CommondtoPaginatedResponseAPIKeyDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(APIKeyDetailsToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

