/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDraftRequest
 */
export interface CreateDraftRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDraftRequest
     */
    appId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDraftRequest
     */
    dataPlaneId?: string;
}

/**
 * Check if a given object implements the CreateDraftRequest interface.
 */
export function instanceOfCreateDraftRequest(value: object): value is CreateDraftRequest {
    return true;
}

export function CreateDraftRequestFromJSON(json: any): CreateDraftRequest {
    return CreateDraftRequestFromJSONTyped(json, false);
}

export function CreateDraftRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDraftRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'dataPlaneId': json['data_plane_id'] == null ? undefined : json['data_plane_id'],
    };
}

export function CreateDraftRequestToJSON(json: any): CreateDraftRequest {
    return CreateDraftRequestToJSONTyped(json, false);
}

export function CreateDraftRequestToJSONTyped(value?: CreateDraftRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'data_plane_id': value['dataPlaneId'],
    };
}

