/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TeamRole } from './TeamRole';
import {
    TeamRoleFromJSON,
    TeamRoleFromJSONTyped,
    TeamRoleToJSON,
    TeamRoleToJSONTyped,
} from './TeamRole';

/**
 * 
 * @export
 * @interface CreateInvitationRequest
 */
export interface CreateInvitationRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateInvitationRequest
     */
    email: string;
    /**
     * 
     * @type {TeamRole}
     * @memberof CreateInvitationRequest
     */
    role: TeamRole;
    /**
     * Set from path parameter, not required in body
     * @type {string}
     * @memberof CreateInvitationRequest
     */
    teamId?: string;
}



/**
 * Check if a given object implements the CreateInvitationRequest interface.
 */
export function instanceOfCreateInvitationRequest(value: object): value is CreateInvitationRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function CreateInvitationRequestFromJSON(json: any): CreateInvitationRequest {
    return CreateInvitationRequestFromJSONTyped(json, false);
}

export function CreateInvitationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInvitationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'role': TeamRoleFromJSON(json['role']),
        'teamId': json['team_id'] == null ? undefined : json['team_id'],
    };
}

export function CreateInvitationRequestToJSON(json: any): CreateInvitationRequest {
    return CreateInvitationRequestToJSONTyped(json, false);
}

export function CreateInvitationRequestToJSONTyped(value?: CreateInvitationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'role': TeamRoleToJSON(value['role']),
        'team_id': value['teamId'],
    };
}

