/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAPIKeyRequest
 */
export interface CreateAPIKeyRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAPIKeyRequest
     */
    appId: string;
    /**
     * RFC3339 format, nil = no expiry
     * @type {string}
     * @memberof CreateAPIKeyRequest
     */
    expiresAt?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAPIKeyRequest
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateAPIKeyRequest
     */
    scopes?: Array<string>;
}

/**
 * Check if a given object implements the CreateAPIKeyRequest interface.
 */
export function instanceOfCreateAPIKeyRequest(value: object): value is CreateAPIKeyRequest {
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateAPIKeyRequestFromJSON(json: any): CreateAPIKeyRequest {
    return CreateAPIKeyRequestFromJSONTyped(json, false);
}

export function CreateAPIKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAPIKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'name': json['name'],
        'scopes': json['scopes'] == null ? undefined : json['scopes'],
    };
}

export function CreateAPIKeyRequestToJSON(json: any): CreateAPIKeyRequest {
    return CreateAPIKeyRequestToJSONTyped(json, false);
}

export function CreateAPIKeyRequestToJSONTyped(value?: CreateAPIKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'expires_at': value['expiresAt'],
        'name': value['name'],
        'scopes': value['scopes'],
    };
}

