/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { APIKeyDetails } from './APIKeyDetails';
import {
    APIKeyDetailsFromJSON,
    APIKeyDetailsFromJSONTyped,
    APIKeyDetailsToJSON,
    APIKeyDetailsToJSONTyped,
} from './APIKeyDetails';

/**
 * 
 * @export
 * @interface CreateAPIKeyResponse
 */
export interface CreateAPIKeyResponse {
    /**
     * Full key value - only shown once!
     * @type {string}
     * @memberof CreateAPIKeyResponse
     */
    apiKey?: string;
    /**
     * 
     * @type {APIKeyDetails}
     * @memberof CreateAPIKeyResponse
     */
    details?: APIKeyDetails;
}

/**
 * Check if a given object implements the CreateAPIKeyResponse interface.
 */
export function instanceOfCreateAPIKeyResponse(value: object): value is CreateAPIKeyResponse {
    return true;
}

export function CreateAPIKeyResponseFromJSON(json: any): CreateAPIKeyResponse {
    return CreateAPIKeyResponseFromJSONTyped(json, false);
}

export function CreateAPIKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAPIKeyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'details': json['details'] == null ? undefined : APIKeyDetailsFromJSON(json['details']),
    };
}

export function CreateAPIKeyResponseToJSON(json: any): CreateAPIKeyResponse {
    return CreateAPIKeyResponseToJSONTyped(json, false);
}

export function CreateAPIKeyResponseToJSONTyped(value?: CreateAPIKeyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': value['apiKey'],
        'details': APIKeyDetailsToJSON(value['details']),
    };
}

