/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanDirectives } from './PlanDirectives';
import {
    PlanDirectivesFromJSON,
    PlanDirectivesFromJSONTyped,
    PlanDirectivesToJSON,
    PlanDirectivesToJSONTyped,
} from './PlanDirectives';
import type { PlanCreditCosts } from './PlanCreditCosts';
import {
    PlanCreditCostsFromJSON,
    PlanCreditCostsFromJSONTyped,
    PlanCreditCostsToJSON,
    PlanCreditCostsToJSONTyped,
} from './PlanCreditCosts';
import type { PlanRateLimits } from './PlanRateLimits';
import {
    PlanRateLimitsFromJSON,
    PlanRateLimitsFromJSONTyped,
    PlanRateLimitsToJSON,
    PlanRateLimitsToJSONTyped,
} from './PlanRateLimits';
import type { PlanFeatures } from './PlanFeatures';
import {
    PlanFeaturesFromJSON,
    PlanFeaturesFromJSONTyped,
    PlanFeaturesToJSON,
    PlanFeaturesToJSONTyped,
} from './PlanFeatures';
import type { PlanPricing } from './PlanPricing';
import {
    PlanPricingFromJSON,
    PlanPricingFromJSONTyped,
    PlanPricingToJSON,
    PlanPricingToJSONTyped,
} from './PlanPricing';
import type { PlanQuotas } from './PlanQuotas';
import {
    PlanQuotasFromJSON,
    PlanQuotasFromJSONTyped,
    PlanQuotasToJSON,
    PlanQuotasToJSONTyped,
} from './PlanQuotas';

/**
 * 
 * @export
 * @interface CreatePlanRequest
 */
export interface CreatePlanRequest {
    /**
     * 
     * @type {{ [key: string]: PlanPricing; }}
     * @memberof CreatePlanRequest
     */
    countryPricing?: { [key: string]: PlanPricing; };
    /**
     * 
     * @type {PlanCreditCosts}
     * @memberof CreatePlanRequest
     */
    creditCosts?: PlanCreditCosts;
    /**
     * 
     * @type {string}
     * @memberof CreatePlanRequest
     */
    description?: string;
    /**
     * 
     * @type {PlanDirectives}
     * @memberof CreatePlanRequest
     */
    directives?: PlanDirectives;
    /**
     * 
     * @type {PlanFeatures}
     * @memberof CreatePlanRequest
     */
    features?: PlanFeatures;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePlanRequest
     */
    isDefault?: boolean;
    /**
     * External plans are visible to customers; internal (default=false) are admin-only
     * @type {boolean}
     * @memberof CreatePlanRequest
     */
    isExternal?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreatePlanRequest
     */
    name: string;
    /**
     * 
     * @type {PlanPricing}
     * @memberof CreatePlanRequest
     */
    pricing?: PlanPricing;
    /**
     * 
     * @type {PlanQuotas}
     * @memberof CreatePlanRequest
     */
    quotas?: PlanQuotas;
    /**
     * 
     * @type {PlanRateLimits}
     * @memberof CreatePlanRequest
     */
    rateLimits?: PlanRateLimits;
    /**
     * 
     * @type {string}
     * @memberof CreatePlanRequest
     */
    slug: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePlanRequest
     */
    sortOrder?: number;
}

/**
 * Check if a given object implements the CreatePlanRequest interface.
 */
export function instanceOfCreatePlanRequest(value: object): value is CreatePlanRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    return true;
}

export function CreatePlanRequestFromJSON(json: any): CreatePlanRequest {
    return CreatePlanRequestFromJSONTyped(json, false);
}

export function CreatePlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'countryPricing': json['country_pricing'] == null ? undefined : (mapValues(json['country_pricing'], PlanPricingFromJSON)),
        'creditCosts': json['credit_costs'] == null ? undefined : PlanCreditCostsFromJSON(json['credit_costs']),
        'description': json['description'] == null ? undefined : json['description'],
        'directives': json['directives'] == null ? undefined : PlanDirectivesFromJSON(json['directives']),
        'features': json['features'] == null ? undefined : PlanFeaturesFromJSON(json['features']),
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'isExternal': json['is_external'] == null ? undefined : json['is_external'],
        'name': json['name'],
        'pricing': json['pricing'] == null ? undefined : PlanPricingFromJSON(json['pricing']),
        'quotas': json['quotas'] == null ? undefined : PlanQuotasFromJSON(json['quotas']),
        'rateLimits': json['rate_limits'] == null ? undefined : PlanRateLimitsFromJSON(json['rate_limits']),
        'slug': json['slug'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
    };
}

export function CreatePlanRequestToJSON(json: any): CreatePlanRequest {
    return CreatePlanRequestToJSONTyped(json, false);
}

export function CreatePlanRequestToJSONTyped(value?: CreatePlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country_pricing': value['countryPricing'] == null ? undefined : (mapValues(value['countryPricing'], PlanPricingToJSON)),
        'credit_costs': PlanCreditCostsToJSON(value['creditCosts']),
        'description': value['description'],
        'directives': PlanDirectivesToJSON(value['directives']),
        'features': PlanFeaturesToJSON(value['features']),
        'is_default': value['isDefault'],
        'is_external': value['isExternal'],
        'name': value['name'],
        'pricing': PlanPricingToJSON(value['pricing']),
        'quotas': PlanQuotasToJSON(value['quotas']),
        'rate_limits': PlanRateLimitsToJSON(value['rateLimits']),
        'slug': value['slug'],
        'sort_order': value['sortOrder'],
    };
}

