/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExtractionConfig } from './ExtractionConfig';
import {
    ExtractionConfigFromJSON,
    ExtractionConfigFromJSONTyped,
    ExtractionConfigToJSON,
    ExtractionConfigToJSONTyped,
} from './ExtractionConfig';
import type { SearchConfig } from './SearchConfig';
import {
    SearchConfigFromJSON,
    SearchConfigFromJSONTyped,
    SearchConfigToJSON,
    SearchConfigToJSONTyped,
} from './SearchConfig';
import type { DirectiveConfig } from './DirectiveConfig';
import {
    DirectiveConfigFromJSON,
    DirectiveConfigFromJSONTyped,
    DirectiveConfigToJSON,
    DirectiveConfigToJSONTyped,
} from './DirectiveConfig';

/**
 * 
 * @export
 * @interface CreateAppRequest
 */
export interface CreateAppRequest {
    /**
     * Description is the application description (optional, max 2000 chars)
     * @type {string}
     * @memberof CreateAppRequest
     */
    description?: string;
    /**
     * DirectiveConfig provides per-app customization of entity/relationship extraction (optional)
     * @type {DirectiveConfig}
     * @memberof CreateAppRequest
     */
    directiveConfig?: DirectiveConfig;
    /**
     * ExtractionConfig contains algorithm configuration for entity extraction (optional)
     * @type {ExtractionConfig}
     * @memberof CreateAppRequest
     */
    extractionConfig?: ExtractionConfig;
    /**
     * Name is the application name (required, 1-255 chars)
     * @type {string}
     * @memberof CreateAppRequest
     */
    name: string;
    /**
     * SearchConfig contains algorithm configuration for search operations (optional)
     * @type {SearchConfig}
     * @memberof CreateAppRequest
     */
    searchConfig?: SearchConfig;
}

/**
 * Check if a given object implements the CreateAppRequest interface.
 */
export function instanceOfCreateAppRequest(value: object): value is CreateAppRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateAppRequestFromJSON(json: any): CreateAppRequest {
    return CreateAppRequestFromJSONTyped(json, false);
}

export function CreateAppRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAppRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'directiveConfig': json['directive_config'] == null ? undefined : DirectiveConfigFromJSON(json['directive_config']),
        'extractionConfig': json['extraction_config'] == null ? undefined : ExtractionConfigFromJSON(json['extraction_config']),
        'name': json['name'],
        'searchConfig': json['search_config'] == null ? undefined : SearchConfigFromJSON(json['search_config']),
    };
}

export function CreateAppRequestToJSON(json: any): CreateAppRequest {
    return CreateAppRequestToJSONTyped(json, false);
}

export function CreateAppRequestToJSONTyped(value?: CreateAppRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'directive_config': DirectiveConfigToJSON(value['directiveConfig']),
        'extraction_config': ExtractionConfigToJSON(value['extractionConfig']),
        'name': value['name'],
        'search_config': SearchConfigToJSON(value['searchConfig']),
    };
}

