/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreditBalanceEntry
 */
export interface CreditBalanceEntry {
    /**
     * e.g., "memory", "search", "storage"
     * @type {string}
     * @memberof CreditBalanceEntry
     */
    creditType?: string;
    /**
     * When these credits expire
     * @type {string}
     * @memberof CreditBalanceEntry
     */
    expiresAt?: string;
    /**
     * Total credits granted for this period
     * @type {number}
     * @memberof CreditBalanceEntry
     */
    granted?: number;
    /**
     * Period in YYYY-MM format
     * @type {string}
     * @memberof CreditBalanceEntry
     */
    period?: string;
    /**
     * Remaining credits (granted - used)
     * @type {number}
     * @memberof CreditBalanceEntry
     */
    remaining?: number;
    /**
     * Credits already consumed
     * @type {number}
     * @memberof CreditBalanceEntry
     */
    used?: number;
}

/**
 * Check if a given object implements the CreditBalanceEntry interface.
 */
export function instanceOfCreditBalanceEntry(value: object): value is CreditBalanceEntry {
    return true;
}

export function CreditBalanceEntryFromJSON(json: any): CreditBalanceEntry {
    return CreditBalanceEntryFromJSONTyped(json, false);
}

export function CreditBalanceEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditBalanceEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'creditType': json['credit_type'] == null ? undefined : json['credit_type'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'granted': json['granted'] == null ? undefined : json['granted'],
        'period': json['period'] == null ? undefined : json['period'],
        'remaining': json['remaining'] == null ? undefined : json['remaining'],
        'used': json['used'] == null ? undefined : json['used'],
    };
}

export function CreditBalanceEntryToJSON(json: any): CreditBalanceEntry {
    return CreditBalanceEntryToJSONTyped(json, false);
}

export function CreditBalanceEntryToJSONTyped(value?: CreditBalanceEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credit_type': value['creditType'],
        'expires_at': value['expiresAt'],
        'granted': value['granted'],
        'period': value['period'],
        'remaining': value['remaining'],
        'used': value['used'],
    };
}

