/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntitlementUsageSummary } from './EntitlementUsageSummary';
import {
    EntitlementUsageSummaryFromJSON,
    EntitlementUsageSummaryFromJSONTyped,
    EntitlementUsageSummaryToJSON,
    EntitlementUsageSummaryToJSONTyped,
} from './EntitlementUsageSummary';

/**
 * 
 * @export
 * @interface CurrentUsageResponse
 */
export interface CurrentUsageResponse {
    /**
     * 
     * @type {Array<EntitlementUsageSummary>}
     * @memberof CurrentUsageResponse
     */
    usages?: Array<EntitlementUsageSummary>;
}

/**
 * Check if a given object implements the CurrentUsageResponse interface.
 */
export function instanceOfCurrentUsageResponse(value: object): value is CurrentUsageResponse {
    return true;
}

export function CurrentUsageResponseFromJSON(json: any): CurrentUsageResponse {
    return CurrentUsageResponseFromJSONTyped(json, false);
}

export function CurrentUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUsageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'usages': json['usages'] == null ? undefined : ((json['usages'] as Array<any>).map(EntitlementUsageSummaryFromJSON)),
    };
}

export function CurrentUsageResponseToJSON(json: any): CurrentUsageResponse {
    return CurrentUsageResponseToJSONTyped(json, false);
}

export function CurrentUsageResponseToJSONTyped(value?: CurrentUsageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usages': value['usages'] == null ? undefined : ((value['usages'] as Array<any>).map(EntitlementUsageSummaryToJSON)),
    };
}

