/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanSummary } from './PlanSummary';
import {
    PlanSummaryFromJSON,
    PlanSummaryFromJSONTyped,
    PlanSummaryToJSON,
    PlanSummaryToJSONTyped,
} from './PlanSummary';

/**
 * 
 * @export
 * @interface DashboardSummaryResponse
 */
export interface DashboardSummaryResponse {
    /**
     * 
     * @type {number}
     * @memberof DashboardSummaryResponse
     */
    appsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof DashboardSummaryResponse
     */
    keysCount?: number;
    /**
     * 
     * @type {number}
     * @memberof DashboardSummaryResponse
     */
    memoriesCount?: number;
    /**
     * 
     * @type {PlanSummary}
     * @memberof DashboardSummaryResponse
     */
    plan?: PlanSummary;
    /**
     * 
     * @type {Array<object>}
     * @memberof DashboardSummaryResponse
     */
    recentActivity?: Array<object>;
    /**
     * 
     * @type {number}
     * @memberof DashboardSummaryResponse
     */
    searchesCount?: number;
}

/**
 * Check if a given object implements the DashboardSummaryResponse interface.
 */
export function instanceOfDashboardSummaryResponse(value: object): value is DashboardSummaryResponse {
    return true;
}

export function DashboardSummaryResponseFromJSON(json: any): DashboardSummaryResponse {
    return DashboardSummaryResponseFromJSONTyped(json, false);
}

export function DashboardSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appsCount': json['apps_count'] == null ? undefined : json['apps_count'],
        'keysCount': json['keys_count'] == null ? undefined : json['keys_count'],
        'memoriesCount': json['memories_count'] == null ? undefined : json['memories_count'],
        'plan': json['plan'] == null ? undefined : PlanSummaryFromJSON(json['plan']),
        'recentActivity': json['recent_activity'] == null ? undefined : json['recent_activity'],
        'searchesCount': json['searches_count'] == null ? undefined : json['searches_count'],
    };
}

export function DashboardSummaryResponseToJSON(json: any): DashboardSummaryResponse {
    return DashboardSummaryResponseToJSONTyped(json, false);
}

export function DashboardSummaryResponseToJSONTyped(value?: DashboardSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apps_count': value['appsCount'],
        'keys_count': value['keysCount'],
        'memories_count': value['memoriesCount'],
        'plan': PlanSummaryToJSON(value['plan']),
        'recent_activity': value['recentActivity'],
        'searches_count': value['searchesCount'],
    };
}

