/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DashboardDataPlaneResponse
 */
export interface DashboardDataPlaneResponse {
    /**
     * Cloud is the data plane's cloud provider: "aws", "azure", or "docker".
     * @type {string}
     * @memberof DashboardDataPlaneResponse
     */
    cloud?: string;
    /**
     * ID is the data plane's nanoID (e.g. "dp_xxxxxxxxxxxxxxxx"). This is the value a
     * client submits as data_plane_id when creating a new app.
     * @type {string}
     * @memberof DashboardDataPlaneResponse
     */
    id?: string;
    /**
     * Region is the data plane's region (e.g. "us-east-1").
     * @type {string}
     * @memberof DashboardDataPlaneResponse
     */
    region?: string;
}

/**
 * Check if a given object implements the DashboardDataPlaneResponse interface.
 */
export function instanceOfDashboardDataPlaneResponse(value: object): value is DashboardDataPlaneResponse {
    return true;
}

export function DashboardDataPlaneResponseFromJSON(json: any): DashboardDataPlaneResponse {
    return DashboardDataPlaneResponseFromJSONTyped(json, false);
}

export function DashboardDataPlaneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardDataPlaneResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cloud': json['cloud'] == null ? undefined : json['cloud'],
        'id': json['id'] == null ? undefined : json['id'],
        'region': json['region'] == null ? undefined : json['region'],
    };
}

export function DashboardDataPlaneResponseToJSON(json: any): DashboardDataPlaneResponse {
    return DashboardDataPlaneResponseToJSONTyped(json, false);
}

export function DashboardDataPlaneResponseToJSONTyped(value?: DashboardDataPlaneResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cloud': value['cloud'],
        'id': value['id'],
        'region': value['region'],
    };
}

