/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateAppRequest } from './CreateAppRequest';
import {
    CreateAppRequestFromJSON,
    CreateAppRequestFromJSONTyped,
    CreateAppRequestToJSON,
    CreateAppRequestToJSONTyped,
} from './CreateAppRequest';

/**
 * 
 * @export
 * @interface DataPlaneCreateAppRequest
 */
export interface DataPlaneCreateAppRequest {
    /**
     * 
     * @type {string}
     * @memberof DataPlaneCreateAppRequest
     */
    dataPlaneId: string;
    /**
     * 
     * @type {CreateAppRequest}
     * @memberof DataPlaneCreateAppRequest
     */
    request?: CreateAppRequest;
}

/**
 * Check if a given object implements the DataPlaneCreateAppRequest interface.
 */
export function instanceOfDataPlaneCreateAppRequest(value: object): value is DataPlaneCreateAppRequest {
    if (!('dataPlaneId' in value) || value['dataPlaneId'] === undefined) return false;
    return true;
}

export function DataPlaneCreateAppRequestFromJSON(json: any): DataPlaneCreateAppRequest {
    return DataPlaneCreateAppRequestFromJSONTyped(json, false);
}

export function DataPlaneCreateAppRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataPlaneCreateAppRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'dataPlaneId': json['data_plane_id'],
        'request': json['request'] == null ? undefined : CreateAppRequestFromJSON(json['request']),
    };
}

export function DataPlaneCreateAppRequestToJSON(json: any): DataPlaneCreateAppRequest {
    return DataPlaneCreateAppRequestToJSONTyped(json, false);
}

export function DataPlaneCreateAppRequestToJSONTyped(value?: DataPlaneCreateAppRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_plane_id': value['dataPlaneId'],
        'request': CreateAppRequestToJSON(value['request']),
    };
}

