/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DebugChatMessage
 */
export interface DebugChatMessage {
    /**
     * 
     * @type {string}
     * @memberof DebugChatMessage
     */
    content: string;
    /**
     * 
     * @type {DebugChatMessageRoleEnum}
     * @memberof DebugChatMessage
     */
    role: DebugChatMessageRoleEnum;
}


/**
 * @export
 */
export const DebugChatMessageRoleEnum = {
    System: 'system',
    User: 'user',
    Assistant: 'assistant'
} as const;
export type DebugChatMessageRoleEnum = typeof DebugChatMessageRoleEnum[keyof typeof DebugChatMessageRoleEnum];


/**
 * Check if a given object implements the DebugChatMessage interface.
 */
export function instanceOfDebugChatMessage(value: object): value is DebugChatMessage {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function DebugChatMessageFromJSON(json: any): DebugChatMessage {
    return DebugChatMessageFromJSONTyped(json, false);
}

export function DebugChatMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebugChatMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'role': json['role'],
    };
}

export function DebugChatMessageToJSON(json: any): DebugChatMessage {
    return DebugChatMessageToJSONTyped(json, false);
}

export function DebugChatMessageToJSONTyped(value?: DebugChatMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'role': value['role'],
    };
}

