/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DebugModelInfo
 */
export interface DebugModelInfo {
    /**
     * 
     * @type {string}
     * @memberof DebugModelInfo
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof DebugModelInfo
     */
    modifiedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DebugModelInfo
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof DebugModelInfo
     */
    size?: number;
}

/**
 * Check if a given object implements the DebugModelInfo interface.
 */
export function instanceOfDebugModelInfo(value: object): value is DebugModelInfo {
    return true;
}

export function DebugModelInfoFromJSON(json: any): DebugModelInfo {
    return DebugModelInfoFromJSONTyped(json, false);
}

export function DebugModelInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebugModelInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'model': json['model'] == null ? undefined : json['model'],
        'modifiedAt': json['modified_at'] == null ? undefined : json['modified_at'],
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function DebugModelInfoToJSON(json: any): DebugModelInfo {
    return DebugModelInfoToJSONTyped(json, false);
}

export function DebugModelInfoToJSONTyped(value?: DebugModelInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model': value['model'],
        'modified_at': value['modifiedAt'],
        'name': value['name'],
        'size': value['size'],
    };
}

