/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DebugChatMessage } from './DebugChatMessage';
import {
    DebugChatMessageFromJSON,
    DebugChatMessageFromJSONTyped,
    DebugChatMessageToJSON,
    DebugChatMessageToJSONTyped,
} from './DebugChatMessage';

/**
 * Chat response payload
 * @export
 * @interface DebugChatResponse
 */
export interface DebugChatResponse {
    /**
     * Done indicates if the response is complete
     * @type {boolean}
     * @memberof DebugChatResponse
     */
    done?: boolean;
    /**
     * EvalCount is the number of tokens generated
     * @type {number}
     * @memberof DebugChatResponse
     */
    evalCount?: number;
    /**
     * Message is the assistant's response
     * @type {DebugChatMessage}
     * @memberof DebugChatResponse
     */
    message?: DebugChatMessage;
    /**
     * Model used for generation
     * @type {string}
     * @memberof DebugChatResponse
     */
    model?: string;
    /**
     * PromptEvalCount is the number of tokens in the prompt
     * @type {number}
     * @memberof DebugChatResponse
     */
    promptEvalCount?: number;
    /**
     * TotalDuration in nanoseconds
     * @type {number}
     * @memberof DebugChatResponse
     */
    totalDuration?: number;
}

/**
 * Check if a given object implements the DebugChatResponse interface.
 */
export function instanceOfDebugChatResponse(value: object): value is DebugChatResponse {
    return true;
}

export function DebugChatResponseFromJSON(json: any): DebugChatResponse {
    return DebugChatResponseFromJSONTyped(json, false);
}

export function DebugChatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DebugChatResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'done': json['done'] == null ? undefined : json['done'],
        'evalCount': json['eval_count'] == null ? undefined : json['eval_count'],
        'message': json['message'] == null ? undefined : DebugChatMessageFromJSON(json['message']),
        'model': json['model'] == null ? undefined : json['model'],
        'promptEvalCount': json['prompt_eval_count'] == null ? undefined : json['prompt_eval_count'],
        'totalDuration': json['total_duration'] == null ? undefined : json['total_duration'],
    };
}

export function DebugChatResponseToJSON(json: any): DebugChatResponse {
    return DebugChatResponseToJSONTyped(json, false);
}

export function DebugChatResponseToJSONTyped(value?: DebugChatResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'done': value['done'],
        'eval_count': value['evalCount'],
        'message': DebugChatMessageToJSON(value['message']),
        'model': value['model'],
        'prompt_eval_count': value['promptEvalCount'],
        'total_duration': value['totalDuration'],
    };
}

