/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagSchemaDef } from './TagSchemaDef';
import {
    TagSchemaDefFromJSON,
    TagSchemaDefFromJSONTyped,
    TagSchemaDefToJSON,
    TagSchemaDefToJSONTyped,
} from './TagSchemaDef';

/**
 * 
 * @export
 * @interface DirectivesResponse
 */
export interface DirectivesResponse {
    /**
     * AffirmativeDirective specifies what to explicitly include in extraction.
     * @type {string}
     * @memberof DirectivesResponse
     */
    affirmativeDirective?: string;
    /**
     * ExtractionDirective provides domain-specific guidance for the LLM.
     * @type {string}
     * @memberof DirectivesResponse
     */
    extractionDirective?: string;
    /**
     * TagSchema provides domain-specific tag keys that extend the base tag schema.
     * Used for categorizing extracted facts into domain-specific dimensions.
     * @type {Array<TagSchemaDef>}
     * @memberof DirectivesResponse
     */
    tagSchema?: Array<TagSchemaDef>;
}

/**
 * Check if a given object implements the DirectivesResponse interface.
 */
export function instanceOfDirectivesResponse(value: object): value is DirectivesResponse {
    return true;
}

export function DirectivesResponseFromJSON(json: any): DirectivesResponse {
    return DirectivesResponseFromJSONTyped(json, false);
}

export function DirectivesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectivesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'affirmativeDirective': json['affirmative_directive'] == null ? undefined : json['affirmative_directive'],
        'extractionDirective': json['extraction_directive'] == null ? undefined : json['extraction_directive'],
        'tagSchema': json['tag_schema'] == null ? undefined : ((json['tag_schema'] as Array<any>).map(TagSchemaDefFromJSON)),
    };
}

export function DirectivesResponseToJSON(json: any): DirectivesResponse {
    return DirectivesResponseToJSONTyped(json, false);
}

export function DirectivesResponseToJSONTyped(value?: DirectivesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'affirmative_directive': value['affirmativeDirective'],
        'extraction_directive': value['extractionDirective'],
        'tag_schema': value['tagSchema'] == null ? undefined : ((value['tagSchema'] as Array<any>).map(TagSchemaDefToJSON)),
    };
}

