/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelationshipType } from './RelationshipType';
import {
    RelationshipTypeFromJSON,
    RelationshipTypeFromJSONTyped,
    RelationshipTypeToJSON,
    RelationshipTypeToJSONTyped,
} from './RelationshipType';

/**
 * 
 * @export
 * @interface DomainSchemaResponse
 */
export interface DomainSchemaResponse {
    /**
     * ClassificationSchema provides custom entity types as a map.
     * Keys are type names, values are descriptions.
     * @type {{ [key: string]: string; }}
     * @memberof DomainSchemaResponse
     */
    classificationSchema?: { [key: string]: string; };
    /**
     * RelationshipSchema provides custom relationship types.
     * @type {Array<RelationshipType>}
     * @memberof DomainSchemaResponse
     */
    relationshipSchema?: Array<RelationshipType>;
}

/**
 * Check if a given object implements the DomainSchemaResponse interface.
 */
export function instanceOfDomainSchemaResponse(value: object): value is DomainSchemaResponse {
    return true;
}

export function DomainSchemaResponseFromJSON(json: any): DomainSchemaResponse {
    return DomainSchemaResponseFromJSONTyped(json, false);
}

export function DomainSchemaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainSchemaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'classificationSchema': json['classification_schema'] == null ? undefined : json['classification_schema'],
        'relationshipSchema': json['relationship_schema'] == null ? undefined : ((json['relationship_schema'] as Array<any>).map(RelationshipTypeFromJSON)),
    };
}

export function DomainSchemaResponseToJSON(json: any): DomainSchemaResponse {
    return DomainSchemaResponseToJSONTyped(json, false);
}

export function DomainSchemaResponseToJSONTyped(value?: DomainSchemaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'classification_schema': value['classificationSchema'],
        'relationship_schema': value['relationshipSchema'] == null ? undefined : ((value['relationshipSchema'] as Array<any>).map(RelationshipTypeToJSON)),
    };
}

