/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateAppRequest } from './UpdateAppRequest';
import {
    UpdateAppRequestFromJSON,
    UpdateAppRequestFromJSONTyped,
    UpdateAppRequestToJSON,
    UpdateAppRequestToJSONTyped,
} from './UpdateAppRequest';

/**
 * 
 * @export
 * @interface DraftResponse
 */
export interface DraftResponse {
    /**
     * 
     * @type {string}
     * @memberof DraftResponse
     */
    appId?: string;
    /**
     * 
     * @type {UpdateAppRequest}
     * @memberof DraftResponse
     */
    config?: UpdateAppRequest;
    /**
     * 
     * @type {string}
     * @memberof DraftResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftResponse
     */
    dataPlaneId?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftResponse
     */
    id?: string;
    /**
     * IsNewApp is true when this draft creates a brand-new app, false when it edits an existing
     * one. The wizard uses it to keep create-mode behavior (copy, defaults) after the create route
     * is replaced with the id-addressable draft URL.
     * @type {boolean}
     * @memberof DraftResponse
     */
    isNewApp?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DraftResponse
     */
    organizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftResponse
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftResponse
     */
    updatedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof DraftResponse
     */
    updatedByName?: string;
    /**
     * 
     * @type {number}
     * @memberof DraftResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the DraftResponse interface.
 */
export function instanceOfDraftResponse(value: object): value is DraftResponse {
    return true;
}

export function DraftResponseFromJSON(json: any): DraftResponse {
    return DraftResponseFromJSONTyped(json, false);
}

export function DraftResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DraftResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'config': json['config'] == null ? undefined : UpdateAppRequestFromJSON(json['config']),
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'dataPlaneId': json['data_plane_id'] == null ? undefined : json['data_plane_id'],
        'id': json['id'] == null ? undefined : json['id'],
        'isNewApp': json['is_new_app'] == null ? undefined : json['is_new_app'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'updatedByName': json['updated_by_name'] == null ? undefined : json['updated_by_name'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function DraftResponseToJSON(json: any): DraftResponse {
    return DraftResponseToJSONTyped(json, false);
}

export function DraftResponseToJSONTyped(value?: DraftResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'config': UpdateAppRequestToJSON(value['config']),
        'created_at': value['createdAt'],
        'data_plane_id': value['dataPlaneId'],
        'id': value['id'],
        'is_new_app': value['isNewApp'],
        'organization_id': value['organizationId'],
        'updated_at': value['updatedAt'],
        'updated_by': value['updatedBy'],
        'updated_by_name': value['updatedByName'],
        'version': value['version'],
    };
}

