/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnforcementConfig
 */
export interface EnforcementConfig {
    /**
     * 
     * @type {boolean}
     * @memberof EnforcementConfig
     */
    checkQuota?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EnforcementConfig
     */
    checkRateLimit?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EnforcementConfig
     */
    trackUsage?: boolean;
}

/**
 * Check if a given object implements the EnforcementConfig interface.
 */
export function instanceOfEnforcementConfig(value: object): value is EnforcementConfig {
    return true;
}

export function EnforcementConfigFromJSON(json: any): EnforcementConfig {
    return EnforcementConfigFromJSONTyped(json, false);
}

export function EnforcementConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnforcementConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'checkQuota': json['check_quota'] == null ? undefined : json['check_quota'],
        'checkRateLimit': json['check_rate_limit'] == null ? undefined : json['check_rate_limit'],
        'trackUsage': json['track_usage'] == null ? undefined : json['track_usage'],
    };
}

export function EnforcementConfigToJSON(json: any): EnforcementConfig {
    return EnforcementConfigToJSONTyped(json, false);
}

export function EnforcementConfigToJSONTyped(value?: EnforcementConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'check_quota': value['checkQuota'],
        'check_rate_limit': value['checkRateLimit'],
        'track_usage': value['trackUsage'],
    };
}

