/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityDef
 */
export interface EntityDef {
    /**
     * Description explains what this entity type represents. Max 200 to match the config-gen
     * producer (configgendto.EntityType.Description, max=200), whose output is copied verbatim
     * into this type by convertAndValidateDomainSchema.
     * @type {string}
     * @memberof EntityDef
     */
    description?: string;
    /**
     * Type is the entity type name (e.g., "patient", "medication")
     * @type {string}
     * @memberof EntityDef
     */
    type: string;
}

/**
 * Check if a given object implements the EntityDef interface.
 */
export function instanceOfEntityDef(value: object): value is EntityDef {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function EntityDefFromJSON(json: any): EntityDef {
    return EntityDefFromJSONTyped(json, false);
}

export function EntityDefFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityDef {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'],
    };
}

export function EntityDefToJSON(json: any): EntityDef {
    return EntityDefToJSONTyped(json, false);
}

export function EntityDefToJSONTyped(value?: EntityDef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'type': value['type'],
    };
}

