/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Extracted entity output
 * @export
 * @interface EntityOutputDTO
 */
export interface EntityOutputDTO {
    /**
     * 
     * @type {boolean}
     * @memberof EntityOutputDTO
     */
    created?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EntityOutputDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityOutputDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityOutputDTO
     */
    type?: string;
}

/**
 * Check if a given object implements the EntityOutputDTO interface.
 */
export function instanceOfEntityOutputDTO(value: object): value is EntityOutputDTO {
    return true;
}

export function EntityOutputDTOFromJSON(json: any): EntityOutputDTO {
    return EntityOutputDTOFromJSONTyped(json, false);
}

export function EntityOutputDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityOutputDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : json['created'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function EntityOutputDTOToJSON(json: any): EntityOutputDTO {
    return EntityOutputDTOToJSONTyped(json, false);
}

export function EntityOutputDTOToJSONTyped(value?: EntityOutputDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'id': value['id'],
        'name': value['name'],
        'type': value['type'],
    };
}

