/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityExtractionConfig
 */
export interface EntityExtractionConfig {
    /**
     * ContextWindow is the number of previous messages to include in context.
     * Only used when EnableContext is true. 0 means use default (10 messages).
     * @type {number}
     * @memberof EntityExtractionConfig
     */
    contextWindow?: number;
    /**
     * EnableContext enables context-aware extraction using conversation history.
     * When true, extraction considers previous messages in the conversation for
     * better entity resolution and relationship detection.
     * @type {boolean}
     * @memberof EntityExtractionConfig
     */
    enableContext?: boolean;
    /**
     * EntityTypes filters which entity types to extract (empty = all types).
     * Valid types: person, organization, concept, location, event, product, other
     * @type {Array<string>}
     * @memberof EntityExtractionConfig
     */
    entityTypes?: Array<string>;
    /**
     * FallbackMessages is the minimum number of messages to include even if
     * the conversation is shorter than ContextWindow. Prevents empty context.
     * @type {number}
     * @memberof EntityExtractionConfig
     */
    fallbackMessages?: number;
    /**
     * MinConfidence is not read by any extraction path (dead field, roadmap TD36). Kept in the API.
     * @type {number}
     * @memberof EntityExtractionConfig
     */
    minConfidence?: number;
    /**
     * Model has no effect today: the model comes from the system AI connection. Reserved for model
     * selection by criteria, allowed only for apps that use their own AI (custom AI / BYOK).
     * @type {string}
     * @memberof EntityExtractionConfig
     */
    model?: string;
    /**
     * ReflectionPasses is the number of reflection calls after the first extraction call (0-5). 0 = one extraction, no reflection.
     * @type {number}
     * @memberof EntityExtractionConfig
     */
    reflectionPasses?: number;
}

/**
 * Check if a given object implements the EntityExtractionConfig interface.
 */
export function instanceOfEntityExtractionConfig(value: object): value is EntityExtractionConfig {
    return true;
}

export function EntityExtractionConfigFromJSON(json: any): EntityExtractionConfig {
    return EntityExtractionConfigFromJSONTyped(json, false);
}

export function EntityExtractionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityExtractionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'contextWindow': json['context_window'] == null ? undefined : json['context_window'],
        'enableContext': json['enable_context'] == null ? undefined : json['enable_context'],
        'entityTypes': json['entity_types'] == null ? undefined : json['entity_types'],
        'fallbackMessages': json['fallback_messages'] == null ? undefined : json['fallback_messages'],
        'minConfidence': json['min_confidence'] == null ? undefined : json['min_confidence'],
        'model': json['model'] == null ? undefined : json['model'],
        'reflectionPasses': json['reflection_passes'] == null ? undefined : json['reflection_passes'],
    };
}

export function EntityExtractionConfigToJSON(json: any): EntityExtractionConfig {
    return EntityExtractionConfigToJSONTyped(json, false);
}

export function EntityExtractionConfigToJSONTyped(value?: EntityExtractionConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context_window': value['contextWindow'],
        'enable_context': value['enableContext'],
        'entity_types': value['entityTypes'],
        'fallback_messages': value['fallbackMessages'],
        'min_confidence': value['minConfidence'],
        'model': value['model'],
        'reflection_passes': value['reflectionPasses'],
    };
}

