/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityResponse
 */
export interface EntityResponse {
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    actorId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EntityResponse
     */
    aliases?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    appId?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof EntityResponse
     */
    attributes?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    customType?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EntityResponse
     */
    sourceMemoryIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the EntityResponse interface.
 */
export function instanceOfEntityResponse(value: object): value is EntityResponse {
    return true;
}

export function EntityResponseFromJSON(json: any): EntityResponse {
    return EntityResponseFromJSONTyped(json, false);
}

export function EntityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'actorId': json['actor_id'] == null ? undefined : json['actor_id'],
        'aliases': json['aliases'] == null ? undefined : json['aliases'],
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'attributes': json['attributes'] == null ? undefined : json['attributes'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'customType': json['custom_type'] == null ? undefined : json['custom_type'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'sourceMemoryIds': json['source_memory_ids'] == null ? undefined : json['source_memory_ids'],
        'type': json['type'] == null ? undefined : json['type'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function EntityResponseToJSON(json: any): EntityResponse {
    return EntityResponseToJSONTyped(json, false);
}

export function EntityResponseToJSONTyped(value?: EntityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actor_id': value['actorId'],
        'aliases': value['aliases'],
        'app_id': value['appId'],
        'attributes': value['attributes'],
        'created_at': value['createdAt'],
        'custom_type': value['customType'],
        'id': value['id'],
        'name': value['name'],
        'source_memory_ids': value['sourceMemoryIds'],
        'type': value['type'],
        'updated_at': value['updatedAt'],
    };
}

