/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResultExplanation } from './ResultExplanation';
import {
    ResultExplanationFromJSON,
    ResultExplanationFromJSONTyped,
    ResultExplanationToJSON,
    ResultExplanationToJSONTyped,
} from './ResultExplanation';

/**
 * 
 * @export
 * @interface ExplainedResult
 */
export interface ExplainedResult {
    /**
     * Content is the memory text content
     * @type {string}
     * @memberof ExplainedResult
     */
    content?: string;
    /**
     * Explanation contains the detailed scoring breakdown
     * @type {ResultExplanation}
     * @memberof ExplainedResult
     */
    explanation?: ResultExplanation;
    /**
     * FinalScore is the combined relevance score after all processing
     * @type {number}
     * @memberof ExplainedResult
     */
    finalScore?: number;
    /**
     * MemoryID is the unique identifier of the matched memory
     * @type {string}
     * @memberof ExplainedResult
     */
    memoryId?: string;
}

/**
 * Check if a given object implements the ExplainedResult interface.
 */
export function instanceOfExplainedResult(value: object): value is ExplainedResult {
    return true;
}

export function ExplainedResultFromJSON(json: any): ExplainedResult {
    return ExplainedResultFromJSONTyped(json, false);
}

export function ExplainedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExplainedResult {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'explanation': json['explanation'] == null ? undefined : ResultExplanationFromJSON(json['explanation']),
        'finalScore': json['final_score'] == null ? undefined : json['final_score'],
        'memoryId': json['memory_id'] == null ? undefined : json['memory_id'],
    };
}

export function ExplainedResultToJSON(json: any): ExplainedResult {
    return ExplainedResultToJSONTyped(json, false);
}

export function ExplainedResultToJSONTyped(value?: ExplainedResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'explanation': ResultExplanationToJSON(value['explanation']),
        'final_score': value['finalScore'],
        'memory_id': value['memoryId'],
    };
}

