/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonaExtractionConfig } from './PersonaExtractionConfig';
import {
    PersonaExtractionConfigFromJSON,
    PersonaExtractionConfigFromJSONTyped,
    PersonaExtractionConfigToJSON,
    PersonaExtractionConfigToJSONTyped,
} from './PersonaExtractionConfig';
import type { FactExtractionConfig } from './FactExtractionConfig';
import {
    FactExtractionConfigFromJSON,
    FactExtractionConfigFromJSONTyped,
    FactExtractionConfigToJSON,
    FactExtractionConfigToJSONTyped,
} from './FactExtractionConfig';
import type { EntityExtractionConfig } from './EntityExtractionConfig';
import {
    EntityExtractionConfigFromJSON,
    EntityExtractionConfigFromJSONTyped,
    EntityExtractionConfigToJSON,
    EntityExtractionConfigToJSONTyped,
} from './EntityExtractionConfig';

/**
 * 
 * @export
 * @interface ExtractionConfig
 */
export interface ExtractionConfig {
    /**
     * Entity holds configuration for entity extraction (optional).
     * @type {EntityExtractionConfig}
     * @memberof ExtractionConfig
     */
    entity?: EntityExtractionConfig;
    /**
     * Fact holds configuration for fact extraction (optional).
     * @type {FactExtractionConfig}
     * @memberof ExtractionConfig
     */
    fact?: FactExtractionConfig;
    /**
     * Persona holds configuration for persona extraction (optional).
     * CRITICAL: When absent from JSON, this stays nil (disabled by default).
     * Unlike Entity/Fact, no defaults are applied when the key is missing.
     * @type {PersonaExtractionConfig}
     * @memberof ExtractionConfig
     */
    persona?: PersonaExtractionConfig;
}

/**
 * Check if a given object implements the ExtractionConfig interface.
 */
export function instanceOfExtractionConfig(value: object): value is ExtractionConfig {
    return true;
}

export function ExtractionConfigFromJSON(json: any): ExtractionConfig {
    return ExtractionConfigFromJSONTyped(json, false);
}

export function ExtractionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'entity': json['entity'] == null ? undefined : EntityExtractionConfigFromJSON(json['entity']),
        'fact': json['fact'] == null ? undefined : FactExtractionConfigFromJSON(json['fact']),
        'persona': json['persona'] == null ? undefined : PersonaExtractionConfigFromJSON(json['persona']),
    };
}

export function ExtractionConfigToJSON(json: any): ExtractionConfig {
    return ExtractionConfigToJSONTyped(json, false);
}

export function ExtractionConfigToJSONTyped(value?: ExtractionConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity': EntityExtractionConfigToJSON(value['entity']),
        'fact': FactExtractionConfigToJSON(value['fact']),
        'persona': PersonaExtractionConfigToJSON(value['persona']),
    };
}

