/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForceReconcileError
 */
export interface ForceReconcileError {
    /**
     * 
     * @type {string}
     * @memberof ForceReconcileError
     */
    entityId?: string;
    /**
     * 
     * @type {string}
     * @memberof ForceReconcileError
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof ForceReconcileError
     */
    phase?: string;
}

/**
 * Check if a given object implements the ForceReconcileError interface.
 */
export function instanceOfForceReconcileError(value: object): value is ForceReconcileError {
    return true;
}

export function ForceReconcileErrorFromJSON(json: any): ForceReconcileError {
    return ForceReconcileErrorFromJSONTyped(json, false);
}

export function ForceReconcileErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForceReconcileError {
    if (json == null) {
        return json;
    }
    return {
        
        'entityId': json['entity_id'] == null ? undefined : json['entity_id'],
        'error': json['error'] == null ? undefined : json['error'],
        'phase': json['phase'] == null ? undefined : json['phase'],
    };
}

export function ForceReconcileErrorToJSON(json: any): ForceReconcileError {
    return ForceReconcileErrorToJSONTyped(json, false);
}

export function ForceReconcileErrorToJSONTyped(value?: ForceReconcileError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity_id': value['entityId'],
        'error': value['error'],
        'phase': value['phase'],
    };
}

