/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PhaseResult } from './PhaseResult';
import {
    PhaseResultFromJSON,
    PhaseResultFromJSONTyped,
    PhaseResultToJSON,
    PhaseResultToJSONTyped,
} from './PhaseResult';
import type { ForceReconcileError } from './ForceReconcileError';
import {
    ForceReconcileErrorFromJSON,
    ForceReconcileErrorFromJSONTyped,
    ForceReconcileErrorToJSON,
    ForceReconcileErrorToJSONTyped,
} from './ForceReconcileError';

/**
 * 
 * @export
 * @interface ForceReconcileResponse
 */
export interface ForceReconcileResponse {
    /**
     * 
     * @type {PhaseResult}
     * @memberof ForceReconcileResponse
     */
    apiKeys?: PhaseResult;
    /**
     * 
     * @type {Array<ForceReconcileError>}
     * @memberof ForceReconcileResponse
     */
    errors?: Array<ForceReconcileError>;
    /**
     * 
     * @type {PhaseResult}
     * @memberof ForceReconcileResponse
     */
    orgApps?: PhaseResult;
    /**
     * 
     * @type {PhaseResult}
     * @memberof ForceReconcileResponse
     */
    orgProjections?: PhaseResult;
    /**
     * 
     * @type {PhaseResult}
     * @memberof ForceReconcileResponse
     */
    planContexts?: PhaseResult;
}

/**
 * Check if a given object implements the ForceReconcileResponse interface.
 */
export function instanceOfForceReconcileResponse(value: object): value is ForceReconcileResponse {
    return true;
}

export function ForceReconcileResponseFromJSON(json: any): ForceReconcileResponse {
    return ForceReconcileResponseFromJSONTyped(json, false);
}

export function ForceReconcileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForceReconcileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKeys': json['api_keys'] == null ? undefined : PhaseResultFromJSON(json['api_keys']),
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ForceReconcileErrorFromJSON)),
        'orgApps': json['org_apps'] == null ? undefined : PhaseResultFromJSON(json['org_apps']),
        'orgProjections': json['org_projections'] == null ? undefined : PhaseResultFromJSON(json['org_projections']),
        'planContexts': json['plan_contexts'] == null ? undefined : PhaseResultFromJSON(json['plan_contexts']),
    };
}

export function ForceReconcileResponseToJSON(json: any): ForceReconcileResponse {
    return ForceReconcileResponseToJSONTyped(json, false);
}

export function ForceReconcileResponseToJSONTyped(value?: ForceReconcileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_keys': PhaseResultToJSON(value['apiKeys']),
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ForceReconcileErrorToJSON)),
        'org_apps': PhaseResultToJSON(value['orgApps']),
        'org_projections': PhaseResultToJSON(value['orgProjections']),
        'plan_contexts': PhaseResultToJSON(value['planContexts']),
    };
}

