/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateDirectivesRequest
 */
export interface GenerateDirectivesRequest {
    /**
     * AppDescription is a detailed description of the application domain.
     * Should include context about what entities and relationships are important.
     * Example: "A medical records system for tracking patients, diagnoses, medications, and treatments."
     * @type {string}
     * @memberof GenerateDirectivesRequest
     */
    appDescription: string;
}

/**
 * Check if a given object implements the GenerateDirectivesRequest interface.
 */
export function instanceOfGenerateDirectivesRequest(value: object): value is GenerateDirectivesRequest {
    if (!('appDescription' in value) || value['appDescription'] === undefined) return false;
    return true;
}

export function GenerateDirectivesRequestFromJSON(json: any): GenerateDirectivesRequest {
    return GenerateDirectivesRequestFromJSONTyped(json, false);
}

export function GenerateDirectivesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateDirectivesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appDescription': json['app_description'],
    };
}

export function GenerateDirectivesRequestToJSON(json: any): GenerateDirectivesRequest {
    return GenerateDirectivesRequestToJSONTyped(json, false);
}

export function GenerateDirectivesRequestToJSONTyped(value?: GenerateDirectivesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_description': value['appDescription'],
    };
}

