/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateDomainSchemaRequest
 */
export interface GenerateDomainSchemaRequest {
    /**
     * AppDescription is a detailed description of the application domain.
     * Should include context about what entities and relationships are important.
     * Example: "A medical records system for tracking patients, diagnoses, medications, and treatments."
     * @type {string}
     * @memberof GenerateDomainSchemaRequest
     */
    appDescription: string;
}

/**
 * Check if a given object implements the GenerateDomainSchemaRequest interface.
 */
export function instanceOfGenerateDomainSchemaRequest(value: object): value is GenerateDomainSchemaRequest {
    if (!('appDescription' in value) || value['appDescription'] === undefined) return false;
    return true;
}

export function GenerateDomainSchemaRequestFromJSON(json: any): GenerateDomainSchemaRequest {
    return GenerateDomainSchemaRequestFromJSONTyped(json, false);
}

export function GenerateDomainSchemaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateDomainSchemaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appDescription': json['app_description'],
    };
}

export function GenerateDomainSchemaRequestToJSON(json: any): GenerateDomainSchemaRequest {
    return GenerateDomainSchemaRequestToJSONTyped(json, false);
}

export function GenerateDomainSchemaRequestToJSONTyped(value?: GenerateDomainSchemaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_description': value['appDescription'],
    };
}

