/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SourceWeightsConfig } from './SourceWeightsConfig';
import {
    SourceWeightsConfigFromJSON,
    SourceWeightsConfigFromJSONTyped,
    SourceWeightsConfigToJSON,
    SourceWeightsConfigToJSONTyped,
} from './SourceWeightsConfig';

/**
 * 
 * @export
 * @interface GetSourceWeightsResponse
 */
export interface GetSourceWeightsResponse {
    /**
     * AppID is the application identifier (UUID)
     * @type {string}
     * @memberof GetSourceWeightsResponse
     */
    appId?: string;
    /**
     * SourceWeights contains the current source weight configuration
     * @type {SourceWeightsConfig}
     * @memberof GetSourceWeightsResponse
     */
    sourceWeights?: SourceWeightsConfig;
    /**
     * UpdatedAt is the timestamp of last configuration update (ISO 8601)
     * @type {string}
     * @memberof GetSourceWeightsResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the GetSourceWeightsResponse interface.
 */
export function instanceOfGetSourceWeightsResponse(value: object): value is GetSourceWeightsResponse {
    return true;
}

export function GetSourceWeightsResponseFromJSON(json: any): GetSourceWeightsResponse {
    return GetSourceWeightsResponseFromJSONTyped(json, false);
}

export function GetSourceWeightsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSourceWeightsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'sourceWeights': json['source_weights'] == null ? undefined : SourceWeightsConfigFromJSON(json['source_weights']),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function GetSourceWeightsResponseToJSON(json: any): GetSourceWeightsResponse {
    return GetSourceWeightsResponseToJSONTyped(json, false);
}

export function GetSourceWeightsResponseToJSONTyped(value?: GetSourceWeightsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'source_weights': SourceWeightsConfigToJSON(value['sourceWeights']),
        'updated_at': value['updatedAt'],
    };
}

