/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GraphSearchOptions
 */
export interface GraphSearchOptions {
    /**
     * Direction controls traversal direction: "incoming", "outgoing", or "both"
     * @type {GraphSearchOptionsDirectionEnum}
     * @memberof GraphSearchOptions
     */
    direction?: GraphSearchOptionsDirectionEnum;
    /**
     * EntityBoostFactor boosts scores for memories with entity matches.
     * 0.3 means 30% boost for each matching entity.
     * @type {number}
     * @memberof GraphSearchOptions
     */
    entityBoostFactor?: number;
    /**
     * HopDecayFactor reduces importance of distant connections.
     * Score is multiplied by this factor for each hop.
     * @type {number}
     * @memberof GraphSearchOptions
     */
    hopDecayFactor?: number;
    /**
     * MaxHops is the graph traversal depth (default: 2)
     * @type {number}
     * @memberof GraphSearchOptions
     */
    maxHops?: number;
    /**
     * RelationshipTypes filters traversal to specific relationship types.
     * Empty means all types are traversed.
     * @type {Array<string>}
     * @memberof GraphSearchOptions
     */
    relationshipTypes?: Array<string>;
}


/**
 * @export
 */
export const GraphSearchOptionsDirectionEnum = {
    Incoming: 'incoming',
    Outgoing: 'outgoing',
    Both: 'both'
} as const;
export type GraphSearchOptionsDirectionEnum = typeof GraphSearchOptionsDirectionEnum[keyof typeof GraphSearchOptionsDirectionEnum];


/**
 * Check if a given object implements the GraphSearchOptions interface.
 */
export function instanceOfGraphSearchOptions(value: object): value is GraphSearchOptions {
    return true;
}

export function GraphSearchOptionsFromJSON(json: any): GraphSearchOptions {
    return GraphSearchOptionsFromJSONTyped(json, false);
}

export function GraphSearchOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphSearchOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'direction': json['direction'] == null ? undefined : json['direction'],
        'entityBoostFactor': json['entity_boost_factor'] == null ? undefined : json['entity_boost_factor'],
        'hopDecayFactor': json['hop_decay_factor'] == null ? undefined : json['hop_decay_factor'],
        'maxHops': json['max_hops'] == null ? undefined : json['max_hops'],
        'relationshipTypes': json['relationship_types'] == null ? undefined : json['relationship_types'],
    };
}

export function GraphSearchOptionsToJSON(json: any): GraphSearchOptions {
    return GraphSearchOptionsToJSONTyped(json, false);
}

export function GraphSearchOptionsToJSONTyped(value?: GraphSearchOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'direction': value['direction'],
        'entity_boost_factor': value['entityBoostFactor'],
        'hop_decay_factor': value['hopDecayFactor'],
        'max_hops': value['maxHops'],
        'relationship_types': value['relationshipTypes'],
    };
}

