/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Graph backfill from memories request payload
 * @export
 * @interface GraphBackfillMemoriesRequest
 */
export interface GraphBackfillMemoriesRequest {
    /**
     * 
     * @type {string}
     * @memberof GraphBackfillMemoriesRequest
     */
    appId: string;
    /**
     * MaxPasses overrides entity extraction passes. 0 = use app config. -1 = disable. 1-5 = run N passes.
     * @type {number}
     * @memberof GraphBackfillMemoriesRequest
     */
    maxPasses?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GraphBackfillMemoriesRequest
     */
    memoryIds: Array<string>;
}

/**
 * Check if a given object implements the GraphBackfillMemoriesRequest interface.
 */
export function instanceOfGraphBackfillMemoriesRequest(value: object): value is GraphBackfillMemoriesRequest {
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('memoryIds' in value) || value['memoryIds'] === undefined) return false;
    return true;
}

export function GraphBackfillMemoriesRequestFromJSON(json: any): GraphBackfillMemoriesRequest {
    return GraphBackfillMemoriesRequestFromJSONTyped(json, false);
}

export function GraphBackfillMemoriesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphBackfillMemoriesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'],
        'maxPasses': json['max_passes'] == null ? undefined : json['max_passes'],
        'memoryIds': json['memory_ids'],
    };
}

export function GraphBackfillMemoriesRequestToJSON(json: any): GraphBackfillMemoriesRequest {
    return GraphBackfillMemoriesRequestToJSONTyped(json, false);
}

export function GraphBackfillMemoriesRequestToJSONTyped(value?: GraphBackfillMemoriesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'max_passes': value['maxPasses'],
        'memory_ids': value['memoryIds'],
    };
}

