/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemoryExtractionResultDTO } from './MemoryExtractionResultDTO';
import {
    MemoryExtractionResultDTOFromJSON,
    MemoryExtractionResultDTOFromJSONTyped,
    MemoryExtractionResultDTOToJSON,
    MemoryExtractionResultDTOToJSONTyped,
} from './MemoryExtractionResultDTO';
import type { BatchItemErrorDTO } from './BatchItemErrorDTO';
import {
    BatchItemErrorDTOFromJSON,
    BatchItemErrorDTOFromJSONTyped,
    BatchItemErrorDTOToJSON,
    BatchItemErrorDTOToJSONTyped,
} from './BatchItemErrorDTO';
import type { GraphBackfillMemorySummaryDTO } from './GraphBackfillMemorySummaryDTO';
import {
    GraphBackfillMemorySummaryDTOFromJSON,
    GraphBackfillMemorySummaryDTOFromJSONTyped,
    GraphBackfillMemorySummaryDTOToJSON,
    GraphBackfillMemorySummaryDTOToJSONTyped,
} from './GraphBackfillMemorySummaryDTO';

/**
 * Graph backfill from memories response
 * @export
 * @interface GraphBackfillMemoriesResponse
 */
export interface GraphBackfillMemoriesResponse {
    /**
     * 
     * @type {Array<BatchItemErrorDTO>}
     * @memberof GraphBackfillMemoriesResponse
     */
    errors?: Array<BatchItemErrorDTO>;
    /**
     * 
     * @type {Array<MemoryExtractionResultDTO>}
     * @memberof GraphBackfillMemoriesResponse
     */
    results?: Array<MemoryExtractionResultDTO>;
    /**
     * 
     * @type {GraphBackfillMemorySummaryDTO}
     * @memberof GraphBackfillMemoriesResponse
     */
    summary?: GraphBackfillMemorySummaryDTO;
}

/**
 * Check if a given object implements the GraphBackfillMemoriesResponse interface.
 */
export function instanceOfGraphBackfillMemoriesResponse(value: object): value is GraphBackfillMemoriesResponse {
    return true;
}

export function GraphBackfillMemoriesResponseFromJSON(json: any): GraphBackfillMemoriesResponse {
    return GraphBackfillMemoriesResponseFromJSONTyped(json, false);
}

export function GraphBackfillMemoriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphBackfillMemoriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(BatchItemErrorDTOFromJSON)),
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(MemoryExtractionResultDTOFromJSON)),
        'summary': json['summary'] == null ? undefined : GraphBackfillMemorySummaryDTOFromJSON(json['summary']),
    };
}

export function GraphBackfillMemoriesResponseToJSON(json: any): GraphBackfillMemoriesResponse {
    return GraphBackfillMemoriesResponseToJSONTyped(json, false);
}

export function GraphBackfillMemoriesResponseToJSONTyped(value?: GraphBackfillMemoriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(BatchItemErrorDTOToJSON)),
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(MemoryExtractionResultDTOToJSON)),
        'summary': GraphBackfillMemorySummaryDTOToJSON(value['summary']),
    };
}

