/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HourlyUsageEntry } from './HourlyUsageEntry';
import {
    HourlyUsageEntryFromJSON,
    HourlyUsageEntryFromJSONTyped,
    HourlyUsageEntryToJSON,
    HourlyUsageEntryToJSONTyped,
} from './HourlyUsageEntry';

/**
 * 
 * @export
 * @interface HourlyUsageResponse
 */
export interface HourlyUsageResponse {
    /**
     * 
     * @type {Array<HourlyUsageEntry>}
     * @memberof HourlyUsageResponse
     */
    entries?: Array<HourlyUsageEntry>;
}

/**
 * Check if a given object implements the HourlyUsageResponse interface.
 */
export function instanceOfHourlyUsageResponse(value: object): value is HourlyUsageResponse {
    return true;
}

export function HourlyUsageResponseFromJSON(json: any): HourlyUsageResponse {
    return HourlyUsageResponseFromJSONTyped(json, false);
}

export function HourlyUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HourlyUsageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': json['entries'] == null ? undefined : ((json['entries'] as Array<any>).map(HourlyUsageEntryFromJSON)),
    };
}

export function HourlyUsageResponseToJSON(json: any): HourlyUsageResponse {
    return HourlyUsageResponseToJSONTyped(json, false);
}

export function HourlyUsageResponseToJSONTyped(value?: HourlyUsageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entries': value['entries'] == null ? undefined : ((value['entries'] as Array<any>).map(HourlyUsageEntryToJSON)),
    };
}

