/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnforcementConfig } from './EnforcementConfig';
import {
    EnforcementConfigFromJSON,
    EnforcementConfigFromJSONTyped,
    EnforcementConfigToJSON,
    EnforcementConfigToJSONTyped,
} from './EnforcementConfig';
import type { CreateMemoryRequest } from './CreateMemoryRequest';
import {
    CreateMemoryRequestFromJSON,
    CreateMemoryRequestFromJSONTyped,
    CreateMemoryRequestToJSON,
    CreateMemoryRequestToJSONTyped,
} from './CreateMemoryRequest';

/**
 * 
 * @export
 * @interface InternalCreateMemoryRequest
 */
export interface InternalCreateMemoryRequest {
    /**
     * 
     * @type {EnforcementConfig}
     * @memberof InternalCreateMemoryRequest
     */
    enforcement?: EnforcementConfig;
    /**
     * 
     * @type {CreateMemoryRequest}
     * @memberof InternalCreateMemoryRequest
     */
    request?: CreateMemoryRequest;
}

/**
 * Check if a given object implements the InternalCreateMemoryRequest interface.
 */
export function instanceOfInternalCreateMemoryRequest(value: object): value is InternalCreateMemoryRequest {
    return true;
}

export function InternalCreateMemoryRequestFromJSON(json: any): InternalCreateMemoryRequest {
    return InternalCreateMemoryRequestFromJSONTyped(json, false);
}

export function InternalCreateMemoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalCreateMemoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enforcement': json['enforcement'] == null ? undefined : EnforcementConfigFromJSON(json['enforcement']),
        'request': json['request'] == null ? undefined : CreateMemoryRequestFromJSON(json['request']),
    };
}

export function InternalCreateMemoryRequestToJSON(json: any): InternalCreateMemoryRequest {
    return InternalCreateMemoryRequestToJSONTyped(json, false);
}

export function InternalCreateMemoryRequestToJSONTyped(value?: InternalCreateMemoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enforcement': EnforcementConfigToJSON(value['enforcement']),
        'request': CreateMemoryRequestToJSON(value['request']),
    };
}

