/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppConfigKind } from './AppConfigKind';
import {
    AppConfigKindFromJSON,
    AppConfigKindFromJSONTyped,
    AppConfigKindToJSON,
    AppConfigKindToJSONTyped,
} from './AppConfigKind';

/**
 * 
 * @export
 * @interface InvalidAppConfig
 */
export interface InvalidAppConfig {
    /**
     * Config is which stored config failed.
     * @type {AppConfigKind}
     * @memberof InvalidAppConfig
     */
    config?: AppConfigKind;
    /**
     * Error is the parse error text.
     * @type {string}
     * @memberof InvalidAppConfig
     */
    error?: string;
}



/**
 * Check if a given object implements the InvalidAppConfig interface.
 */
export function instanceOfInvalidAppConfig(value: object): value is InvalidAppConfig {
    return true;
}

export function InvalidAppConfigFromJSON(json: any): InvalidAppConfig {
    return InvalidAppConfigFromJSONTyped(json, false);
}

export function InvalidAppConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvalidAppConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : AppConfigKindFromJSON(json['config']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function InvalidAppConfigToJSON(json: any): InvalidAppConfig {
    return InvalidAppConfigToJSONTyped(json, false);
}

export function InvalidAppConfigToJSONTyped(value?: InvalidAppConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': AppConfigKindToJSON(value['config']),
        'error': value['error'],
    };
}

