/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LedgerEntry
 */
export interface LedgerEntry {
    /**
     * positive for grants, negative for revocations
     * @type {number}
     * @memberof LedgerEntry
     */
    amount?: number;
    /**
     * running balance after this transaction
     * @type {number}
     * @memberof LedgerEntry
     */
    balanceAfter?: number;
    /**
     * 
     * @type {string}
     * @memberof LedgerEntry
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof LedgerEntry
     */
    creditType?: string;
    /**
     * 
     * @type {string}
     * @memberof LedgerEntry
     */
    id?: string;
    /**
     * Period in YYYY-MM format
     * @type {string}
     * @memberof LedgerEntry
     */
    period?: string;
    /**
     * 
     * @type {string}
     * @memberof LedgerEntry
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof LedgerEntry
     */
    referenceId?: string;
    /**
     * e.g., "organization", "job", "payment"
     * @type {string}
     * @memberof LedgerEntry
     */
    referenceType?: string;
    /**
     * e.g., "plan_grant", "manual_revocation"
     * @type {string}
     * @memberof LedgerEntry
     */
    source?: string;
}

/**
 * Check if a given object implements the LedgerEntry interface.
 */
export function instanceOfLedgerEntry(value: object): value is LedgerEntry {
    return true;
}

export function LedgerEntryFromJSON(json: any): LedgerEntry {
    return LedgerEntryFromJSONTyped(json, false);
}

export function LedgerEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LedgerEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'balanceAfter': json['balance_after'] == null ? undefined : json['balance_after'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'creditType': json['credit_type'] == null ? undefined : json['credit_type'],
        'id': json['id'] == null ? undefined : json['id'],
        'period': json['period'] == null ? undefined : json['period'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'referenceId': json['reference_id'] == null ? undefined : json['reference_id'],
        'referenceType': json['reference_type'] == null ? undefined : json['reference_type'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function LedgerEntryToJSON(json: any): LedgerEntry {
    return LedgerEntryToJSONTyped(json, false);
}

export function LedgerEntryToJSONTyped(value?: LedgerEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'balance_after': value['balanceAfter'],
        'created_at': value['createdAt'],
        'credit_type': value['creditType'],
        'id': value['id'],
        'period': value['period'],
        'reason': value['reason'],
        'reference_id': value['referenceId'],
        'reference_type': value['referenceType'],
        'source': value['source'],
    };
}

