/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActorSummary } from './ActorSummary';
import {
    ActorSummaryFromJSON,
    ActorSummaryFromJSONTyped,
    ActorSummaryToJSON,
    ActorSummaryToJSONTyped,
} from './ActorSummary';

/**
 * 
 * @export
 * @interface ListActorsResponse
 */
export interface ListActorsResponse {
    /**
     * 
     * @type {Array<ActorSummary>}
     * @memberof ListActorsResponse
     */
    actors?: Array<ActorSummary>;
    /**
     * 
     * @type {number}
     * @memberof ListActorsResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the ListActorsResponse interface.
 */
export function instanceOfListActorsResponse(value: object): value is ListActorsResponse {
    return true;
}

export function ListActorsResponseFromJSON(json: any): ListActorsResponse {
    return ListActorsResponseFromJSONTyped(json, false);
}

export function ListActorsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListActorsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'actors': json['actors'] == null ? undefined : ((json['actors'] as Array<any>).map(ActorSummaryFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ListActorsResponseToJSON(json: any): ListActorsResponse {
    return ListActorsResponseToJSONTyped(json, false);
}

export function ListActorsResponseToJSONTyped(value?: ListActorsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'actors': value['actors'] == null ? undefined : ((value['actors'] as Array<any>).map(ActorSummaryToJSON)),
        'total': value['total'],
    };
}

