/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationCount
 */
export interface LocationCount {
    /**
     * Count is the number of users from this country.
     * @type {number}
     * @memberof LocationCount
     */
    count?: number;
    /**
     * CountryCode is the ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof LocationCount
     */
    countryCode?: string;
}

/**
 * Check if a given object implements the LocationCount interface.
 */
export function instanceOfLocationCount(value: object): value is LocationCount {
    return true;
}

export function LocationCountFromJSON(json: any): LocationCount {
    return LocationCountFromJSONTyped(json, false);
}

export function LocationCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationCount {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'countryCode': json['country_code'] == null ? undefined : json['country_code'],
    };
}

export function LocationCountToJSON(json: any): LocationCount {
    return LocationCountToJSONTyped(json, false);
}

export function LocationCountToJSONTyped(value?: LocationCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'country_code': value['countryCode'],
    };
}

