/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof LoginResponse
     */
    expiresIn?: number;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    organizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    refreshToken?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    tokenType?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    userId?: string;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
    return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
    return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'email': json['email'] == null ? undefined : json['email'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'name': json['name'] == null ? undefined : json['name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function LoginResponseToJSON(json: any): LoginResponse {
    return LoginResponseToJSONTyped(json, false);
}

export function LoginResponseToJSONTyped(value?: LoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'email': value['email'],
        'expires_in': value['expiresIn'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'refresh_token': value['refreshToken'],
        'token_type': value['tokenType'],
        'user_id': value['userId'],
    };
}

