/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MethodWeights
 */
export interface MethodWeights {
    /**
     * BM25 is the weight for keyword matching results (default: 0.2)
     * @type {number}
     * @memberof MethodWeights
     */
    bm25?: number;
    /**
     * Graph is the weight for graph-enhanced results (default: 0.3)
     * @type {number}
     * @memberof MethodWeights
     */
    graph?: number;
    /**
     * Vector is the weight for vector similarity search (default: 0.5)
     * @type {number}
     * @memberof MethodWeights
     */
    vector?: number;
}

/**
 * Check if a given object implements the MethodWeights interface.
 */
export function instanceOfMethodWeights(value: object): value is MethodWeights {
    return true;
}

export function MethodWeightsFromJSON(json: any): MethodWeights {
    return MethodWeightsFromJSONTyped(json, false);
}

export function MethodWeightsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MethodWeights {
    if (json == null) {
        return json;
    }
    return {
        
        'bm25': json['bm25'] == null ? undefined : json['bm25'],
        'graph': json['graph'] == null ? undefined : json['graph'],
        'vector': json['vector'] == null ? undefined : json['vector'],
    };
}

export function MethodWeightsToJSON(json: any): MethodWeights {
    return MethodWeightsToJSONTyped(json, false);
}

export function MethodWeightsToJSONTyped(value?: MethodWeights | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bm25': value['bm25'],
        'graph': value['graph'],
        'vector': value['vector'],
    };
}

