/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MRRSeriesPoint
 */
export interface MRRSeriesPoint {
    /**
     * 
     * @type {string}
     * @memberof MRRSeriesPoint
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof MRRSeriesPoint
     */
    mrrMinor?: number;
}

/**
 * Check if a given object implements the MRRSeriesPoint interface.
 */
export function instanceOfMRRSeriesPoint(value: object): value is MRRSeriesPoint {
    return true;
}

export function MRRSeriesPointFromJSON(json: any): MRRSeriesPoint {
    return MRRSeriesPointFromJSONTyped(json, false);
}

export function MRRSeriesPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): MRRSeriesPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'mrrMinor': json['mrr_minor'] == null ? undefined : json['mrr_minor'],
    };
}

export function MRRSeriesPointToJSON(json: any): MRRSeriesPoint {
    return MRRSeriesPointToJSONTyped(json, false);
}

export function MRRSeriesPointToJSONTyped(value?: MRRSeriesPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'mrr_minor': value['mrrMinor'],
    };
}

