/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrgSummary } from './OrgSummary';
import {
    OrgSummaryFromJSON,
    OrgSummaryFromJSONTyped,
    OrgSummaryToJSON,
    OrgSummaryToJSONTyped,
} from './OrgSummary';

/**
 * 
 * @export
 * @interface OAuthCallbackResponse
 */
export interface OAuthCallbackResponse {
    /**
     * 
     * @type {string}
     * @memberof OAuthCallbackResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthCallbackResponse
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof OAuthCallbackResponse
     */
    expiresIn?: number;
    /**
     * True if user was just created
     * @type {boolean}
     * @memberof OAuthCallbackResponse
     */
    isNewUser?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OAuthCallbackResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthCallbackResponse
     */
    organizationId?: string;
    /**
     * Multi-org challenge (present only when the user belongs to >1 org; tokens empty then).
     * @type {Array<OrgSummary>}
     * @memberof OAuthCallbackResponse
     */
    orgs?: Array<OrgSummary>;
    /**
     * 
     * @type {string}
     * @memberof OAuthCallbackResponse
     */
    refreshToken?: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthCallbackResponse
     */
    selectionToken?: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthCallbackResponse
     */
    tokenType?: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthCallbackResponse
     */
    userId?: string;
}

/**
 * Check if a given object implements the OAuthCallbackResponse interface.
 */
export function instanceOfOAuthCallbackResponse(value: object): value is OAuthCallbackResponse {
    return true;
}

export function OAuthCallbackResponseFromJSON(json: any): OAuthCallbackResponse {
    return OAuthCallbackResponseFromJSONTyped(json, false);
}

export function OAuthCallbackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthCallbackResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'email': json['email'] == null ? undefined : json['email'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'isNewUser': json['is_new_user'] == null ? undefined : json['is_new_user'],
        'name': json['name'] == null ? undefined : json['name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'orgs': json['orgs'] == null ? undefined : ((json['orgs'] as Array<any>).map(OrgSummaryFromJSON)),
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'selectionToken': json['selection_token'] == null ? undefined : json['selection_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function OAuthCallbackResponseToJSON(json: any): OAuthCallbackResponse {
    return OAuthCallbackResponseToJSONTyped(json, false);
}

export function OAuthCallbackResponseToJSONTyped(value?: OAuthCallbackResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'email': value['email'],
        'expires_in': value['expiresIn'],
        'is_new_user': value['isNewUser'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'orgs': value['orgs'] == null ? undefined : ((value['orgs'] as Array<any>).map(OrgSummaryToJSON)),
        'refresh_token': value['refreshToken'],
        'selection_token': value['selectionToken'],
        'token_type': value['tokenType'],
        'user_id': value['userId'],
    };
}

