/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RateLimitWindow } from './RateLimitWindow';
import {
    RateLimitWindowFromJSON,
    RateLimitWindowFromJSONTyped,
    RateLimitWindowToJSON,
    RateLimitWindowToJSONTyped,
} from './RateLimitWindow';

/**
 * 
 * @export
 * @interface OperationRateLimitStatus
 */
export interface OperationRateLimitStatus {
    /**
     * "memory_create", "search"
     * @type {string}
     * @memberof OperationRateLimitStatus
     */
    operation?: string;
    /**
     * 
     * @type {Array<RateLimitWindow>}
     * @memberof OperationRateLimitStatus
     */
    windows?: Array<RateLimitWindow>;
}

/**
 * Check if a given object implements the OperationRateLimitStatus interface.
 */
export function instanceOfOperationRateLimitStatus(value: object): value is OperationRateLimitStatus {
    return true;
}

export function OperationRateLimitStatusFromJSON(json: any): OperationRateLimitStatus {
    return OperationRateLimitStatusFromJSONTyped(json, false);
}

export function OperationRateLimitStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationRateLimitStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'] == null ? undefined : json['operation'],
        'windows': json['windows'] == null ? undefined : ((json['windows'] as Array<any>).map(RateLimitWindowFromJSON)),
    };
}

export function OperationRateLimitStatusToJSON(json: any): OperationRateLimitStatus {
    return OperationRateLimitStatusToJSONTyped(json, false);
}

export function OperationRateLimitStatusToJSONTyped(value?: OperationRateLimitStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operation': value['operation'],
        'windows': value['windows'] == null ? undefined : ((value['windows'] as Array<any>).map(RateLimitWindowToJSON)),
    };
}

