/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Counts of deleted records by type
 * @export
 * @interface OpsAppDeletionResult
 */
export interface OpsAppDeletionResult {
    /**
     * Conversations is the count of deleted conversation records
     * @type {number}
     * @memberof OpsAppDeletionResult
     */
    conversations?: number;
    /**
     * Entities is the count of deleted entity records from CockroachDB
     * @type {number}
     * @memberof OpsAppDeletionResult
     */
    entities?: number;
    /**
     * GraphEntities is the count of deleted entity nodes from graph store
     * @type {number}
     * @memberof OpsAppDeletionResult
     */
    graphEntities?: number;
    /**
     * GraphMemories is the count of deleted memory nodes from graph store
     * @type {number}
     * @memberof OpsAppDeletionResult
     */
    graphMemories?: number;
    /**
     * GraphMentions is the count of deleted mention edges from graph store
     * @type {number}
     * @memberof OpsAppDeletionResult
     */
    graphMentions?: number;
    /**
     * GraphRelationships is the count of deleted relationship edges from graph store
     * @type {number}
     * @memberof OpsAppDeletionResult
     */
    graphRelationships?: number;
    /**
     * Memories is the count of deleted memory records from CockroachDB
     * @type {number}
     * @memberof OpsAppDeletionResult
     */
    memories?: number;
    /**
     * Messages is the count of deleted message records
     * @type {number}
     * @memberof OpsAppDeletionResult
     */
    messages?: number;
    /**
     * RedisKeys is the count of deleted Redis cache keys (conversation context)
     * @type {number}
     * @memberof OpsAppDeletionResult
     */
    redisKeys?: number;
    /**
     * Relationships is the count of deleted relationship records from CockroachDB
     * @type {number}
     * @memberof OpsAppDeletionResult
     */
    relationships?: number;
}

/**
 * Check if a given object implements the OpsAppDeletionResult interface.
 */
export function instanceOfOpsAppDeletionResult(value: object): value is OpsAppDeletionResult {
    return true;
}

export function OpsAppDeletionResultFromJSON(json: any): OpsAppDeletionResult {
    return OpsAppDeletionResultFromJSONTyped(json, false);
}

export function OpsAppDeletionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpsAppDeletionResult {
    if (json == null) {
        return json;
    }
    return {
        
        'conversations': json['conversations'] == null ? undefined : json['conversations'],
        'entities': json['entities'] == null ? undefined : json['entities'],
        'graphEntities': json['graph_entities'] == null ? undefined : json['graph_entities'],
        'graphMemories': json['graph_memories'] == null ? undefined : json['graph_memories'],
        'graphMentions': json['graph_mentions'] == null ? undefined : json['graph_mentions'],
        'graphRelationships': json['graph_relationships'] == null ? undefined : json['graph_relationships'],
        'memories': json['memories'] == null ? undefined : json['memories'],
        'messages': json['messages'] == null ? undefined : json['messages'],
        'redisKeys': json['redis_keys'] == null ? undefined : json['redis_keys'],
        'relationships': json['relationships'] == null ? undefined : json['relationships'],
    };
}

export function OpsAppDeletionResultToJSON(json: any): OpsAppDeletionResult {
    return OpsAppDeletionResultToJSONTyped(json, false);
}

export function OpsAppDeletionResultToJSONTyped(value?: OpsAppDeletionResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversations': value['conversations'],
        'entities': value['entities'],
        'graph_entities': value['graphEntities'],
        'graph_memories': value['graphMemories'],
        'graph_mentions': value['graphMentions'],
        'graph_relationships': value['graphRelationships'],
        'memories': value['memories'],
        'messages': value['messages'],
        'redis_keys': value['redisKeys'],
        'relationships': value['relationships'],
    };
}

