/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpsAppDeletionResult } from './OpsAppDeletionResult';
import {
    OpsAppDeletionResultFromJSON,
    OpsAppDeletionResultFromJSONTyped,
    OpsAppDeletionResultToJSON,
    OpsAppDeletionResultToJSONTyped,
} from './OpsAppDeletionResult';

/**
 * App data deletion response
 * @export
 * @interface OpsAppDeleteResponse
 */
export interface OpsAppDeleteResponse {
    /**
     * AppID is the ID of the deleted application
     * @type {string}
     * @memberof OpsAppDeleteResponse
     */
    appId?: string;
    /**
     * Deleted contains counts of deleted records by type
     * @type {OpsAppDeletionResult}
     * @memberof OpsAppDeleteResponse
     */
    deleted?: OpsAppDeletionResult;
}

/**
 * Check if a given object implements the OpsAppDeleteResponse interface.
 */
export function instanceOfOpsAppDeleteResponse(value: object): value is OpsAppDeleteResponse {
    return true;
}

export function OpsAppDeleteResponseFromJSON(json: any): OpsAppDeleteResponse {
    return OpsAppDeleteResponseFromJSONTyped(json, false);
}

export function OpsAppDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpsAppDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'deleted': json['deleted'] == null ? undefined : OpsAppDeletionResultFromJSON(json['deleted']),
    };
}

export function OpsAppDeleteResponseToJSON(json: any): OpsAppDeleteResponse {
    return OpsAppDeleteResponseToJSONTyped(json, false);
}

export function OpsAppDeleteResponseToJSONTyped(value?: OpsAppDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'deleted': OpsAppDeletionResultToJSON(value['deleted']),
    };
}

