/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * GDPR deletion request
 * @export
 * @interface OpsGDPRDeleteRequest
 */
export interface OpsGDPRDeleteRequest {
    /**
     * AppID scopes deletion to a specific application (required to prevent cross-app deletion)
     * @type {string}
     * @memberof OpsGDPRDeleteRequest
     */
    appId: string;
    /**
     * ConversationID optionally limits deletion to a specific conversation
     * @type {string}
     * @memberof OpsGDPRDeleteRequest
     */
    conversationId?: string;
    /**
     * Level specifies the deletion scope: conversation, messages, or all
     * @type {OpsGDPRDeleteRequestLevelEnum}
     * @memberof OpsGDPRDeleteRequest
     */
    level: OpsGDPRDeleteRequestLevelEnum;
}


/**
 * @export
 */
export const OpsGDPRDeleteRequestLevelEnum = {
    Conversation: 'conversation',
    Messages: 'messages',
    All: 'all'
} as const;
export type OpsGDPRDeleteRequestLevelEnum = typeof OpsGDPRDeleteRequestLevelEnum[keyof typeof OpsGDPRDeleteRequestLevelEnum];


/**
 * Check if a given object implements the OpsGDPRDeleteRequest interface.
 */
export function instanceOfOpsGDPRDeleteRequest(value: object): value is OpsGDPRDeleteRequest {
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('level' in value) || value['level'] === undefined) return false;
    return true;
}

export function OpsGDPRDeleteRequestFromJSON(json: any): OpsGDPRDeleteRequest {
    return OpsGDPRDeleteRequestFromJSONTyped(json, false);
}

export function OpsGDPRDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpsGDPRDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'],
        'conversationId': json['conversation_id'] == null ? undefined : json['conversation_id'],
        'level': json['level'],
    };
}

export function OpsGDPRDeleteRequestToJSON(json: any): OpsGDPRDeleteRequest {
    return OpsGDPRDeleteRequestToJSONTyped(json, false);
}

export function OpsGDPRDeleteRequestToJSONTyped(value?: OpsGDPRDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'conversation_id': value['conversationId'],
        'level': value['level'],
    };
}

