/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpsViolationResponse } from './OpsViolationResponse';
import {
    OpsViolationResponseFromJSON,
    OpsViolationResponseFromJSONTyped,
    OpsViolationResponseToJSON,
    OpsViolationResponseToJSONTyped,
} from './OpsViolationResponse';

/**
 * Paginated violations response
 * @export
 * @interface OpsPaginatedViolationsResponse
 */
export interface OpsPaginatedViolationsResponse {
    /**
     * 
     * @type {number}
     * @memberof OpsPaginatedViolationsResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof OpsPaginatedViolationsResponse
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof OpsPaginatedViolationsResponse
     */
    total?: number;
    /**
     * 
     * @type {Array<OpsViolationResponse>}
     * @memberof OpsPaginatedViolationsResponse
     */
    violations?: Array<OpsViolationResponse>;
}

/**
 * Check if a given object implements the OpsPaginatedViolationsResponse interface.
 */
export function instanceOfOpsPaginatedViolationsResponse(value: object): value is OpsPaginatedViolationsResponse {
    return true;
}

export function OpsPaginatedViolationsResponseFromJSON(json: any): OpsPaginatedViolationsResponse {
    return OpsPaginatedViolationsResponseFromJSONTyped(json, false);
}

export function OpsPaginatedViolationsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpsPaginatedViolationsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'total': json['total'] == null ? undefined : json['total'],
        'violations': json['violations'] == null ? undefined : ((json['violations'] as Array<any>).map(OpsViolationResponseFromJSON)),
    };
}

export function OpsPaginatedViolationsResponseToJSON(json: any): OpsPaginatedViolationsResponse {
    return OpsPaginatedViolationsResponseToJSONTyped(json, false);
}

export function OpsPaginatedViolationsResponseToJSONTyped(value?: OpsPaginatedViolationsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
        'violations': value['violations'] == null ? undefined : ((value['violations'] as Array<any>).map(OpsViolationResponseToJSON)),
    };
}

