/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpsSanityReportResponse } from './OpsSanityReportResponse';
import {
    OpsSanityReportResponseFromJSON,
    OpsSanityReportResponseFromJSONTyped,
    OpsSanityReportResponseToJSON,
    OpsSanityReportResponseToJSONTyped,
} from './OpsSanityReportResponse';

/**
 * Reconciliation summary response
 * @export
 * @interface OpsReconciliationSummaryResponse
 */
export interface OpsReconciliationSummaryResponse {
    /**
     * 
     * @type {number}
     * @memberof OpsReconciliationSummaryResponse
     */
    failed?: number;
    /**
     * 
     * @type {boolean}
     * @memberof OpsReconciliationSummaryResponse
     */
    isRunning?: boolean;
    /**
     * 
     * @type {OpsSanityReportResponse}
     * @memberof OpsReconciliationSummaryResponse
     */
    lastCheck?: OpsSanityReportResponse;
    /**
     * 
     * @type {number}
     * @memberof OpsReconciliationSummaryResponse
     */
    pending?: number;
    /**
     * 
     * @type {number}
     * @memberof OpsReconciliationSummaryResponse
     */
    resolved?: number;
}

/**
 * Check if a given object implements the OpsReconciliationSummaryResponse interface.
 */
export function instanceOfOpsReconciliationSummaryResponse(value: object): value is OpsReconciliationSummaryResponse {
    return true;
}

export function OpsReconciliationSummaryResponseFromJSON(json: any): OpsReconciliationSummaryResponse {
    return OpsReconciliationSummaryResponseFromJSONTyped(json, false);
}

export function OpsReconciliationSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpsReconciliationSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'failed': json['failed'] == null ? undefined : json['failed'],
        'isRunning': json['is_running'] == null ? undefined : json['is_running'],
        'lastCheck': json['last_check'] == null ? undefined : OpsSanityReportResponseFromJSON(json['last_check']),
        'pending': json['pending'] == null ? undefined : json['pending'],
        'resolved': json['resolved'] == null ? undefined : json['resolved'],
    };
}

export function OpsReconciliationSummaryResponseToJSON(json: any): OpsReconciliationSummaryResponse {
    return OpsReconciliationSummaryResponseToJSONTyped(json, false);
}

export function OpsReconciliationSummaryResponseToJSONTyped(value?: OpsReconciliationSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'failed': value['failed'],
        'is_running': value['isRunning'],
        'last_check': OpsSanityReportResponseToJSON(value['lastCheck']),
        'pending': value['pending'],
        'resolved': value['resolved'],
    };
}

