/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Sanity violation response
 * @export
 * @interface OpsViolationResponse
 */
export interface OpsViolationResponse {
    /**
     * 
     * @type {string}
     * @memberof OpsViolationResponse
     */
    appId?: string;
    /**
     * 
     * @type {string}
     * @memberof OpsViolationResponse
     */
    entityId?: string;
    /**
     * 
     * @type {string}
     * @memberof OpsViolationResponse
     */
    firstSeenAt?: string;
    /**
     * 
     * @type {string}
     * @memberof OpsViolationResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OpsViolationResponse
     */
    lastSeenAt?: string;
    /**
     * 
     * @type {string}
     * @memberof OpsViolationResponse
     */
    memoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof OpsViolationResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof OpsViolationResponse
     */
    resolvedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof OpsViolationResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof OpsViolationResponse
     */
    type?: string;
}

/**
 * Check if a given object implements the OpsViolationResponse interface.
 */
export function instanceOfOpsViolationResponse(value: object): value is OpsViolationResponse {
    return true;
}

export function OpsViolationResponseFromJSON(json: any): OpsViolationResponse {
    return OpsViolationResponseFromJSONTyped(json, false);
}

export function OpsViolationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpsViolationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'entityId': json['entity_id'] == null ? undefined : json['entity_id'],
        'firstSeenAt': json['first_seen_at'] == null ? undefined : json['first_seen_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastSeenAt': json['last_seen_at'] == null ? undefined : json['last_seen_at'],
        'memoryId': json['memory_id'] == null ? undefined : json['memory_id'],
        'message': json['message'] == null ? undefined : json['message'],
        'resolvedAt': json['resolved_at'] == null ? undefined : json['resolved_at'],
        'status': json['status'] == null ? undefined : json['status'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function OpsViolationResponseToJSON(json: any): OpsViolationResponse {
    return OpsViolationResponseToJSONTyped(json, false);
}

export function OpsViolationResponseToJSONTyped(value?: OpsViolationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'entity_id': value['entityId'],
        'first_seen_at': value['firstSeenAt'],
        'id': value['id'],
        'last_seen_at': value['lastSeenAt'],
        'memory_id': value['memoryId'],
        'message': value['message'],
        'resolved_at': value['resolvedAt'],
        'status': value['status'],
        'type': value['type'],
    };
}

