/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationSummary
 */
export interface OrganizationSummary {
    /**
     * 
     * @type {string}
     * @memberof OrganizationSummary
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof OrganizationSummary
     */
    memberCount?: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizationSummary
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationSummary
     */
    plan?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationSummary
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationSummary
     */
    slug?: string;
}

/**
 * Check if a given object implements the OrganizationSummary interface.
 */
export function instanceOfOrganizationSummary(value: object): value is OrganizationSummary {
    return true;
}

export function OrganizationSummaryFromJSON(json: any): OrganizationSummary {
    return OrganizationSummaryFromJSONTyped(json, false);
}

export function OrganizationSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'memberCount': json['member_count'] == null ? undefined : json['member_count'],
        'name': json['name'] == null ? undefined : json['name'],
        'plan': json['plan'] == null ? undefined : json['plan'],
        'role': json['role'] == null ? undefined : json['role'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function OrganizationSummaryToJSON(json: any): OrganizationSummary {
    return OrganizationSummaryToJSONTyped(json, false);
}

export function OrganizationSummaryToJSONTyped(value?: OrganizationSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'member_count': value['memberCount'],
        'name': value['name'],
        'plan': value['plan'],
        'role': value['role'],
        'slug': value['slug'],
    };
}

