/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanInfo } from './PlanInfo';
import {
    PlanInfoFromJSON,
    PlanInfoFromJSONTyped,
    PlanInfoToJSON,
    PlanInfoToJSONTyped,
} from './PlanInfo';

/**
 * 
 * @export
 * @interface OrganizationDetails
 */
export interface OrganizationDetails {
    /**
     * 
     * @type {string}
     * @memberof OrganizationDetails
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDetails
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDetails
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDetails
     */
    logoUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof OrganizationDetails
     */
    memberQuota?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationDetails
     */
    memoryCredits?: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDetails
     */
    name?: string;
    /**
     * Plan details loaded from Plan table
     * @type {PlanInfo}
     * @memberof OrganizationDetails
     */
    plan?: PlanInfo;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDetails
     */
    planId?: string;
    /**
     * 
     * @type {number}
     * @memberof OrganizationDetails
     */
    searchCredits?: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDetails
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDetails
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDetails
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the OrganizationDetails interface.
 */
export function instanceOfOrganizationDetails(value: object): value is OrganizationDetails {
    return true;
}

export function OrganizationDetailsFromJSON(json: any): OrganizationDetails {
    return OrganizationDetailsFromJSONTyped(json, false);
}

export function OrganizationDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'color': json['color'] == null ? undefined : json['color'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'memberQuota': json['member_quota'] == null ? undefined : json['member_quota'],
        'memoryCredits': json['memory_credits'] == null ? undefined : json['memory_credits'],
        'name': json['name'] == null ? undefined : json['name'],
        'plan': json['plan'] == null ? undefined : PlanInfoFromJSON(json['plan']),
        'planId': json['plan_id'] == null ? undefined : json['plan_id'],
        'searchCredits': json['search_credits'] == null ? undefined : json['search_credits'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function OrganizationDetailsToJSON(json: any): OrganizationDetails {
    return OrganizationDetailsToJSONTyped(json, false);
}

export function OrganizationDetailsToJSONTyped(value?: OrganizationDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'color': value['color'],
        'created_at': value['createdAt'],
        'id': value['id'],
        'logo_url': value['logoUrl'],
        'member_quota': value['memberQuota'],
        'memory_credits': value['memoryCredits'],
        'name': value['name'],
        'plan': PlanInfoToJSON(value['plan']),
        'plan_id': value['planId'],
        'search_credits': value['searchCredits'],
        'slug': value['slug'],
        'status': value['status'],
        'updated_at': value['updatedAt'],
    };
}

