/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrgGrandfatherResponse
 */
export interface OrgGrandfatherResponse {
    /**
     * 
     * @type {string}
     * @memberof OrgGrandfatherResponse
     */
    grandfatherMode?: string;
    /**
     * 
     * @type {string}
     * @memberof OrgGrandfatherResponse
     */
    grandfatherReason?: string;
    /**
     * RFC3339, empty unless LOCK_UNTIL
     * @type {string}
     * @memberof OrgGrandfatherResponse
     */
    grandfatherUntil?: string;
    /**
     * 
     * @type {string}
     * @memberof OrgGrandfatherResponse
     */
    orgId?: string;
}

/**
 * Check if a given object implements the OrgGrandfatherResponse interface.
 */
export function instanceOfOrgGrandfatherResponse(value: object): value is OrgGrandfatherResponse {
    return true;
}

export function OrgGrandfatherResponseFromJSON(json: any): OrgGrandfatherResponse {
    return OrgGrandfatherResponseFromJSONTyped(json, false);
}

export function OrgGrandfatherResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgGrandfatherResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'grandfatherMode': json['grandfather_mode'] == null ? undefined : json['grandfather_mode'],
        'grandfatherReason': json['grandfather_reason'] == null ? undefined : json['grandfather_reason'],
        'grandfatherUntil': json['grandfather_until'] == null ? undefined : json['grandfather_until'],
        'orgId': json['org_id'] == null ? undefined : json['org_id'],
    };
}

export function OrgGrandfatherResponseToJSON(json: any): OrgGrandfatherResponse {
    return OrgGrandfatherResponseToJSONTyped(json, false);
}

export function OrgGrandfatherResponseToJSONTyped(value?: OrgGrandfatherResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grandfather_mode': value['grandfatherMode'],
        'grandfather_reason': value['grandfatherReason'],
        'grandfather_until': value['grandfatherUntil'],
        'org_id': value['orgId'],
    };
}

