/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * Page is the current page number (1-indexed)
     * @type {number}
     * @memberof PaginationMeta
     */
    page?: number;
    /**
     * PageSize is the number of items per page
     * @type {number}
     * @memberof PaginationMeta
     */
    pageSize?: number;
    /**
     * TotalItems is the total number of items across all pages.
     * int64 because SQL COUNT(*) returns int64.
     * @type {number}
     * @memberof PaginationMeta
     */
    totalItems?: number;
    /**
     * TotalPages is the total number of pages
     * @type {number}
     * @memberof PaginationMeta
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PaginationMeta interface.
 */
export function instanceOfPaginationMeta(value: object): value is PaginationMeta {
    return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
    return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'totalItems': json['total_items'] == null ? undefined : json['total_items'],
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
    };
}

export function PaginationMetaToJSON(json: any): PaginationMeta {
    return PaginationMetaToJSONTyped(json, false);
}

export function PaginationMetaToJSONTyped(value?: PaginationMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'page_size': value['pageSize'],
        'total_items': value['totalItems'],
        'total_pages': value['totalPages'],
    };
}

