/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentAttemptView
 */
export interface PaymentAttemptView {
    /**
     * 
     * @type {number}
     * @memberof PaymentAttemptView
     */
    amountMinor?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttemptView
     */
    attemptType?: string;
    /**
     * RFC3339
     * @type {string}
     * @memberof PaymentAttemptView
     */
    attemptedAt?: string;
    /**
     * RFC3339
     * @type {string}
     * @memberof PaymentAttemptView
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttemptView
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttemptView
     */
    failureReason?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttemptView
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttemptView
     */
    paymentOrderId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttemptView
     */
    paymentType?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttemptView
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttemptView
     */
    providerPaymentId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttemptView
     */
    providerResponseRaw?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttemptView
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentAttemptView
     */
    subscriptionId?: string;
}

/**
 * Check if a given object implements the PaymentAttemptView interface.
 */
export function instanceOfPaymentAttemptView(value: object): value is PaymentAttemptView {
    return true;
}

export function PaymentAttemptViewFromJSON(json: any): PaymentAttemptView {
    return PaymentAttemptViewFromJSONTyped(json, false);
}

export function PaymentAttemptViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentAttemptView {
    if (json == null) {
        return json;
    }
    return {
        
        'amountMinor': json['amount_minor'] == null ? undefined : json['amount_minor'],
        'attemptType': json['attempt_type'] == null ? undefined : json['attempt_type'],
        'attemptedAt': json['attempted_at'] == null ? undefined : json['attempted_at'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'failureReason': json['failure_reason'] == null ? undefined : json['failure_reason'],
        'id': json['id'] == null ? undefined : json['id'],
        'paymentOrderId': json['payment_order_id'] == null ? undefined : json['payment_order_id'],
        'paymentType': json['payment_type'] == null ? undefined : json['payment_type'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'providerPaymentId': json['provider_payment_id'] == null ? undefined : json['provider_payment_id'],
        'providerResponseRaw': json['provider_response_raw'] == null ? undefined : json['provider_response_raw'],
        'status': json['status'] == null ? undefined : json['status'],
        'subscriptionId': json['subscription_id'] == null ? undefined : json['subscription_id'],
    };
}

export function PaymentAttemptViewToJSON(json: any): PaymentAttemptView {
    return PaymentAttemptViewToJSONTyped(json, false);
}

export function PaymentAttemptViewToJSONTyped(value?: PaymentAttemptView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_minor': value['amountMinor'],
        'attempt_type': value['attemptType'],
        'attempted_at': value['attemptedAt'],
        'created_at': value['createdAt'],
        'currency': value['currency'],
        'failure_reason': value['failureReason'],
        'id': value['id'],
        'payment_order_id': value['paymentOrderId'],
        'payment_type': value['paymentType'],
        'provider': value['provider'],
        'provider_payment_id': value['providerPaymentId'],
        'provider_response_raw': value['providerResponseRaw'],
        'status': value['status'],
        'subscription_id': value['subscriptionId'],
    };
}

