/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentCustomer
 */
export interface PaymentCustomer {
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCustomer
     */
    phone: string;
}

/**
 * Check if a given object implements the PaymentCustomer interface.
 */
export function instanceOfPaymentCustomer(value: object): value is PaymentCustomer {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function PaymentCustomerFromJSON(json: any): PaymentCustomer {
    return PaymentCustomerFromJSONTyped(json, false);
}

export function PaymentCustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentCustomer {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'phone': json['phone'],
    };
}

export function PaymentCustomerToJSON(json: any): PaymentCustomer {
    return PaymentCustomerToJSONTyped(json, false);
}

export function PaymentCustomerToJSONTyped(value?: PaymentCustomer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'phone': value['phone'],
    };
}

