/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonaDomain } from './PersonaDomain';
import {
    PersonaDomainFromJSON,
    PersonaDomainFromJSONTyped,
    PersonaDomainToJSON,
    PersonaDomainToJSONTyped,
} from './PersonaDomain';

/**
 * 
 * @export
 * @interface PersonaSchemaResponse
 */
export interface PersonaSchemaResponse {
    /**
     * Domains is a list of persona domains with traits.
     * @type {Array<PersonaDomain>}
     * @memberof PersonaSchemaResponse
     */
    domains?: Array<PersonaDomain>;
}

/**
 * Check if a given object implements the PersonaSchemaResponse interface.
 */
export function instanceOfPersonaSchemaResponse(value: object): value is PersonaSchemaResponse {
    return true;
}

export function PersonaSchemaResponseFromJSON(json: any): PersonaSchemaResponse {
    return PersonaSchemaResponseFromJSONTyped(json, false);
}

export function PersonaSchemaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonaSchemaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'domains': json['domains'] == null ? undefined : ((json['domains'] as Array<any>).map(PersonaDomainFromJSON)),
    };
}

export function PersonaSchemaResponseToJSON(json: any): PersonaSchemaResponse {
    return PersonaSchemaResponseToJSONTyped(json, false);
}

export function PersonaSchemaResponseToJSONTyped(value?: PersonaSchemaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domains': value['domains'] == null ? undefined : ((value['domains'] as Array<any>).map(PersonaDomainToJSON)),
    };
}

