/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhaseResult
 */
export interface PhaseResult {
    /**
     * 
     * @type {number}
     * @memberof PhaseResult
     */
    failed?: number;
    /**
     * 
     * @type {number}
     * @memberof PhaseResult
     */
    succeeded?: number;
    /**
     * 
     * @type {number}
     * @memberof PhaseResult
     */
    total?: number;
}

/**
 * Check if a given object implements the PhaseResult interface.
 */
export function instanceOfPhaseResult(value: object): value is PhaseResult {
    return true;
}

export function PhaseResultFromJSON(json: any): PhaseResult {
    return PhaseResultFromJSONTyped(json, false);
}

export function PhaseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhaseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'failed': json['failed'] == null ? undefined : json['failed'],
        'succeeded': json['succeeded'] == null ? undefined : json['succeeded'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function PhaseResultToJSON(json: any): PhaseResult {
    return PhaseResultToJSONTyped(json, false);
}

export function PhaseResultToJSONTyped(value?: PhaseResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'failed': value['failed'],
        'succeeded': value['succeeded'],
        'total': value['total'],
    };
}

