/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanChangeCreatePreview
 */
export interface PlanChangeCreatePreview {
    /**
     * 
     * @type {number}
     * @memberof PlanChangeCreatePreview
     */
    chargeNowMinor?: number;
    /**
     * 
     * @type {PlanChangeCreatePreviewRecurringIntervalEnum}
     * @memberof PlanChangeCreatePreview
     */
    recurringInterval?: PlanChangeCreatePreviewRecurringIntervalEnum;
    /**
     * 
     * @type {number}
     * @memberof PlanChangeCreatePreview
     */
    recurringMinor?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PlanChangeCreatePreview
     */
    requiresPhone?: boolean;
}


/**
 * @export
 */
export const PlanChangeCreatePreviewRecurringIntervalEnum = {
    Monthly: 'MONTHLY',
    Yearly: 'YEARLY'
} as const;
export type PlanChangeCreatePreviewRecurringIntervalEnum = typeof PlanChangeCreatePreviewRecurringIntervalEnum[keyof typeof PlanChangeCreatePreviewRecurringIntervalEnum];


/**
 * Check if a given object implements the PlanChangeCreatePreview interface.
 */
export function instanceOfPlanChangeCreatePreview(value: object): value is PlanChangeCreatePreview {
    return true;
}

export function PlanChangeCreatePreviewFromJSON(json: any): PlanChangeCreatePreview {
    return PlanChangeCreatePreviewFromJSONTyped(json, false);
}

export function PlanChangeCreatePreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanChangeCreatePreview {
    if (json == null) {
        return json;
    }
    return {
        
        'chargeNowMinor': json['charge_now_minor'] == null ? undefined : json['charge_now_minor'],
        'recurringInterval': json['recurring_interval'] == null ? undefined : json['recurring_interval'],
        'recurringMinor': json['recurring_minor'] == null ? undefined : json['recurring_minor'],
        'requiresPhone': json['requires_phone'] == null ? undefined : json['requires_phone'],
    };
}

export function PlanChangeCreatePreviewToJSON(json: any): PlanChangeCreatePreview {
    return PlanChangeCreatePreviewToJSONTyped(json, false);
}

export function PlanChangeCreatePreviewToJSONTyped(value?: PlanChangeCreatePreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'charge_now_minor': value['chargeNowMinor'],
        'recurring_interval': value['recurringInterval'],
        'recurring_minor': value['recurringMinor'],
        'requires_phone': value['requiresPhone'],
    };
}

