/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanQuotas
 */
export interface PlanQuotas {
    /**
     * 
     * @type {number}
     * @memberof PlanQuotas
     */
    maxApiKeys?: number;
    /**
     * 
     * @type {number}
     * @memberof PlanQuotas
     */
    maxApps?: number;
    /**
     * 
     * @type {number}
     * @memberof PlanQuotas
     */
    maxMembers?: number;
    /**
     * 
     * @type {number}
     * @memberof PlanQuotas
     */
    maxTeams?: number;
    /**
     * 
     * @type {number}
     * @memberof PlanQuotas
     */
    memoryCredits?: number;
    /**
     * 
     * @type {number}
     * @memberof PlanQuotas
     */
    searchCredits?: number;
}

/**
 * Check if a given object implements the PlanQuotas interface.
 */
export function instanceOfPlanQuotas(value: object): value is PlanQuotas {
    return true;
}

export function PlanQuotasFromJSON(json: any): PlanQuotas {
    return PlanQuotasFromJSONTyped(json, false);
}

export function PlanQuotasFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanQuotas {
    if (json == null) {
        return json;
    }
    return {
        
        'maxApiKeys': json['max_api_keys'] == null ? undefined : json['max_api_keys'],
        'maxApps': json['max_apps'] == null ? undefined : json['max_apps'],
        'maxMembers': json['max_members'] == null ? undefined : json['max_members'],
        'maxTeams': json['max_teams'] == null ? undefined : json['max_teams'],
        'memoryCredits': json['memory_credits'] == null ? undefined : json['memory_credits'],
        'searchCredits': json['search_credits'] == null ? undefined : json['search_credits'],
    };
}

export function PlanQuotasToJSON(json: any): PlanQuotas {
    return PlanQuotasToJSONTyped(json, false);
}

export function PlanQuotasToJSONTyped(value?: PlanQuotas | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_api_keys': value['maxApiKeys'],
        'max_apps': value['maxApps'],
        'max_members': value['maxMembers'],
        'max_teams': value['maxTeams'],
        'memory_credits': value['memoryCredits'],
        'search_credits': value['searchCredits'],
    };
}

