/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanChangeCancelToFreePreview
 */
export interface PlanChangeCancelToFreePreview {
    /**
     * 
     * @type {string}
     * @memberof PlanChangeCancelToFreePreview
     */
    activeUntil?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanChangeCancelToFreePreview
     */
    currentPlanName?: string;
}

/**
 * Check if a given object implements the PlanChangeCancelToFreePreview interface.
 */
export function instanceOfPlanChangeCancelToFreePreview(value: object): value is PlanChangeCancelToFreePreview {
    return true;
}

export function PlanChangeCancelToFreePreviewFromJSON(json: any): PlanChangeCancelToFreePreview {
    return PlanChangeCancelToFreePreviewFromJSONTyped(json, false);
}

export function PlanChangeCancelToFreePreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanChangeCancelToFreePreview {
    if (json == null) {
        return json;
    }
    return {
        
        'activeUntil': json['active_until'] == null ? undefined : json['active_until'],
        'currentPlanName': json['current_plan_name'] == null ? undefined : json['current_plan_name'],
    };
}

export function PlanChangeCancelToFreePreviewToJSON(json: any): PlanChangeCancelToFreePreview {
    return PlanChangeCancelToFreePreviewToJSONTyped(json, false);
}

export function PlanChangeCancelToFreePreviewToJSONTyped(value?: PlanChangeCancelToFreePreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_until': value['activeUntil'],
        'current_plan_name': value['currentPlanName'],
    };
}

