/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanCreditCosts
 */
export interface PlanCreditCosts {
    /**
     * 
     * @type {number}
     * @memberof PlanCreditCosts
     */
    contextAwareSearch?: number;
    /**
     * 
     * @type {number}
     * @memberof PlanCreditCosts
     */
    deepSearch?: number;
    /**
     * 
     * @type {number}
     * @memberof PlanCreditCosts
     */
    memoryCreate?: number;
    /**
     * 
     * @type {number}
     * @memberof PlanCreditCosts
     */
    quickSearch?: number;
}

/**
 * Check if a given object implements the PlanCreditCosts interface.
 */
export function instanceOfPlanCreditCosts(value: object): value is PlanCreditCosts {
    return true;
}

export function PlanCreditCostsFromJSON(json: any): PlanCreditCosts {
    return PlanCreditCostsFromJSONTyped(json, false);
}

export function PlanCreditCostsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanCreditCosts {
    if (json == null) {
        return json;
    }
    return {
        
        'contextAwareSearch': json['context_aware_search'] == null ? undefined : json['context_aware_search'],
        'deepSearch': json['deep_search'] == null ? undefined : json['deep_search'],
        'memoryCreate': json['memory_create'] == null ? undefined : json['memory_create'],
        'quickSearch': json['quick_search'] == null ? undefined : json['quick_search'],
    };
}

export function PlanCreditCostsToJSON(json: any): PlanCreditCosts {
    return PlanCreditCostsToJSONTyped(json, false);
}

export function PlanCreditCostsToJSONTyped(value?: PlanCreditCosts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context_aware_search': value['contextAwareSearch'],
        'deep_search': value['deepSearch'],
        'memory_create': value['memoryCreate'],
        'quick_search': value['quickSearch'],
    };
}

