/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanChangeResumeAuthPreview
 */
export interface PlanChangeResumeAuthPreview {
    /**
     * 
     * @type {string}
     * @memberof PlanChangeResumeAuthPreview
     */
    planName?: string;
}

/**
 * Check if a given object implements the PlanChangeResumeAuthPreview interface.
 */
export function instanceOfPlanChangeResumeAuthPreview(value: object): value is PlanChangeResumeAuthPreview {
    return true;
}

export function PlanChangeResumeAuthPreviewFromJSON(json: any): PlanChangeResumeAuthPreview {
    return PlanChangeResumeAuthPreviewFromJSONTyped(json, false);
}

export function PlanChangeResumeAuthPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanChangeResumeAuthPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'planName': json['plan_name'] == null ? undefined : json['plan_name'],
    };
}

export function PlanChangeResumeAuthPreviewToJSON(json: any): PlanChangeResumeAuthPreview {
    return PlanChangeResumeAuthPreviewToJSONTyped(json, false);
}

export function PlanChangeResumeAuthPreviewToJSONTyped(value?: PlanChangeResumeAuthPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plan_name': value['planName'],
    };
}

