/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanRateLimits } from './PlanRateLimits';
import {
    PlanRateLimitsFromJSON,
    PlanRateLimitsFromJSONTyped,
    PlanRateLimitsToJSON,
    PlanRateLimitsToJSONTyped,
} from './PlanRateLimits';
import type { PlanQuotas } from './PlanQuotas';
import {
    PlanQuotasFromJSON,
    PlanQuotasFromJSONTyped,
    PlanQuotasToJSON,
    PlanQuotasToJSONTyped,
} from './PlanQuotas';

/**
 * 
 * @export
 * @interface PlanInfo
 */
export interface PlanInfo {
    /**
     * 
     * @type {string}
     * @memberof PlanInfo
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanInfo
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlanInfo
     */
    isExternal?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PlanInfo
     */
    name?: string;
    /**
     * 
     * @type {PlanQuotas}
     * @memberof PlanInfo
     */
    quotas?: PlanQuotas;
    /**
     * 
     * @type {PlanRateLimits}
     * @memberof PlanInfo
     */
    rateLimits?: PlanRateLimits;
    /**
     * 
     * @type {string}
     * @memberof PlanInfo
     */
    slug?: string;
}

/**
 * Check if a given object implements the PlanInfo interface.
 */
export function instanceOfPlanInfo(value: object): value is PlanInfo {
    return true;
}

export function PlanInfoFromJSON(json: any): PlanInfo {
    return PlanInfoFromJSONTyped(json, false);
}

export function PlanInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'isExternal': json['is_external'] == null ? undefined : json['is_external'],
        'name': json['name'] == null ? undefined : json['name'],
        'quotas': json['quotas'] == null ? undefined : PlanQuotasFromJSON(json['quotas']),
        'rateLimits': json['rate_limits'] == null ? undefined : PlanRateLimitsFromJSON(json['rate_limits']),
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function PlanInfoToJSON(json: any): PlanInfo {
    return PlanInfoToJSONTyped(json, false);
}

export function PlanInfoToJSONTyped(value?: PlanInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'id': value['id'],
        'is_external': value['isExternal'],
        'name': value['name'],
        'quotas': PlanQuotasToJSON(value['quotas']),
        'rate_limits': PlanRateLimitsToJSON(value['rateLimits']),
        'slug': value['slug'],
    };
}

