/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanDirectives } from './PlanDirectives';
import {
    PlanDirectivesFromJSON,
    PlanDirectivesFromJSONTyped,
    PlanDirectivesToJSON,
    PlanDirectivesToJSONTyped,
} from './PlanDirectives';
import type { PlanCreditCosts } from './PlanCreditCosts';
import {
    PlanCreditCostsFromJSON,
    PlanCreditCostsFromJSONTyped,
    PlanCreditCostsToJSON,
    PlanCreditCostsToJSONTyped,
} from './PlanCreditCosts';
import type { PlanRateLimits } from './PlanRateLimits';
import {
    PlanRateLimitsFromJSON,
    PlanRateLimitsFromJSONTyped,
    PlanRateLimitsToJSON,
    PlanRateLimitsToJSONTyped,
} from './PlanRateLimits';
import type { PlanFeatures } from './PlanFeatures';
import {
    PlanFeaturesFromJSON,
    PlanFeaturesFromJSONTyped,
    PlanFeaturesToJSON,
    PlanFeaturesToJSONTyped,
} from './PlanFeatures';
import type { PlanPricing } from './PlanPricing';
import {
    PlanPricingFromJSON,
    PlanPricingFromJSONTyped,
    PlanPricingToJSON,
    PlanPricingToJSONTyped,
} from './PlanPricing';
import type { PlanQuotas } from './PlanQuotas';
import {
    PlanQuotasFromJSON,
    PlanQuotasFromJSONTyped,
    PlanQuotasToJSON,
    PlanQuotasToJSONTyped,
} from './PlanQuotas';

/**
 * 
 * @export
 * @interface PlanResponse
 */
export interface PlanResponse {
    /**
     * 
     * @type {number}
     * @memberof PlanResponse
     */
    amountMinor?: number;
    /**
     * 
     * @type {{ [key: string]: PlanPricing; }}
     * @memberof PlanResponse
     */
    countryPricing?: { [key: string]: PlanPricing; };
    /**
     * 
     * @type {string}
     * @memberof PlanResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {PlanCreditCosts}
     * @memberof PlanResponse
     */
    creditCosts?: PlanCreditCosts;
    /**
     * 
     * @type {string}
     * @memberof PlanResponse
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanResponse
     */
    description?: string;
    /**
     * 
     * @type {PlanDirectives}
     * @memberof PlanResponse
     */
    directives?: PlanDirectives;
    /**
     * 
     * @type {PlanFeatures}
     * @memberof PlanResponse
     */
    features?: PlanFeatures;
    /**
     * 
     * @type {string}
     * @memberof PlanResponse
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof PlanResponse
     */
    interval?: number;
    /**
     * 
     * @type {string}
     * @memberof PlanResponse
     */
    intervalType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlanResponse
     */
    isCurrent?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlanResponse
     */
    isDefault?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PlanResponse
     */
    maxAmountMinor?: number;
    /**
     * 
     * @type {number}
     * @memberof PlanResponse
     */
    maxCycles?: number;
    /**
     * 
     * @type {string}
     * @memberof PlanResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanResponse
     */
    planType?: string;
    /**
     * 
     * @type {PlanPricing}
     * @memberof PlanResponse
     */
    pricing?: PlanPricing;
    /**
     * 
     * @type {PlanQuotas}
     * @memberof PlanResponse
     */
    quotas?: PlanQuotas;
    /**
     * 
     * @type {PlanRateLimits}
     * @memberof PlanResponse
     */
    rateLimits?: PlanRateLimits;
    /**
     * 
     * @type {string}
     * @memberof PlanResponse
     */
    slug?: string;
    /**
     * 
     * @type {number}
     * @memberof PlanResponse
     */
    sortOrder?: number;
    /**
     * 
     * @type {string}
     * @memberof PlanResponse
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof PlanResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the PlanResponse interface.
 */
export function instanceOfPlanResponse(value: object): value is PlanResponse {
    return true;
}

export function PlanResponseFromJSON(json: any): PlanResponse {
    return PlanResponseFromJSONTyped(json, false);
}

export function PlanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amountMinor': json['amount_minor'] == null ? undefined : json['amount_minor'],
        'countryPricing': json['country_pricing'] == null ? undefined : (mapValues(json['country_pricing'], PlanPricingFromJSON)),
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'creditCosts': json['credit_costs'] == null ? undefined : PlanCreditCostsFromJSON(json['credit_costs']),
        'currency': json['currency'] == null ? undefined : json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'directives': json['directives'] == null ? undefined : PlanDirectivesFromJSON(json['directives']),
        'features': json['features'] == null ? undefined : PlanFeaturesFromJSON(json['features']),
        'id': json['id'] == null ? undefined : json['id'],
        'interval': json['interval'] == null ? undefined : json['interval'],
        'intervalType': json['interval_type'] == null ? undefined : json['interval_type'],
        'isCurrent': json['is_current'] == null ? undefined : json['is_current'],
        'isDefault': json['is_default'] == null ? undefined : json['is_default'],
        'maxAmountMinor': json['max_amount_minor'] == null ? undefined : json['max_amount_minor'],
        'maxCycles': json['max_cycles'] == null ? undefined : json['max_cycles'],
        'name': json['name'] == null ? undefined : json['name'],
        'planType': json['plan_type'] == null ? undefined : json['plan_type'],
        'pricing': json['pricing'] == null ? undefined : PlanPricingFromJSON(json['pricing']),
        'quotas': json['quotas'] == null ? undefined : PlanQuotasFromJSON(json['quotas']),
        'rateLimits': json['rate_limits'] == null ? undefined : PlanRateLimitsFromJSON(json['rate_limits']),
        'slug': json['slug'] == null ? undefined : json['slug'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function PlanResponseToJSON(json: any): PlanResponse {
    return PlanResponseToJSONTyped(json, false);
}

export function PlanResponseToJSONTyped(value?: PlanResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_minor': value['amountMinor'],
        'country_pricing': value['countryPricing'] == null ? undefined : (mapValues(value['countryPricing'], PlanPricingToJSON)),
        'created_at': value['createdAt'],
        'credit_costs': PlanCreditCostsToJSON(value['creditCosts']),
        'currency': value['currency'],
        'description': value['description'],
        'directives': PlanDirectivesToJSON(value['directives']),
        'features': PlanFeaturesToJSON(value['features']),
        'id': value['id'],
        'interval': value['interval'],
        'interval_type': value['intervalType'],
        'is_current': value['isCurrent'],
        'is_default': value['isDefault'],
        'max_amount_minor': value['maxAmountMinor'],
        'max_cycles': value['maxCycles'],
        'name': value['name'],
        'plan_type': value['planType'],
        'pricing': PlanPricingToJSON(value['pricing']),
        'quotas': PlanQuotasToJSON(value['quotas']),
        'rate_limits': PlanRateLimitsToJSON(value['rateLimits']),
        'slug': value['slug'],
        'sort_order': value['sortOrder'],
        'updated_at': value['updatedAt'],
        'version': value['version'],
    };
}

