/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanChangeBlockedPreview
 */
export interface PlanChangeBlockedPreview {
    /**
     * 
     * @type {string}
     * @memberof PlanChangeBlockedPreview
     */
    reason?: string;
}

/**
 * Check if a given object implements the PlanChangeBlockedPreview interface.
 */
export function instanceOfPlanChangeBlockedPreview(value: object): value is PlanChangeBlockedPreview {
    return true;
}

export function PlanChangeBlockedPreviewFromJSON(json: any): PlanChangeBlockedPreview {
    return PlanChangeBlockedPreviewFromJSONTyped(json, false);
}

export function PlanChangeBlockedPreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanChangeBlockedPreview {
    if (json == null) {
        return json;
    }
    return {
        
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function PlanChangeBlockedPreviewToJSON(json: any): PlanChangeBlockedPreview {
    return PlanChangeBlockedPreviewToJSONTyped(json, false);
}

export function PlanChangeBlockedPreviewToJSONTyped(value?: PlanChangeBlockedPreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reason': value['reason'],
    };
}

