/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlanChangeCommitResponse
 */
export interface PlanChangeCommitResponse {
    /**
     * 
     * @type {PlanChangeCommitResponseActionEnum}
     * @memberof PlanChangeCommitResponse
     */
    action?: PlanChangeCommitResponseActionEnum;
    /**
     * 
     * @type {string}
     * @memberof PlanChangeCommitResponse
     */
    authLink?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanChangeCommitResponse
     */
    authSessionId?: string;
    /**
     * CheckoutSessionID is the one-time first-cycle Order's Cashfree payment session id (paid before mandate auth).
     * @type {string}
     * @memberof PlanChangeCommitResponse
     */
    checkoutSessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanChangeCommitResponse
     */
    effectiveAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanChangeCommitResponse
     */
    environment?: string;
    /**
     * 
     * @type {string}
     * @memberof PlanChangeCommitResponse
     */
    provider?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlanChangeCommitResponse
     */
    requiresAuthorization?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PlanChangeCommitResponse
     */
    subscriptionId?: string;
}


/**
 * @export
 */
export const PlanChangeCommitResponseActionEnum = {
    Create: 'CREATE',
    Upgrade: 'UPGRADE',
    Downgrade: 'DOWNGRADE',
    CancelToFree: 'CANCEL_TO_FREE',
    ResumeAuth: 'RESUME_AUTH',
    Noop: 'NOOP',
    Blocked: 'BLOCKED'
} as const;
export type PlanChangeCommitResponseActionEnum = typeof PlanChangeCommitResponseActionEnum[keyof typeof PlanChangeCommitResponseActionEnum];


/**
 * Check if a given object implements the PlanChangeCommitResponse interface.
 */
export function instanceOfPlanChangeCommitResponse(value: object): value is PlanChangeCommitResponse {
    return true;
}

export function PlanChangeCommitResponseFromJSON(json: any): PlanChangeCommitResponse {
    return PlanChangeCommitResponseFromJSONTyped(json, false);
}

export function PlanChangeCommitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlanChangeCommitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'authLink': json['auth_link'] == null ? undefined : json['auth_link'],
        'authSessionId': json['auth_session_id'] == null ? undefined : json['auth_session_id'],
        'checkoutSessionId': json['checkout_session_id'] == null ? undefined : json['checkout_session_id'],
        'effectiveAt': json['effective_at'] == null ? undefined : json['effective_at'],
        'environment': json['environment'] == null ? undefined : json['environment'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'requiresAuthorization': json['requires_authorization'] == null ? undefined : json['requires_authorization'],
        'subscriptionId': json['subscription_id'] == null ? undefined : json['subscription_id'],
    };
}

export function PlanChangeCommitResponseToJSON(json: any): PlanChangeCommitResponse {
    return PlanChangeCommitResponseToJSONTyped(json, false);
}

export function PlanChangeCommitResponseToJSONTyped(value?: PlanChangeCommitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'auth_link': value['authLink'],
        'auth_session_id': value['authSessionId'],
        'checkout_session_id': value['checkoutSessionId'],
        'effective_at': value['effectiveAt'],
        'environment': value['environment'],
        'provider': value['provider'],
        'requires_authorization': value['requiresAuthorization'],
        'subscription_id': value['subscriptionId'],
    };
}

