/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionPaymentResponse } from './SubscriptionPaymentResponse';
import {
    SubscriptionPaymentResponseFromJSON,
    SubscriptionPaymentResponseFromJSONTyped,
    SubscriptionPaymentResponseToJSON,
    SubscriptionPaymentResponseToJSONTyped,
} from './SubscriptionPaymentResponse';

/**
 * 
 * @export
 * @interface ProviderHistoryView
 */
export interface ProviderHistoryView {
    /**
     * 
     * @type {Array<SubscriptionPaymentResponse>}
     * @memberof ProviderHistoryView
     */
    payments?: Array<SubscriptionPaymentResponse>;
}

/**
 * Check if a given object implements the ProviderHistoryView interface.
 */
export function instanceOfProviderHistoryView(value: object): value is ProviderHistoryView {
    return true;
}

export function ProviderHistoryViewFromJSON(json: any): ProviderHistoryView {
    return ProviderHistoryViewFromJSONTyped(json, false);
}

export function ProviderHistoryViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProviderHistoryView {
    if (json == null) {
        return json;
    }
    return {
        
        'payments': json['payments'] == null ? undefined : ((json['payments'] as Array<any>).map(SubscriptionPaymentResponseFromJSON)),
    };
}

export function ProviderHistoryViewToJSON(json: any): ProviderHistoryView {
    return ProviderHistoryViewToJSONTyped(json, false);
}

export function ProviderHistoryViewToJSONTyped(value?: ProviderHistoryView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payments': value['payments'] == null ? undefined : ((value['payments'] as Array<any>).map(SubscriptionPaymentResponseToJSON)),
    };
}

