/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicRelationshipType
 */
export interface PublicRelationshipType {
    /**
     * 
     * @type {string}
     * @memberof PublicRelationshipType
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicRelationshipType
     */
    from?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PublicRelationshipType
     */
    queryExpansion?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicRelationshipType
     */
    to?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicRelationshipType
     */
    type?: string;
}

/**
 * Check if a given object implements the PublicRelationshipType interface.
 */
export function instanceOfPublicRelationshipType(value: object): value is PublicRelationshipType {
    return true;
}

export function PublicRelationshipTypeFromJSON(json: any): PublicRelationshipType {
    return PublicRelationshipTypeFromJSONTyped(json, false);
}

export function PublicRelationshipTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicRelationshipType {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'from': json['from'] == null ? undefined : json['from'],
        'queryExpansion': json['query_expansion'] == null ? undefined : json['query_expansion'],
        'to': json['to'] == null ? undefined : json['to'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function PublicRelationshipTypeToJSON(json: any): PublicRelationshipType {
    return PublicRelationshipTypeToJSONTyped(json, false);
}

export function PublicRelationshipTypeToJSONTyped(value?: PublicRelationshipType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'from': value['from'],
        'query_expansion': value['queryExpansion'],
        'to': value['to'],
        'type': value['type'],
    };
}

