/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublishDraftResponse
 */
export interface PublishDraftResponse {
    /**
     * 
     * @type {string}
     * @memberof PublishDraftResponse
     */
    appId?: string;
    /**
     * 
     * @type {string}
     * @memberof PublishDraftResponse
     */
    defaultApiKey?: string;
}

/**
 * Check if a given object implements the PublishDraftResponse interface.
 */
export function instanceOfPublishDraftResponse(value: object): value is PublishDraftResponse {
    return true;
}

export function PublishDraftResponseFromJSON(json: any): PublishDraftResponse {
    return PublishDraftResponseFromJSONTyped(json, false);
}

export function PublishDraftResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishDraftResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'defaultApiKey': json['default_api_key'] == null ? undefined : json['default_api_key'],
    };
}

export function PublishDraftResponseToJSON(json: any): PublishDraftResponse {
    return PublishDraftResponseToJSONTyped(json, false);
}

export function PublishDraftResponseToJSONTyped(value?: PublishDraftResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'default_api_key': value['defaultApiKey'],
    };
}

