/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OperationRateLimitStatus } from './OperationRateLimitStatus';
import {
    OperationRateLimitStatusFromJSON,
    OperationRateLimitStatusFromJSONTyped,
    OperationRateLimitStatusToJSON,
    OperationRateLimitStatusToJSONTyped,
} from './OperationRateLimitStatus';

/**
 * 
 * @export
 * @interface RateLimitStatusResponse
 */
export interface RateLimitStatusResponse {
    /**
     * 
     * @type {Array<OperationRateLimitStatus>}
     * @memberof RateLimitStatusResponse
     */
    operations?: Array<OperationRateLimitStatus>;
}

/**
 * Check if a given object implements the RateLimitStatusResponse interface.
 */
export function instanceOfRateLimitStatusResponse(value: object): value is RateLimitStatusResponse {
    return true;
}

export function RateLimitStatusResponseFromJSON(json: any): RateLimitStatusResponse {
    return RateLimitStatusResponseFromJSONTyped(json, false);
}

export function RateLimitStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RateLimitStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'operations': json['operations'] == null ? undefined : ((json['operations'] as Array<any>).map(OperationRateLimitStatusFromJSON)),
    };
}

export function RateLimitStatusResponseToJSON(json: any): RateLimitStatusResponse {
    return RateLimitStatusResponseToJSONTyped(json, false);
}

export function RateLimitStatusResponseToJSONTyped(value?: RateLimitStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operations': value['operations'] == null ? undefined : ((value['operations'] as Array<any>).map(OperationRateLimitStatusToJSON)),
    };
}

