/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RateLimitWindow
 */
export interface RateLimitWindow {
    /**
     * Current count in this window
     * @type {number}
     * @memberof RateLimitWindow
     */
    current?: number;
    /**
     * Configured limit from plan
     * @type {number}
     * @memberof RateLimitWindow
     */
    limit?: number;
    /**
     * "per_second", "per_minute", "per_day"
     * @type {string}
     * @memberof RateLimitWindow
     */
    window?: string;
}

/**
 * Check if a given object implements the RateLimitWindow interface.
 */
export function instanceOfRateLimitWindow(value: object): value is RateLimitWindow {
    return true;
}

export function RateLimitWindowFromJSON(json: any): RateLimitWindow {
    return RateLimitWindowFromJSONTyped(json, false);
}

export function RateLimitWindowFromJSONTyped(json: any, ignoreDiscriminator: boolean): RateLimitWindow {
    if (json == null) {
        return json;
    }
    return {
        
        'current': json['current'] == null ? undefined : json['current'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'window': json['window'] == null ? undefined : json['window'],
    };
}

export function RateLimitWindowToJSON(json: any): RateLimitWindow {
    return RateLimitWindowToJSONTyped(json, false);
}

export function RateLimitWindowToJSONTyped(value?: RateLimitWindow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current': value['current'],
        'limit': value['limit'],
        'window': value['window'],
    };
}

