/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Extracted relationship output
 * @export
 * @interface RelationshipOutputDTO
 */
export interface RelationshipOutputDTO {
    /**
     * 
     * @type {boolean}
     * @memberof RelationshipOutputDTO
     */
    created?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RelationshipOutputDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipOutputDTO
     */
    sourceEntityId?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipOutputDTO
     */
    targetEntityId?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipOutputDTO
     */
    type?: string;
}

/**
 * Check if a given object implements the RelationshipOutputDTO interface.
 */
export function instanceOfRelationshipOutputDTO(value: object): value is RelationshipOutputDTO {
    return true;
}

export function RelationshipOutputDTOFromJSON(json: any): RelationshipOutputDTO {
    return RelationshipOutputDTOFromJSONTyped(json, false);
}

export function RelationshipOutputDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipOutputDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'created': json['created'] == null ? undefined : json['created'],
        'id': json['id'] == null ? undefined : json['id'],
        'sourceEntityId': json['source_entity_id'] == null ? undefined : json['source_entity_id'],
        'targetEntityId': json['target_entity_id'] == null ? undefined : json['target_entity_id'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function RelationshipOutputDTOToJSON(json: any): RelationshipOutputDTO {
    return RelationshipOutputDTOToJSONTyped(json, false);
}

export function RelationshipOutputDTOToJSONTyped(value?: RelationshipOutputDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created': value['created'],
        'id': value['id'],
        'source_entity_id': value['sourceEntityId'],
        'target_entity_id': value['targetEntityId'],
        'type': value['type'],
    };
}

