/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RelationshipResponse
 */
export interface RelationshipResponse {
    /**
     * 
     * @type {string}
     * @memberof RelationshipResponse
     */
    appId?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipResponse
     */
    fact?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipResponse
     */
    id?: string;
    /**
     * 
     * @type {object}
     * @memberof RelationshipResponse
     */
    metadata?: object;
    /**
     * 
     * @type {string}
     * @memberof RelationshipResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipResponse
     */
    sourceEntityId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RelationshipResponse
     */
    sourceMemoryIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RelationshipResponse
     */
    targetEntityId?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipResponse
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipResponse
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipResponse
     */
    validFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof RelationshipResponse
     */
    validTo?: string;
    /**
     * 
     * @type {number}
     * @memberof RelationshipResponse
     */
    weight?: number;
}

/**
 * Check if a given object implements the RelationshipResponse interface.
 */
export function instanceOfRelationshipResponse(value: object): value is RelationshipResponse {
    return true;
}

export function RelationshipResponseFromJSON(json: any): RelationshipResponse {
    return RelationshipResponseFromJSONTyped(json, false);
}

export function RelationshipResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'fact': json['fact'] == null ? undefined : json['fact'],
        'id': json['id'] == null ? undefined : json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'] == null ? undefined : json['name'],
        'sourceEntityId': json['source_entity_id'] == null ? undefined : json['source_entity_id'],
        'sourceMemoryIds': json['source_memory_ids'] == null ? undefined : json['source_memory_ids'],
        'targetEntityId': json['target_entity_id'] == null ? undefined : json['target_entity_id'],
        'type': json['type'] == null ? undefined : json['type'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'validFrom': json['valid_from'] == null ? undefined : json['valid_from'],
        'validTo': json['valid_to'] == null ? undefined : json['valid_to'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function RelationshipResponseToJSON(json: any): RelationshipResponse {
    return RelationshipResponseToJSONTyped(json, false);
}

export function RelationshipResponseToJSONTyped(value?: RelationshipResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'created_at': value['createdAt'],
        'fact': value['fact'],
        'id': value['id'],
        'metadata': value['metadata'],
        'name': value['name'],
        'source_entity_id': value['sourceEntityId'],
        'source_memory_ids': value['sourceMemoryIds'],
        'target_entity_id': value['targetEntityId'],
        'type': value['type'],
        'updated_at': value['updatedAt'],
        'valid_from': value['validFrom'],
        'valid_to': value['validTo'],
        'weight': value['weight'],
    };
}

