/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RelationshipType
 */
export interface RelationshipType {
    /**
     * Description explains what this relationship type represents.
     * Example: "A prescription of medication for a patient"
     * @type {string}
     * @memberof RelationshipType
     */
    description: string;
    /**
     * From is the optional source entity type constraint (e.g., "medication").
     * Empty string means no constraint (relationship can start from any entity).
     * @type {string}
     * @memberof RelationshipType
     */
    from: string;
    /**
     * GenerateReverse indicates whether reverse-direction retrieval vectors should be generated for this type.
     * @type {boolean}
     * @memberof RelationshipType
     */
    generateReverse: boolean;
    /**
     * GenerateSynonyms indicates whether type-level synonym vectors should be generated for this type.
     * @type {boolean}
     * @memberof RelationshipType
     */
    generateSynonyms: boolean;
    /**
     * ReverseType is the label for the reverse direction (e.g. mother_of -> son_of). Empty string when generate_reverse is false.
     * @type {string}
     * @memberof RelationshipType
     */
    reverseType: string;
    /**
     * To is the optional target entity type constraint (e.g., "patient").
     * Empty string means no constraint (relationship can point to any entity).
     * @type {string}
     * @memberof RelationshipType
     */
    to: string;
    /**
     * Type is the relationship type name (e.g., "prescribed_to", "allergic_to")
     * @type {string}
     * @memberof RelationshipType
     */
    type: string;
}

/**
 * Check if a given object implements the RelationshipType interface.
 */
export function instanceOfRelationshipType(value: object): value is RelationshipType {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('generateReverse' in value) || value['generateReverse'] === undefined) return false;
    if (!('generateSynonyms' in value) || value['generateSynonyms'] === undefined) return false;
    if (!('reverseType' in value) || value['reverseType'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function RelationshipTypeFromJSON(json: any): RelationshipType {
    return RelationshipTypeFromJSONTyped(json, false);
}

export function RelationshipTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelationshipType {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'from': json['from'],
        'generateReverse': json['generate_reverse'],
        'generateSynonyms': json['generate_synonyms'],
        'reverseType': json['reverse_type'],
        'to': json['to'],
        'type': json['type'],
    };
}

export function RelationshipTypeToJSON(json: any): RelationshipType {
    return RelationshipTypeToJSONTyped(json, false);
}

export function RelationshipTypeToJSONTyped(value?: RelationshipType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'from': value['from'],
        'generate_reverse': value['generateReverse'],
        'generate_synonyms': value['generateSynonyms'],
        'reverse_type': value['reverseType'],
        'to': value['to'],
        'type': value['type'],
    };
}

