/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplayWebhookResponse
 */
export interface ReplayWebhookResponse {
    /**
     * 
     * @type {string}
     * @memberof ReplayWebhookResponse
     */
    eventType?: string;
    /**
     * 
     * @type {string}
     * @memberof ReplayWebhookResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the ReplayWebhookResponse interface.
 */
export function instanceOfReplayWebhookResponse(value: object): value is ReplayWebhookResponse {
    return true;
}

export function ReplayWebhookResponseFromJSON(json: any): ReplayWebhookResponse {
    return ReplayWebhookResponseFromJSONTyped(json, false);
}

export function ReplayWebhookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplayWebhookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'eventType': json['event_type'] == null ? undefined : json['event_type'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ReplayWebhookResponseToJSON(json: any): ReplayWebhookResponse {
    return ReplayWebhookResponseToJSONTyped(json, false);
}

export function ReplayWebhookResponseToJSONTyped(value?: ReplayWebhookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_type': value['eventType'],
        'status': value['status'],
    };
}

