/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RerankerOptions
 */
export interface RerankerOptions {
    /**
     * K is the RRF constant for reciprocal rank fusion (default: 60)
     * @type {number}
     * @memberof RerankerOptions
     */
    k?: number;
    /**
     * Lambda is the MMR diversity parameter.
     * 0.0 = maximum diversity, 1.0 = pure relevance.
     * @type {number}
     * @memberof RerankerOptions
     */
    lambda?: number;
    /**
     * TopN limits maximum results to return after reranking.
     * 0 means return all results.
     * @type {number}
     * @memberof RerankerOptions
     */
    topN?: number;
    /**
     * Type specifies the reranker algorithm: rrf, rrf_temporal, mmr, temporal, node_distance, cross_encoder
     * @type {RerankerOptionsTypeEnum}
     * @memberof RerankerOptions
     */
    type?: RerankerOptionsTypeEnum;
}


/**
 * @export
 */
export const RerankerOptionsTypeEnum = {
    Rrf: 'rrf',
    RrfTemporal: 'rrf_temporal',
    Mmr: 'mmr',
    Temporal: 'temporal',
    NodeDistance: 'node_distance',
    CrossEncoder: 'cross_encoder'
} as const;
export type RerankerOptionsTypeEnum = typeof RerankerOptionsTypeEnum[keyof typeof RerankerOptionsTypeEnum];


/**
 * Check if a given object implements the RerankerOptions interface.
 */
export function instanceOfRerankerOptions(value: object): value is RerankerOptions {
    return true;
}

export function RerankerOptionsFromJSON(json: any): RerankerOptions {
    return RerankerOptionsFromJSONTyped(json, false);
}

export function RerankerOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RerankerOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'k': json['k'] == null ? undefined : json['k'],
        'lambda': json['lambda'] == null ? undefined : json['lambda'],
        'topN': json['top_n'] == null ? undefined : json['top_n'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function RerankerOptionsToJSON(json: any): RerankerOptions {
    return RerankerOptionsToJSONTyped(json, false);
}

export function RerankerOptionsToJSONTyped(value?: RerankerOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'k': value['k'],
        'lambda': value['lambda'],
        'top_n': value['topN'],
        'type': value['type'],
    };
}

