/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RerankerAdjustment
 */
export interface RerankerAdjustment {
    /**
     * AgeDays is the memory age in days (for temporal reranker)
     * @type {number}
     * @memberof RerankerAdjustment
     */
    ageDays?: number;
    /**
     * DecayFactor is the temporal decay multiplier (for temporal reranker)
     * @type {number}
     * @memberof RerankerAdjustment
     */
    decayFactor?: number;
    /**
     * RankAfter is the result's rank after this reranker
     * @type {number}
     * @memberof RerankerAdjustment
     */
    rankAfter?: number;
    /**
     * RankBefore is the result's rank before this reranker
     * @type {number}
     * @memberof RerankerAdjustment
     */
    rankBefore?: number;
    /**
     * ScoreDelta is the change in score (positive = boosted, negative = demoted)
     * @type {number}
     * @memberof RerankerAdjustment
     */
    scoreDelta?: number;
    /**
     * Step is the reranker name (e.g., "rrf", "mmr", "temporal")
     * @type {RerankerAdjustmentStepEnum}
     * @memberof RerankerAdjustment
     */
    step?: RerankerAdjustmentStepEnum;
}


/**
 * @export
 */
export const RerankerAdjustmentStepEnum = {
    Rrf: 'rrf',
    Mmr: 'mmr',
    Temporal: 'temporal'
} as const;
export type RerankerAdjustmentStepEnum = typeof RerankerAdjustmentStepEnum[keyof typeof RerankerAdjustmentStepEnum];


/**
 * Check if a given object implements the RerankerAdjustment interface.
 */
export function instanceOfRerankerAdjustment(value: object): value is RerankerAdjustment {
    return true;
}

export function RerankerAdjustmentFromJSON(json: any): RerankerAdjustment {
    return RerankerAdjustmentFromJSONTyped(json, false);
}

export function RerankerAdjustmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RerankerAdjustment {
    if (json == null) {
        return json;
    }
    return {
        
        'ageDays': json['age_days'] == null ? undefined : json['age_days'],
        'decayFactor': json['decay_factor'] == null ? undefined : json['decay_factor'],
        'rankAfter': json['rank_after'] == null ? undefined : json['rank_after'],
        'rankBefore': json['rank_before'] == null ? undefined : json['rank_before'],
        'scoreDelta': json['score_delta'] == null ? undefined : json['score_delta'],
        'step': json['step'] == null ? undefined : json['step'],
    };
}

export function RerankerAdjustmentToJSON(json: any): RerankerAdjustment {
    return RerankerAdjustmentToJSONTyped(json, false);
}

export function RerankerAdjustmentToJSONTyped(value?: RerankerAdjustment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'age_days': value['ageDays'],
        'decay_factor': value['decayFactor'],
        'rank_after': value['rankAfter'],
        'rank_before': value['rankBefore'],
        'score_delta': value['scoreDelta'],
        'step': value['step'],
    };
}

