/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RerankerOptions
 */
export interface RerankerOptions {
    /**
     * MMRLambda is the MMR diversity parameter: 0.0 = maximum diversity, 1.0 = pure relevance. Validated
     * (0.0 to 1.0) by Validate when Type is mmr; other types store the value without validating it. Defaults to
     * 0.5 (the built-in services.search.mmr_lambda) when the key is absent. Not read by the pipeline yet
     * (roadmap TD48).
     * @type {number}
     * @memberof RerankerOptions
     */
    mmrLambda?: number;
    /**
     * RRFK is the reciprocal rank fusion constant. Validated (0 to 1000) by Validate when Type is rrf or
     * rrf_temporal; other types store the value without validating it. Defaults to 60 (the built-in
     * services.search.rrf_k) when the key is absent; an explicit 0 is kept. Not read by the pipeline yet
     * (roadmap TD47).
     * @type {number}
     * @memberof RerankerOptions
     */
    rrfK?: number;
    /**
     * Type specifies the reranker algorithm: rrf, rrf_temporal, mmr, temporal, node_distance, cross_encoder.
     * The tag default (cross_encoder) applies when a stored config has no type; new apps are written with
     * the system value services.search.reranker_type.
     * @type {RerankerOptionsTypeEnum}
     * @memberof RerankerOptions
     */
    type?: RerankerOptionsTypeEnum;
}


/**
 * @export
 */
export const RerankerOptionsTypeEnum = {
    Rrf: 'rrf',
    RrfTemporal: 'rrf_temporal',
    Mmr: 'mmr',
    Temporal: 'temporal',
    NodeDistance: 'node_distance',
    CrossEncoder: 'cross_encoder'
} as const;
export type RerankerOptionsTypeEnum = typeof RerankerOptionsTypeEnum[keyof typeof RerankerOptionsTypeEnum];


/**
 * Check if a given object implements the RerankerOptions interface.
 */
export function instanceOfRerankerOptions(value: object): value is RerankerOptions {
    return true;
}

export function RerankerOptionsFromJSON(json: any): RerankerOptions {
    return RerankerOptionsFromJSONTyped(json, false);
}

export function RerankerOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RerankerOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'mmrLambda': json['mmr_lambda'] == null ? undefined : json['mmr_lambda'],
        'rrfK': json['rrf_k'] == null ? undefined : json['rrf_k'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function RerankerOptionsToJSON(json: any): RerankerOptions {
    return RerankerOptionsToJSONTyped(json, false);
}

export function RerankerOptionsToJSONTyped(value?: RerankerOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mmr_lambda': value['mmrLambda'],
        'rrf_k': value['rrfK'],
        'type': value['type'],
    };
}

