/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RerankerConfigUsed
 */
export interface RerankerConfigUsed {
    /**
     * K is the RRF constant (for RRF reranker)
     * @type {number}
     * @memberof RerankerConfigUsed
     */
    k?: number;
    /**
     * Lambda is the diversity parameter (for MMR reranker)
     * @type {number}
     * @memberof RerankerConfigUsed
     */
    lambda?: number;
    /**
     * Type is the reranker algorithm (none, rrf, mmr, temporal, etc.)
     * @type {RerankerConfigUsedTypeEnum}
     * @memberof RerankerConfigUsed
     */
    type?: RerankerConfigUsedTypeEnum;
}


/**
 * @export
 */
export const RerankerConfigUsedTypeEnum = {
    None: 'none',
    Rrf: 'rrf',
    Mmr: 'mmr',
    Temporal: 'temporal'
} as const;
export type RerankerConfigUsedTypeEnum = typeof RerankerConfigUsedTypeEnum[keyof typeof RerankerConfigUsedTypeEnum];


/**
 * Check if a given object implements the RerankerConfigUsed interface.
 */
export function instanceOfRerankerConfigUsed(value: object): value is RerankerConfigUsed {
    return true;
}

export function RerankerConfigUsedFromJSON(json: any): RerankerConfigUsed {
    return RerankerConfigUsedFromJSONTyped(json, false);
}

export function RerankerConfigUsedFromJSONTyped(json: any, ignoreDiscriminator: boolean): RerankerConfigUsed {
    if (json == null) {
        return json;
    }
    return {
        
        'k': json['k'] == null ? undefined : json['k'],
        'lambda': json['lambda'] == null ? undefined : json['lambda'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function RerankerConfigUsedToJSON(json: any): RerankerConfigUsed {
    return RerankerConfigUsedToJSONTyped(json, false);
}

export function RerankerConfigUsedToJSONTyped(value?: RerankerConfigUsed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'k': value['k'],
        'lambda': value['lambda'],
        'type': value['type'],
    };
}

