/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetPasswordRequestRequest
 */
export interface ResetPasswordRequestRequest {
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordRequestRequest
     */
    email: string;
}

/**
 * Check if a given object implements the ResetPasswordRequestRequest interface.
 */
export function instanceOfResetPasswordRequestRequest(value: object): value is ResetPasswordRequestRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ResetPasswordRequestRequestFromJSON(json: any): ResetPasswordRequestRequest {
    return ResetPasswordRequestRequestFromJSONTyped(json, false);
}

export function ResetPasswordRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetPasswordRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ResetPasswordRequestRequestToJSON(json: any): ResetPasswordRequestRequest {
    return ResetPasswordRequestRequestToJSONTyped(json, false);
}

export function ResetPasswordRequestRequestToJSONTyped(value?: ResetPasswordRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

