/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RevenueByPlanEntry
 */
export interface RevenueByPlanEntry {
    /**
     * 
     * @type {number}
     * @memberof RevenueByPlanEntry
     */
    activeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof RevenueByPlanEntry
     */
    mrrMinor?: number;
    /**
     * 
     * @type {string}
     * @memberof RevenueByPlanEntry
     */
    planKey?: string;
    /**
     * 
     * @type {string}
     * @memberof RevenueByPlanEntry
     */
    planName?: string;
}

/**
 * Check if a given object implements the RevenueByPlanEntry interface.
 */
export function instanceOfRevenueByPlanEntry(value: object): value is RevenueByPlanEntry {
    return true;
}

export function RevenueByPlanEntryFromJSON(json: any): RevenueByPlanEntry {
    return RevenueByPlanEntryFromJSONTyped(json, false);
}

export function RevenueByPlanEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RevenueByPlanEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'activeCount': json['active_count'] == null ? undefined : json['active_count'],
        'mrrMinor': json['mrr_minor'] == null ? undefined : json['mrr_minor'],
        'planKey': json['plan_key'] == null ? undefined : json['plan_key'],
        'planName': json['plan_name'] == null ? undefined : json['plan_name'],
    };
}

export function RevenueByPlanEntryToJSON(json: any): RevenueByPlanEntry {
    return RevenueByPlanEntryToJSONTyped(json, false);
}

export function RevenueByPlanEntryToJSONTyped(value?: RevenueByPlanEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_count': value['activeCount'],
        'mrr_minor': value['mrrMinor'],
        'plan_key': value['planKey'],
        'plan_name': value['planName'],
    };
}

