/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateAppRequest } from './UpdateAppRequest';
import {
    UpdateAppRequestFromJSON,
    UpdateAppRequestFromJSONTyped,
    UpdateAppRequestToJSON,
    UpdateAppRequestToJSONTyped,
} from './UpdateAppRequest';

/**
 * 
 * @export
 * @interface SaveDraftRequest
 */
export interface SaveDraftRequest {
    /**
     * 
     * @type {UpdateAppRequest}
     * @memberof SaveDraftRequest
     */
    config: UpdateAppRequest;
    /**
     * 
     * @type {string}
     * @memberof SaveDraftRequest
     */
    dataPlaneId?: string;
    /**
     * 
     * @type {number}
     * @memberof SaveDraftRequest
     */
    version?: number;
}

/**
 * Check if a given object implements the SaveDraftRequest interface.
 */
export function instanceOfSaveDraftRequest(value: object): value is SaveDraftRequest {
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function SaveDraftRequestFromJSON(json: any): SaveDraftRequest {
    return SaveDraftRequestFromJSONTyped(json, false);
}

export function SaveDraftRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveDraftRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': UpdateAppRequestFromJSON(json['config']),
        'dataPlaneId': json['data_plane_id'] == null ? undefined : json['data_plane_id'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function SaveDraftRequestToJSON(json: any): SaveDraftRequest {
    return SaveDraftRequestToJSONTyped(json, false);
}

export function SaveDraftRequestToJSONTyped(value?: SaveDraftRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': UpdateAppRequestToJSON(value['config']),
        'data_plane_id': value['dataPlaneId'],
        'version': value['version'],
    };
}

