/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RelationshipDef } from './RelationshipDef';
import {
    RelationshipDefFromJSON,
    RelationshipDefFromJSONTyped,
    RelationshipDefToJSON,
    RelationshipDefToJSONTyped,
} from './RelationshipDef';
import type { EntityDef } from './EntityDef';
import {
    EntityDefFromJSON,
    EntityDefFromJSONTyped,
    EntityDefToJSON,
    EntityDefToJSONTyped,
} from './EntityDef';

/**
 * 
 * @export
 * @interface SchemaDefaultsResponse
 */
export interface SchemaDefaultsResponse {
    /**
     * EntityTypes are the base entity-type definitions (type identifier + human description).
     * @type {Array<EntityDef>}
     * @memberof SchemaDefaultsResponse
     */
    entityTypes?: Array<EntityDef>;
    /**
     * RelationshipTypes are the base relationship-type definitions (type identifier + human
     * description; From/To are empty for base types — the UI draws no default edges from them).
     * @type {Array<RelationshipDef>}
     * @memberof SchemaDefaultsResponse
     */
    relationshipTypes?: Array<RelationshipDef>;
}

/**
 * Check if a given object implements the SchemaDefaultsResponse interface.
 */
export function instanceOfSchemaDefaultsResponse(value: object): value is SchemaDefaultsResponse {
    return true;
}

export function SchemaDefaultsResponseFromJSON(json: any): SchemaDefaultsResponse {
    return SchemaDefaultsResponseFromJSONTyped(json, false);
}

export function SchemaDefaultsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaDefaultsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entityTypes': json['entity_types'] == null ? undefined : ((json['entity_types'] as Array<any>).map(EntityDefFromJSON)),
        'relationshipTypes': json['relationship_types'] == null ? undefined : ((json['relationship_types'] as Array<any>).map(RelationshipDefFromJSON)),
    };
}

export function SchemaDefaultsResponseToJSON(json: any): SchemaDefaultsResponse {
    return SchemaDefaultsResponseToJSONTyped(json, false);
}

export function SchemaDefaultsResponseToJSONTyped(value?: SchemaDefaultsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity_types': value['entityTypes'] == null ? undefined : ((value['entityTypes'] as Array<any>).map(EntityDefToJSON)),
        'relationship_types': value['relationshipTypes'] == null ? undefined : ((value['relationshipTypes'] as Array<any>).map(RelationshipDefToJSON)),
    };
}

