/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemaDefaultsResponse
 */
export interface SchemaDefaultsResponse {
    /**
     * EntityTypes contains all base entity type identifiers (e.g., "person", "organization").
     * @type {Array<string>}
     * @memberof SchemaDefaultsResponse
     */
    entityTypes?: Array<string>;
    /**
     * RelationshipTypes contains all base relationship type identifiers (e.g., "works_for", "knows").
     * @type {Array<string>}
     * @memberof SchemaDefaultsResponse
     */
    relationshipTypes?: Array<string>;
}

/**
 * Check if a given object implements the SchemaDefaultsResponse interface.
 */
export function instanceOfSchemaDefaultsResponse(value: object): value is SchemaDefaultsResponse {
    return true;
}

export function SchemaDefaultsResponseFromJSON(json: any): SchemaDefaultsResponse {
    return SchemaDefaultsResponseFromJSONTyped(json, false);
}

export function SchemaDefaultsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaDefaultsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entityTypes': json['entity_types'] == null ? undefined : json['entity_types'],
        'relationshipTypes': json['relationship_types'] == null ? undefined : json['relationship_types'],
    };
}

export function SchemaDefaultsResponseToJSON(json: any): SchemaDefaultsResponse {
    return SchemaDefaultsResponseToJSONTyped(json, false);
}

export function SchemaDefaultsResponseToJSONTyped(value?: SchemaDefaultsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity_types': value['entityTypes'],
        'relationship_types': value['relationshipTypes'],
    };
}

