/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchMethodInfo
 */
export interface SearchMethodInfo {
    /**
     * AvgLatencyMs is the typical execution time in milliseconds
     * @type {number}
     * @memberof SearchMethodInfo
     */
    avgLatencyMs?: number;
    /**
     * Description explains what the method does and when to use it
     * @type {string}
     * @memberof SearchMethodInfo
     */
    description?: string;
    /**
     * DisplayName is the human-readable name for UI display
     * @type {string}
     * @memberof SearchMethodInfo
     */
    displayName?: string;
    /**
     * Name is the method identifier used in API requests (e.g., "quick", "deep")
     * @type {string}
     * @memberof SearchMethodInfo
     */
    name?: string;
    /**
     * RecommendedFor lists use cases where this method excels
     * @type {Array<string>}
     * @memberof SearchMethodInfo
     */
    recommendedFor?: Array<string>;
    /**
     * SupportsBM25 indicates if the method uses BM25 keyword matching
     * @type {boolean}
     * @memberof SearchMethodInfo
     */
    supportsBm25?: boolean;
    /**
     * SupportsGraph indicates if the method uses knowledge graph traversal
     * @type {boolean}
     * @memberof SearchMethodInfo
     */
    supportsGraph?: boolean;
}

/**
 * Check if a given object implements the SearchMethodInfo interface.
 */
export function instanceOfSearchMethodInfo(value: object): value is SearchMethodInfo {
    return true;
}

export function SearchMethodInfoFromJSON(json: any): SearchMethodInfo {
    return SearchMethodInfoFromJSONTyped(json, false);
}

export function SearchMethodInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchMethodInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'avgLatencyMs': json['avg_latency_ms'] == null ? undefined : json['avg_latency_ms'],
        'description': json['description'] == null ? undefined : json['description'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'name': json['name'] == null ? undefined : json['name'],
        'recommendedFor': json['recommended_for'] == null ? undefined : json['recommended_for'],
        'supportsBm25': json['supports_bm25'] == null ? undefined : json['supports_bm25'],
        'supportsGraph': json['supports_graph'] == null ? undefined : json['supports_graph'],
    };
}

export function SearchMethodInfoToJSON(json: any): SearchMethodInfo {
    return SearchMethodInfoToJSONTyped(json, false);
}

export function SearchMethodInfoToJSONTyped(value?: SearchMethodInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avg_latency_ms': value['avgLatencyMs'],
        'description': value['description'],
        'display_name': value['displayName'],
        'name': value['name'],
        'recommended_for': value['recommendedFor'],
        'supports_bm25': value['supportsBm25'],
        'supports_graph': value['supportsGraph'],
    };
}

