/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetGrandfatherRequest
 */
export interface SetGrandfatherRequest {
    /**
     * 
     * @type {SetGrandfatherRequestModeEnum}
     * @memberof SetGrandfatherRequest
     */
    mode: SetGrandfatherRequestModeEnum;
    /**
     * 
     * @type {string}
     * @memberof SetGrandfatherRequest
     */
    reason?: string;
    /**
     * RFC3339; required when Mode=LOCK_UNTIL
     * @type {string}
     * @memberof SetGrandfatherRequest
     */
    until?: string;
}


/**
 * @export
 */
export const SetGrandfatherRequestModeEnum = {
    NoOverride: 'NO_OVERRIDE',
    LockUntil: 'LOCK_UNTIL',
    LockIndefinite: 'LOCK_INDEFINITE'
} as const;
export type SetGrandfatherRequestModeEnum = typeof SetGrandfatherRequestModeEnum[keyof typeof SetGrandfatherRequestModeEnum];


/**
 * Check if a given object implements the SetGrandfatherRequest interface.
 */
export function instanceOfSetGrandfatherRequest(value: object): value is SetGrandfatherRequest {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function SetGrandfatherRequestFromJSON(json: any): SetGrandfatherRequest {
    return SetGrandfatherRequestFromJSONTyped(json, false);
}

export function SetGrandfatherRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetGrandfatherRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'until': json['until'] == null ? undefined : json['until'],
    };
}

export function SetGrandfatherRequestToJSON(json: any): SetGrandfatherRequest {
    return SetGrandfatherRequestToJSONTyped(json, false);
}

export function SetGrandfatherRequestToJSONTyped(value?: SetGrandfatherRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'reason': value['reason'],
        'until': value['until'],
    };
}

