/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SourceWeightsConfig
 */
export interface SourceWeightsConfig {
    /**
     * EntitySeedWeight is the weight for entity-based search results
     * @type {number}
     * @memberof SourceWeightsConfig
     */
    entitySeedWeight?: number;
    /**
     * GraphExpandedWeight is the weight for graph-expanded results
     * @type {number}
     * @memberof SourceWeightsConfig
     */
    graphExpandedWeight?: number;
    /**
     * LLMSeedWeight is the weight for LLM-extracted entity results
     * @type {number}
     * @memberof SourceWeightsConfig
     */
    llmSeedWeight?: number;
    /**
     * RelationshipSeedWeight is the weight for relationship-based search results
     * @type {number}
     * @memberof SourceWeightsConfig
     */
    relationshipSeedWeight?: number;
}

/**
 * Check if a given object implements the SourceWeightsConfig interface.
 */
export function instanceOfSourceWeightsConfig(value: object): value is SourceWeightsConfig {
    return true;
}

export function SourceWeightsConfigFromJSON(json: any): SourceWeightsConfig {
    return SourceWeightsConfigFromJSONTyped(json, false);
}

export function SourceWeightsConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceWeightsConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'entitySeedWeight': json['entity_seed_weight'] == null ? undefined : json['entity_seed_weight'],
        'graphExpandedWeight': json['graph_expanded_weight'] == null ? undefined : json['graph_expanded_weight'],
        'llmSeedWeight': json['llm_seed_weight'] == null ? undefined : json['llm_seed_weight'],
        'relationshipSeedWeight': json['relationship_seed_weight'] == null ? undefined : json['relationship_seed_weight'],
    };
}

export function SourceWeightsConfigToJSON(json: any): SourceWeightsConfig {
    return SourceWeightsConfigToJSONTyped(json, false);
}

export function SourceWeightsConfigToJSONTyped(value?: SourceWeightsConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity_seed_weight': value['entitySeedWeight'],
        'graph_expanded_weight': value['graphExpandedWeight'],
        'llm_seed_weight': value['llmSeedWeight'],
        'relationship_seed_weight': value['relationshipSeedWeight'],
    };
}

