/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudioAuditEntryResponse
 */
export interface StudioAuditEntryResponse {
    /**
     * 
     * @type {string}
     * @memberof StudioAuditEntryResponse
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof StudioAuditEntryResponse
     */
    actorId?: string;
    /**
     * 
     * @type {string}
     * @memberof StudioAuditEntryResponse
     */
    appId?: string;
    /**
     * 
     * @type {string}
     * @memberof StudioAuditEntryResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof StudioAuditEntryResponse
     */
    details?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof StudioAuditEntryResponse
     */
    errorMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof StudioAuditEntryResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof StudioAuditEntryResponse
     */
    orgId?: string;
    /**
     * 
     * @type {string}
     * @memberof StudioAuditEntryResponse
     */
    requestId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof StudioAuditEntryResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the StudioAuditEntryResponse interface.
 */
export function instanceOfStudioAuditEntryResponse(value: object): value is StudioAuditEntryResponse {
    return true;
}

export function StudioAuditEntryResponseFromJSON(json: any): StudioAuditEntryResponse {
    return StudioAuditEntryResponseFromJSONTyped(json, false);
}

export function StudioAuditEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudioAuditEntryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'actorId': json['actor_id'] == null ? undefined : json['actor_id'],
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'details': json['details'] == null ? undefined : json['details'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'id': json['id'] == null ? undefined : json['id'],
        'orgId': json['org_id'] == null ? undefined : json['org_id'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function StudioAuditEntryResponseToJSON(json: any): StudioAuditEntryResponse {
    return StudioAuditEntryResponseToJSONTyped(json, false);
}

export function StudioAuditEntryResponseToJSONTyped(value?: StudioAuditEntryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'actor_id': value['actorId'],
        'app_id': value['appId'],
        'created_at': value['createdAt'],
        'details': value['details'],
        'error_message': value['errorMessage'],
        'id': value['id'],
        'org_id': value['orgId'],
        'request_id': value['requestId'],
        'success': value['success'],
    };
}

