/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionView
 */
export interface SubscriptionView {
    /**
     * 
     * @type {number}
     * @memberof SubscriptionView
     */
    amountMinor?: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    authLink?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    authSessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    billingCycle?: string;
    /**
     * RFC3339
     * @type {string}
     * @memberof SubscriptionView
     */
    cancelAt?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    environment?: string;
    /**
     * IsTerminal is true when the subscription is in a dead/terminal state (CANCELLED, EXPIRED, COMPLETED,
     * HALTED). A terminal record does not occupy the org's one-active slot; the UI treats it as "no live
     * subscription" (buy path available) and never shows manage/authorize actions for it.
     * @type {boolean}
     * @memberof SubscriptionView
     */
    isTerminal?: boolean;
    /**
     * NeedsAuthorization is true for any live (non-terminal) subscription that still owes a card
     * authorization. That covers TWO cases: (a) a first-time mandate awaiting authorization (status
     * PENDING_AUTH or AUTHENTICATED) carrying a usable auth session, and (b) an ACTIVE subscription
     * with a re-auth/upgrade mandate parked on it (pending_subscription_id set) carrying a usable
     * pending auth session. It drives the Authorize CTA and the post-payment auto-redirect; it is
     * never true for a terminal record.
     * @type {boolean}
     * @memberof SubscriptionView
     */
    needsAuthorization?: boolean;
    /**
     * RFC3339
     * @type {string}
     * @memberof SubscriptionView
     */
    nextChargeDate?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    orgId?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    orgName?: string;
    /**
     * PendingAuthLink and PendingAuthSessionID belong to the PARKED pending mandate (the new mandate
     * created for a re-authorization or an upgrade), not to the currently active one. When
     * NeedsAuthorization is true because of a parked pending mandate, the UI must send the customer to
     * THESE, not to AuthLink/AuthSessionID — those still point at the old, already-authorized mandate.
     * @type {string}
     * @memberof SubscriptionView
     */
    pendingAuthLink?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    pendingAuthSessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    pendingEffectiveAt?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    pendingPlanKey?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    pendingPlanName?: string;
    /**
     * PendingRequiresAuthorization distinguishes the TWO kinds of pending plan change that
     * PendingPlanKey/PendingPlanName describe. False means a CYCLE-END scheduled change: nothing is owed,
     * the customer keeps the current plan until PendingEffectiveAt and the new plan starts then. True means
     * an IN-FLIGHT change that is waiting on a card authorization (a new mandate is parked on the row);
     * it has no scheduled date and will not apply until the customer authorizes. The UI must render
     * different copy for each, so this is projected explicitly rather than inferred.
     * @type {boolean}
     * @memberof SubscriptionView
     */
    pendingRequiresAuthorization?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    planKey?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    planName?: string;
    /**
     * PriceUnavailable is true when the plan's price could not be resolved for the subscription's
     * frozen (billing_cycle, country) — the UI must show an explicit error, never a silent ₹0.
     * @type {boolean}
     * @memberof SubscriptionView
     */
    priceUnavailable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    providerSubscriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionView
     */
    subscriptionId?: string;
}

/**
 * Check if a given object implements the SubscriptionView interface.
 */
export function instanceOfSubscriptionView(value: object): value is SubscriptionView {
    return true;
}

export function SubscriptionViewFromJSON(json: any): SubscriptionView {
    return SubscriptionViewFromJSONTyped(json, false);
}

export function SubscriptionViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionView {
    if (json == null) {
        return json;
    }
    return {
        
        'amountMinor': json['amount_minor'] == null ? undefined : json['amount_minor'],
        'authLink': json['auth_link'] == null ? undefined : json['auth_link'],
        'authSessionId': json['auth_session_id'] == null ? undefined : json['auth_session_id'],
        'billingCycle': json['billing_cycle'] == null ? undefined : json['billing_cycle'],
        'cancelAt': json['cancel_at'] == null ? undefined : json['cancel_at'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'environment': json['environment'] == null ? undefined : json['environment'],
        'isTerminal': json['is_terminal'] == null ? undefined : json['is_terminal'],
        'needsAuthorization': json['needs_authorization'] == null ? undefined : json['needs_authorization'],
        'nextChargeDate': json['next_charge_date'] == null ? undefined : json['next_charge_date'],
        'orgId': json['org_id'] == null ? undefined : json['org_id'],
        'orgName': json['org_name'] == null ? undefined : json['org_name'],
        'pendingAuthLink': json['pending_auth_link'] == null ? undefined : json['pending_auth_link'],
        'pendingAuthSessionId': json['pending_auth_session_id'] == null ? undefined : json['pending_auth_session_id'],
        'pendingEffectiveAt': json['pending_effective_at'] == null ? undefined : json['pending_effective_at'],
        'pendingPlanKey': json['pending_plan_key'] == null ? undefined : json['pending_plan_key'],
        'pendingPlanName': json['pending_plan_name'] == null ? undefined : json['pending_plan_name'],
        'pendingRequiresAuthorization': json['pending_requires_authorization'] == null ? undefined : json['pending_requires_authorization'],
        'planKey': json['plan_key'] == null ? undefined : json['plan_key'],
        'planName': json['plan_name'] == null ? undefined : json['plan_name'],
        'priceUnavailable': json['price_unavailable'] == null ? undefined : json['price_unavailable'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'providerSubscriptionId': json['provider_subscription_id'] == null ? undefined : json['provider_subscription_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'subscriptionId': json['subscription_id'] == null ? undefined : json['subscription_id'],
    };
}

export function SubscriptionViewToJSON(json: any): SubscriptionView {
    return SubscriptionViewToJSONTyped(json, false);
}

export function SubscriptionViewToJSONTyped(value?: SubscriptionView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_minor': value['amountMinor'],
        'auth_link': value['authLink'],
        'auth_session_id': value['authSessionId'],
        'billing_cycle': value['billingCycle'],
        'cancel_at': value['cancelAt'],
        'currency': value['currency'],
        'environment': value['environment'],
        'is_terminal': value['isTerminal'],
        'needs_authorization': value['needsAuthorization'],
        'next_charge_date': value['nextChargeDate'],
        'org_id': value['orgId'],
        'org_name': value['orgName'],
        'pending_auth_link': value['pendingAuthLink'],
        'pending_auth_session_id': value['pendingAuthSessionId'],
        'pending_effective_at': value['pendingEffectiveAt'],
        'pending_plan_key': value['pendingPlanKey'],
        'pending_plan_name': value['pendingPlanName'],
        'pending_requires_authorization': value['pendingRequiresAuthorization'],
        'plan_key': value['planKey'],
        'plan_name': value['planName'],
        'price_unavailable': value['priceUnavailable'],
        'provider': value['provider'],
        'provider_subscription_id': value['providerSubscriptionId'],
        'status': value['status'],
        'subscription_id': value['subscriptionId'],
    };
}

