/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionFlowSeriesPoint
 */
export interface SubscriptionFlowSeriesPoint {
    /**
     * 
     * @type {number}
     * @memberof SubscriptionFlowSeriesPoint
     */
    churnedCount?: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionFlowSeriesPoint
     */
    date?: string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionFlowSeriesPoint
     */
    newCount?: number;
}

/**
 * Check if a given object implements the SubscriptionFlowSeriesPoint interface.
 */
export function instanceOfSubscriptionFlowSeriesPoint(value: object): value is SubscriptionFlowSeriesPoint {
    return true;
}

export function SubscriptionFlowSeriesPointFromJSON(json: any): SubscriptionFlowSeriesPoint {
    return SubscriptionFlowSeriesPointFromJSONTyped(json, false);
}

export function SubscriptionFlowSeriesPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionFlowSeriesPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'churnedCount': json['churned_count'] == null ? undefined : json['churned_count'],
        'date': json['date'] == null ? undefined : json['date'],
        'newCount': json['new_count'] == null ? undefined : json['new_count'],
    };
}

export function SubscriptionFlowSeriesPointToJSON(json: any): SubscriptionFlowSeriesPoint {
    return SubscriptionFlowSeriesPointToJSONTyped(json, false);
}

export function SubscriptionFlowSeriesPointToJSONTyped(value?: SubscriptionFlowSeriesPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'churned_count': value['churnedCount'],
        'date': value['date'],
        'new_count': value['newCount'],
    };
}

