/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncOutboxStatsResponse
 */
export interface SyncOutboxStatsResponse {
    /**
     * 
     * @type {number}
     * @memberof SyncOutboxStatsResponse
     */
    completed?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncOutboxStatsResponse
     */
    dead?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncOutboxStatsResponse
     */
    pending?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncOutboxStatsResponse
     */
    processing?: number;
}

/**
 * Check if a given object implements the SyncOutboxStatsResponse interface.
 */
export function instanceOfSyncOutboxStatsResponse(value: object): value is SyncOutboxStatsResponse {
    return true;
}

export function SyncOutboxStatsResponseFromJSON(json: any): SyncOutboxStatsResponse {
    return SyncOutboxStatsResponseFromJSONTyped(json, false);
}

export function SyncOutboxStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncOutboxStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'completed': json['completed'] == null ? undefined : json['completed'],
        'dead': json['dead'] == null ? undefined : json['dead'],
        'pending': json['pending'] == null ? undefined : json['pending'],
        'processing': json['processing'] == null ? undefined : json['processing'],
    };
}

export function SyncOutboxStatsResponseToJSON(json: any): SyncOutboxStatsResponse {
    return SyncOutboxStatsResponseToJSONTyped(json, false);
}

export function SyncOutboxStatsResponseToJSONTyped(value?: SyncOutboxStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed': value['completed'],
        'dead': value['dead'],
        'pending': value['pending'],
        'processing': value['processing'],
    };
}

