/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncOutboxEntryResponse
 */
export interface SyncOutboxEntryResponse {
    /**
     * 
     * @type {string}
     * @memberof SyncOutboxEntryResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncOutboxEntryResponse
     */
    entityKey?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncOutboxEntryResponse
     */
    entityType?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncOutboxEntryResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncOutboxEntryResponse
     */
    lastError?: string;
    /**
     * 
     * @type {number}
     * @memberof SyncOutboxEntryResponse
     */
    maxRetries?: number;
    /**
     * 
     * @type {string}
     * @memberof SyncOutboxEntryResponse
     */
    operation?: string;
    /**
     * 
     * @type {number}
     * @memberof SyncOutboxEntryResponse
     */
    retryCount?: number;
    /**
     * 
     * @type {string}
     * @memberof SyncOutboxEntryResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncOutboxEntryResponse
     */
    targetPlaneUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncOutboxEntryResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the SyncOutboxEntryResponse interface.
 */
export function instanceOfSyncOutboxEntryResponse(value: object): value is SyncOutboxEntryResponse {
    return true;
}

export function SyncOutboxEntryResponseFromJSON(json: any): SyncOutboxEntryResponse {
    return SyncOutboxEntryResponseFromJSONTyped(json, false);
}

export function SyncOutboxEntryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncOutboxEntryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'entityKey': json['entity_key'] == null ? undefined : json['entity_key'],
        'entityType': json['entity_type'] == null ? undefined : json['entity_type'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastError': json['last_error'] == null ? undefined : json['last_error'],
        'maxRetries': json['max_retries'] == null ? undefined : json['max_retries'],
        'operation': json['operation'] == null ? undefined : json['operation'],
        'retryCount': json['retry_count'] == null ? undefined : json['retry_count'],
        'status': json['status'] == null ? undefined : json['status'],
        'targetPlaneUrl': json['target_plane_url'] == null ? undefined : json['target_plane_url'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function SyncOutboxEntryResponseToJSON(json: any): SyncOutboxEntryResponse {
    return SyncOutboxEntryResponseToJSONTyped(json, false);
}

export function SyncOutboxEntryResponseToJSONTyped(value?: SyncOutboxEntryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'entity_key': value['entityKey'],
        'entity_type': value['entityType'],
        'id': value['id'],
        'last_error': value['lastError'],
        'max_retries': value['maxRetries'],
        'operation': value['operation'],
        'retry_count': value['retryCount'],
        'status': value['status'],
        'target_plane_url': value['targetPlaneUrl'],
        'updated_at': value['updatedAt'],
    };
}

