/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SyncOutboxEntryResponse } from './SyncOutboxEntryResponse';
import {
    SyncOutboxEntryResponseFromJSON,
    SyncOutboxEntryResponseFromJSONTyped,
    SyncOutboxEntryResponseToJSON,
    SyncOutboxEntryResponseToJSONTyped,
} from './SyncOutboxEntryResponse';

/**
 * 
 * @export
 * @interface SyncOutboxListResponse
 */
export interface SyncOutboxListResponse {
    /**
     * 
     * @type {Array<SyncOutboxEntryResponse>}
     * @memberof SyncOutboxListResponse
     */
    entries?: Array<SyncOutboxEntryResponse>;
    /**
     * 
     * @type {number}
     * @memberof SyncOutboxListResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncOutboxListResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof SyncOutboxListResponse
     */
    total?: number;
}

/**
 * Check if a given object implements the SyncOutboxListResponse interface.
 */
export function instanceOfSyncOutboxListResponse(value: object): value is SyncOutboxListResponse {
    return true;
}

export function SyncOutboxListResponseFromJSON(json: any): SyncOutboxListResponse {
    return SyncOutboxListResponseFromJSONTyped(json, false);
}

export function SyncOutboxListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncOutboxListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': json['entries'] == null ? undefined : ((json['entries'] as Array<any>).map(SyncOutboxEntryResponseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function SyncOutboxListResponseToJSON(json: any): SyncOutboxListResponse {
    return SyncOutboxListResponseToJSONTyped(json, false);
}

export function SyncOutboxListResponseToJSONTyped(value?: SyncOutboxListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entries': value['entries'] == null ? undefined : ((value['entries'] as Array<any>).map(SyncOutboxEntryResponseToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'total': value['total'],
    };
}

