/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SyncedPlanEntry } from './SyncedPlanEntry';
import {
    SyncedPlanEntryFromJSON,
    SyncedPlanEntryFromJSONTyped,
    SyncedPlanEntryToJSON,
    SyncedPlanEntryToJSONTyped,
} from './SyncedPlanEntry';

/**
 * 
 * @export
 * @interface SyncPlansResponse
 */
export interface SyncPlansResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof SyncPlansResponse
     */
    errors?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SyncPlansResponse
     */
    skipped?: number;
    /**
     * 
     * @type {Array<SyncedPlanEntry>}
     * @memberof SyncPlansResponse
     */
    synced?: Array<SyncedPlanEntry>;
}

/**
 * Check if a given object implements the SyncPlansResponse interface.
 */
export function instanceOfSyncPlansResponse(value: object): value is SyncPlansResponse {
    return true;
}

export function SyncPlansResponseFromJSON(json: any): SyncPlansResponse {
    return SyncPlansResponseFromJSONTyped(json, false);
}

export function SyncPlansResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncPlansResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'] == null ? undefined : json['errors'],
        'skipped': json['skipped'] == null ? undefined : json['skipped'],
        'synced': json['synced'] == null ? undefined : ((json['synced'] as Array<any>).map(SyncedPlanEntryFromJSON)),
    };
}

export function SyncPlansResponseToJSON(json: any): SyncPlansResponse {
    return SyncPlansResponseToJSONTyped(json, false);
}

export function SyncPlansResponseToJSONTyped(value?: SyncPlansResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': value['errors'],
        'skipped': value['skipped'],
        'synced': value['synced'] == null ? undefined : ((value['synced'] as Array<any>).map(SyncedPlanEntryToJSON)),
    };
}

