/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamMemberDetails
 */
export interface TeamMemberDetails {
    /**
     * 
     * @type {string}
     * @memberof TeamMemberDetails
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberDetails
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberDetails
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberDetails
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberDetails
     */
    organizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberDetails
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberDetails
     */
    teamId?: string;
    /**
     * 
     * @type {string}
     * @memberof TeamMemberDetails
     */
    userId?: string;
}

/**
 * Check if a given object implements the TeamMemberDetails interface.
 */
export function instanceOfTeamMemberDetails(value: object): value is TeamMemberDetails {
    return true;
}

export function TeamMemberDetailsFromJSON(json: any): TeamMemberDetails {
    return TeamMemberDetailsFromJSONTyped(json, false);
}

export function TeamMemberDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamMemberDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'organizationId': json['organization_id'] == null ? undefined : json['organization_id'],
        'role': json['role'] == null ? undefined : json['role'],
        'teamId': json['team_id'] == null ? undefined : json['team_id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function TeamMemberDetailsToJSON(json: any): TeamMemberDetails {
    return TeamMemberDetailsToJSONTyped(json, false);
}

export function TeamMemberDetailsToJSONTyped(value?: TeamMemberDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'email': value['email'],
        'id': value['id'],
        'name': value['name'],
        'organization_id': value['organizationId'],
        'role': value['role'],
        'team_id': value['teamId'],
        'user_id': value['userId'],
    };
}

