/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TeamInvitationStatus = {
    TeamInvitationStatusPending: 'pending',
    TeamInvitationStatusAccepted: 'accepted',
    TeamInvitationStatusRejected: 'rejected',
    TeamInvitationStatusCancelled: 'cancelled'
} as const;
export type TeamInvitationStatus = typeof TeamInvitationStatus[keyof typeof TeamInvitationStatus];


export function instanceOfTeamInvitationStatus(value: any): boolean {
    for (const key in TeamInvitationStatus) {
        if (Object.prototype.hasOwnProperty.call(TeamInvitationStatus, key)) {
            if (TeamInvitationStatus[key as keyof typeof TeamInvitationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TeamInvitationStatusFromJSON(json: any): TeamInvitationStatus {
    return TeamInvitationStatusFromJSONTyped(json, false);
}

export function TeamInvitationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamInvitationStatus {
    return json as TeamInvitationStatus;
}

export function TeamInvitationStatusToJSON(value?: TeamInvitationStatus | null): any {
    return value as any;
}

export function TeamInvitationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): TeamInvitationStatus {
    return value as TeamInvitationStatus;
}

