/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemporalFilter
 */
export interface TemporalFilter {
    /**
     * FromTime is the start of a time-range filter, RFC 3339. Returns memories whose validity period overlaps
     * [from_time, +inf): memories still valid at from_time or valid after it. Can be used alone (open-ended).
     * With ToTime the range is [from_time, to_time]. Cannot be combined with ValidAt.
     * @type {string}
     * @memberof TemporalFilter
     */
    fromTime?: string;
    /**
     * ToTime is the end of a time-range filter, RFC 3339 (inclusive). Returns memories whose validity period
     * overlaps (-inf, to_time]: memories that started on or before to_time. Can be used alone (open-ended).
     * With FromTime the range is [from_time, to_time] and from_time must be on or before to_time.
     * Cannot be combined with ValidAt.
     * @type {string}
     * @memberof TemporalFilter
     */
    toTime?: string;
    /**
     * ValidAt returns memories valid at exactly this moment (active_from <= valid_at and active_to empty or >= valid_at), RFC 3339.
     * Mutually exclusive with FromTime and ToTime.
     * @type {string}
     * @memberof TemporalFilter
     */
    validAt?: string;
}

/**
 * Check if a given object implements the TemporalFilter interface.
 */
export function instanceOfTemporalFilter(value: object): value is TemporalFilter {
    return true;
}

export function TemporalFilterFromJSON(json: any): TemporalFilter {
    return TemporalFilterFromJSONTyped(json, false);
}

export function TemporalFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemporalFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'fromTime': json['from_time'] == null ? undefined : json['from_time'],
        'toTime': json['to_time'] == null ? undefined : json['to_time'],
        'validAt': json['valid_at'] == null ? undefined : json['valid_at'],
    };
}

export function TemporalFilterToJSON(json: any): TemporalFilter {
    return TemporalFilterToJSONTyped(json, false);
}

export function TemporalFilterToJSONTyped(value?: TemporalFilter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from_time': value['fromTime'],
        'to_time': value['toTime'],
        'valid_at': value['validAt'],
    };
}

