/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemporalDecayConfig
 */
export interface TemporalDecayConfig {
    /**
     * Enabled toggles temporal decay (true by default)
     * @type {boolean}
     * @memberof TemporalDecayConfig
     */
    enabled?: boolean;
    /**
     * Lambda is the decay rate for exponential decay.
     * Higher values cause faster decay. Decay formula: exp(-lambda * age_days)
     * @type {number}
     * @memberof TemporalDecayConfig
     */
    lambda?: number;
    /**
     * MaxAgeDays ignores memories older than this threshold.
     * 0 means no maximum age limit.
     * @type {number}
     * @memberof TemporalDecayConfig
     */
    maxAgeDays?: number;
}

/**
 * Check if a given object implements the TemporalDecayConfig interface.
 */
export function instanceOfTemporalDecayConfig(value: object): value is TemporalDecayConfig {
    return true;
}

export function TemporalDecayConfigFromJSON(json: any): TemporalDecayConfig {
    return TemporalDecayConfigFromJSONTyped(json, false);
}

export function TemporalDecayConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemporalDecayConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'lambda': json['lambda'] == null ? undefined : json['lambda'],
        'maxAgeDays': json['max_age_days'] == null ? undefined : json['max_age_days'],
    };
}

export function TemporalDecayConfigToJSON(json: any): TemporalDecayConfig {
    return TemporalDecayConfigToJSONTyped(json, false);
}

export function TemporalDecayConfigToJSONTyped(value?: TemporalDecayConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'lambda': value['lambda'],
        'max_age_days': value['maxAgeDays'],
    };
}

