/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnlinkValidation
 */
export interface UnlinkValidation {
    /**
     * CanUnlink indicates whether the OAuth provider can be safely unlinked.
     * @type {boolean}
     * @memberof UnlinkValidation
     */
    canUnlink?: boolean;
    /**
     * Reason provides a human-readable explanation when CanUnlink is false.
     * Empty when CanUnlink is true.
     * @type {string}
     * @memberof UnlinkValidation
     */
    reason?: string;
}

/**
 * Check if a given object implements the UnlinkValidation interface.
 */
export function instanceOfUnlinkValidation(value: object): value is UnlinkValidation {
    return true;
}

export function UnlinkValidationFromJSON(json: any): UnlinkValidation {
    return UnlinkValidationFromJSONTyped(json, false);
}

export function UnlinkValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnlinkValidation {
    if (json == null) {
        return json;
    }
    return {
        
        'canUnlink': json['can_unlink'] == null ? undefined : json['can_unlink'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function UnlinkValidationToJSON(json: any): UnlinkValidation {
    return UnlinkValidationToJSONTyped(json, false);
}

export function UnlinkValidationToJSONTyped(value?: UnlinkValidation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'can_unlink': value['canUnlink'],
        'reason': value['reason'],
    };
}

