/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTeamRequest
 */
export interface UpdateTeamRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTeamRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the UpdateTeamRequest interface.
 */
export function instanceOfUpdateTeamRequest(value: object): value is UpdateTeamRequest {
    return true;
}

export function UpdateTeamRequestFromJSON(json: any): UpdateTeamRequest {
    return UpdateTeamRequestFromJSONTyped(json, false);
}

export function UpdateTeamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTeamRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function UpdateTeamRequestToJSON(json: any): UpdateTeamRequest {
    return UpdateTeamRequestToJSONTyped(json, false);
}

export function UpdateTeamRequestToJSONTyped(value?: UpdateTeamRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

