/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SourceWeightsConfig } from './SourceWeightsConfig';
import {
    SourceWeightsConfigFromJSON,
    SourceWeightsConfigFromJSONTyped,
    SourceWeightsConfigToJSON,
    SourceWeightsConfigToJSONTyped,
} from './SourceWeightsConfig';

/**
 * 
 * @export
 * @interface UpdateSourceWeightsResponse
 */
export interface UpdateSourceWeightsResponse {
    /**
     * AppID is the application identifier (UUID)
     * @type {string}
     * @memberof UpdateSourceWeightsResponse
     */
    appId?: string;
    /**
     * Message is a human-readable success message
     * @type {string}
     * @memberof UpdateSourceWeightsResponse
     */
    message?: string;
    /**
     * SourceWeights contains the updated source weight configuration
     * @type {SourceWeightsConfig}
     * @memberof UpdateSourceWeightsResponse
     */
    sourceWeights?: SourceWeightsConfig;
    /**
     * UpdatedAt is the timestamp of this update (ISO 8601)
     * @type {string}
     * @memberof UpdateSourceWeightsResponse
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the UpdateSourceWeightsResponse interface.
 */
export function instanceOfUpdateSourceWeightsResponse(value: object): value is UpdateSourceWeightsResponse {
    return true;
}

export function UpdateSourceWeightsResponseFromJSON(json: any): UpdateSourceWeightsResponse {
    return UpdateSourceWeightsResponseFromJSONTyped(json, false);
}

export function UpdateSourceWeightsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSourceWeightsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'message': json['message'] == null ? undefined : json['message'],
        'sourceWeights': json['source_weights'] == null ? undefined : SourceWeightsConfigFromJSON(json['source_weights']),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function UpdateSourceWeightsResponseToJSON(json: any): UpdateSourceWeightsResponse {
    return UpdateSourceWeightsResponseToJSONTyped(json, false);
}

export function UpdateSourceWeightsResponseToJSONTyped(value?: UpdateSourceWeightsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'message': value['message'],
        'source_weights': SourceWeightsConfigToJSON(value['sourceWeights']),
        'updated_at': value['updatedAt'],
    };
}

