/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRelationshipRequest
 */
export interface UpdateRelationshipRequest {
    /**
     * Fact is a natural language description of the relationship (optional)
     * @type {string}
     * @memberof UpdateRelationshipRequest
     */
    fact?: string;
    /**
     * Metadata contains flexible relationship metadata (optional)
     * @type {object}
     * @memberof UpdateRelationshipRequest
     */
    metadata?: object;
    /**
     * Name is a human-readable name for the relationship (optional)
     * @type {string}
     * @memberof UpdateRelationshipRequest
     */
    name?: string;
    /**
     * SourceEntityID is the source entity ID (optional for partial update)
     * @type {string}
     * @memberof UpdateRelationshipRequest
     */
    sourceEntityId?: string;
    /**
     * SourceMemoryIDs are memory IDs that contributed to this relationship (optional)
     * @type {Array<string>}
     * @memberof UpdateRelationshipRequest
     */
    sourceMemoryIds?: Array<string>;
    /**
     * TargetEntityID is the target entity ID (optional for partial update)
     * @type {string}
     * @memberof UpdateRelationshipRequest
     */
    targetEntityId?: string;
    /**
     * Type is the relationship type (optional for partial update)
     * @type {string}
     * @memberof UpdateRelationshipRequest
     */
    type?: string;
    /**
     * ValidFrom is the start of validity period (optional)
     * @type {string}
     * @memberof UpdateRelationshipRequest
     */
    validFrom?: string;
    /**
     * ValidTo is the end of validity period (optional)
     * @type {string}
     * @memberof UpdateRelationshipRequest
     */
    validTo?: string;
    /**
     * Weight is the relationship strength (optional, range 0-5)
     * @type {number}
     * @memberof UpdateRelationshipRequest
     */
    weight?: number;
}

/**
 * Check if a given object implements the UpdateRelationshipRequest interface.
 */
export function instanceOfUpdateRelationshipRequest(value: object): value is UpdateRelationshipRequest {
    return true;
}

export function UpdateRelationshipRequestFromJSON(json: any): UpdateRelationshipRequest {
    return UpdateRelationshipRequestFromJSONTyped(json, false);
}

export function UpdateRelationshipRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRelationshipRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fact': json['fact'] == null ? undefined : json['fact'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'] == null ? undefined : json['name'],
        'sourceEntityId': json['source_entity_id'] == null ? undefined : json['source_entity_id'],
        'sourceMemoryIds': json['source_memory_ids'] == null ? undefined : json['source_memory_ids'],
        'targetEntityId': json['target_entity_id'] == null ? undefined : json['target_entity_id'],
        'type': json['type'] == null ? undefined : json['type'],
        'validFrom': json['valid_from'] == null ? undefined : json['valid_from'],
        'validTo': json['valid_to'] == null ? undefined : json['valid_to'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function UpdateRelationshipRequestToJSON(json: any): UpdateRelationshipRequest {
    return UpdateRelationshipRequestToJSONTyped(json, false);
}

export function UpdateRelationshipRequestToJSONTyped(value?: UpdateRelationshipRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fact': value['fact'],
        'metadata': value['metadata'],
        'name': value['name'],
        'source_entity_id': value['sourceEntityId'],
        'source_memory_ids': value['sourceMemoryIds'],
        'target_entity_id': value['targetEntityId'],
        'type': value['type'],
        'valid_from': value['validFrom'],
        'valid_to': value['validTo'],
        'weight': value['weight'],
    };
}

