/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemporalDecayConfig } from './TemporalDecayConfig';
import {
    TemporalDecayConfigFromJSON,
    TemporalDecayConfigFromJSONTyped,
    TemporalDecayConfigToJSON,
    TemporalDecayConfigToJSONTyped,
} from './TemporalDecayConfig';
import type { SourceWeightsConfig } from './SourceWeightsConfig';
import {
    SourceWeightsConfigFromJSON,
    SourceWeightsConfigFromJSONTyped,
    SourceWeightsConfigToJSON,
    SourceWeightsConfigToJSONTyped,
} from './SourceWeightsConfig';
import type { GraphSearchOptions } from './GraphSearchOptions';
import {
    GraphSearchOptionsFromJSON,
    GraphSearchOptionsFromJSONTyped,
    GraphSearchOptionsToJSON,
    GraphSearchOptionsToJSONTyped,
} from './GraphSearchOptions';
import type { MethodWeights } from './MethodWeights';
import {
    MethodWeightsFromJSON,
    MethodWeightsFromJSONTyped,
    MethodWeightsToJSON,
    MethodWeightsToJSONTyped,
} from './MethodWeights';
import type { RerankerOptions } from './RerankerOptions';
import {
    RerankerOptionsFromJSON,
    RerankerOptionsFromJSONTyped,
    RerankerOptionsToJSON,
    RerankerOptionsToJSONTyped,
} from './RerankerOptions';

/**
 * 
 * @export
 * @interface UpdateSearchConfigRequest
 */
export interface UpdateSearchConfigRequest {
    /**
     * DefaultMethod specifies the default search strategy; required in every update request.
     * The caller must resend the current engine value on every update;
     * a different value is rejected once memories exist.
     * @type {UpdateSearchConfigRequestDefaultMethodEnum}
     * @memberof UpdateSearchConfigRequest
     */
    defaultMethod: UpdateSearchConfigRequestDefaultMethodEnum;
    /**
     * EnableAutoSelect enables/disables automatic method selection (optional)
     * @type {boolean}
     * @memberof UpdateSearchConfigRequest
     */
    enableAutoSelect?: boolean;
    /**
     * GraphOptions configures graph search (optional)
     * @type {GraphSearchOptions}
     * @memberof UpdateSearchConfigRequest
     */
    graphOptions?: GraphSearchOptions;
    /**
     * MethodWeights configures hybrid search weights (optional)
     * @type {MethodWeights}
     * @memberof UpdateSearchConfigRequest
     */
    methodWeights?: MethodWeights;
    /**
     * Reranker configures reranking (optional)
     * @type {RerankerOptions}
     * @memberof UpdateSearchConfigRequest
     */
    reranker?: RerankerOptions;
    /**
     * SourceWeights configures seed source weights (optional)
     * @type {SourceWeightsConfig}
     * @memberof UpdateSearchConfigRequest
     */
    sourceWeights?: SourceWeightsConfig;
    /**
     * TemporalDecay configures temporal decay (optional)
     * @type {TemporalDecayConfig}
     * @memberof UpdateSearchConfigRequest
     */
    temporalDecay?: TemporalDecayConfig;
    /**
     * TopN sets the result count (optional). nil = not sent; 0 is stored as the system top_n (services.search.top_n).
     * @type {number}
     * @memberof UpdateSearchConfigRequest
     */
    topN?: number;
}


/**
 * @export
 */
export const UpdateSearchConfigRequestDefaultMethodEnum = {
    QuickSearch: 'quick_search',
    DeepSearch: 'deep_search',
    ContextAwareSearch: 'context_aware_search'
} as const;
export type UpdateSearchConfigRequestDefaultMethodEnum = typeof UpdateSearchConfigRequestDefaultMethodEnum[keyof typeof UpdateSearchConfigRequestDefaultMethodEnum];


/**
 * Check if a given object implements the UpdateSearchConfigRequest interface.
 */
export function instanceOfUpdateSearchConfigRequest(value: object): value is UpdateSearchConfigRequest {
    if (!('defaultMethod' in value) || value['defaultMethod'] === undefined) return false;
    return true;
}

export function UpdateSearchConfigRequestFromJSON(json: any): UpdateSearchConfigRequest {
    return UpdateSearchConfigRequestFromJSONTyped(json, false);
}

export function UpdateSearchConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSearchConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultMethod': json['default_method'],
        'enableAutoSelect': json['enable_auto_select'] == null ? undefined : json['enable_auto_select'],
        'graphOptions': json['graph_options'] == null ? undefined : GraphSearchOptionsFromJSON(json['graph_options']),
        'methodWeights': json['method_weights'] == null ? undefined : MethodWeightsFromJSON(json['method_weights']),
        'reranker': json['reranker'] == null ? undefined : RerankerOptionsFromJSON(json['reranker']),
        'sourceWeights': json['source_weights'] == null ? undefined : SourceWeightsConfigFromJSON(json['source_weights']),
        'temporalDecay': json['temporal_decay'] == null ? undefined : TemporalDecayConfigFromJSON(json['temporal_decay']),
        'topN': json['top_n'] == null ? undefined : json['top_n'],
    };
}

export function UpdateSearchConfigRequestToJSON(json: any): UpdateSearchConfigRequest {
    return UpdateSearchConfigRequestToJSONTyped(json, false);
}

export function UpdateSearchConfigRequestToJSONTyped(value?: UpdateSearchConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default_method': value['defaultMethod'],
        'enable_auto_select': value['enableAutoSelect'],
        'graph_options': GraphSearchOptionsToJSON(value['graphOptions']),
        'method_weights': MethodWeightsToJSON(value['methodWeights']),
        'reranker': RerankerOptionsToJSON(value['reranker']),
        'source_weights': SourceWeightsConfigToJSON(value['sourceWeights']),
        'temporal_decay': TemporalDecayConfigToJSON(value['temporalDecay']),
        'top_n': value['topN'],
    };
}

