/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SourceWeightsConfig } from './SourceWeightsConfig';
import {
    SourceWeightsConfigFromJSON,
    SourceWeightsConfigFromJSONTyped,
    SourceWeightsConfigToJSON,
    SourceWeightsConfigToJSONTyped,
} from './SourceWeightsConfig';

/**
 * 
 * @export
 * @interface UpdateSourceWeightsRequest
 */
export interface UpdateSourceWeightsRequest {
    /**
     * SourceWeights contains the new source weight configuration
     * @type {SourceWeightsConfig}
     * @memberof UpdateSourceWeightsRequest
     */
    sourceWeights: SourceWeightsConfig;
}

/**
 * Check if a given object implements the UpdateSourceWeightsRequest interface.
 */
export function instanceOfUpdateSourceWeightsRequest(value: object): value is UpdateSourceWeightsRequest {
    if (!('sourceWeights' in value) || value['sourceWeights'] === undefined) return false;
    return true;
}

export function UpdateSourceWeightsRequestFromJSON(json: any): UpdateSourceWeightsRequest {
    return UpdateSourceWeightsRequestFromJSONTyped(json, false);
}

export function UpdateSourceWeightsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSourceWeightsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'sourceWeights': SourceWeightsConfigFromJSON(json['source_weights']),
    };
}

export function UpdateSourceWeightsRequestToJSON(json: any): UpdateSourceWeightsRequest {
    return UpdateSourceWeightsRequestToJSONTyped(json, false);
}

export function UpdateSourceWeightsRequestToJSONTyped(value?: UpdateSourceWeightsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source_weights': SourceWeightsConfigToJSON(value['sourceWeights']),
    };
}

