/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOrgSummary
 */
export interface UserOrgSummary {
    /**
     * OrgID is the organization's unique identifier.
     * @type {string}
     * @memberof UserOrgSummary
     */
    orgId?: string;
    /**
     * OrgName is the organization's display name.
     * @type {string}
     * @memberof UserOrgSummary
     */
    orgName?: string;
    /**
     * PlanSlug is the slug of the plan this organization is subscribed to.
     * @type {string}
     * @memberof UserOrgSummary
     */
    planSlug?: string;
    /**
     * Role is the user's role within this organization (e.g., "owner", "member").
     * @type {string}
     * @memberof UserOrgSummary
     */
    role?: string;
}

/**
 * Check if a given object implements the UserOrgSummary interface.
 */
export function instanceOfUserOrgSummary(value: object): value is UserOrgSummary {
    return true;
}

export function UserOrgSummaryFromJSON(json: any): UserOrgSummary {
    return UserOrgSummaryFromJSONTyped(json, false);
}

export function UserOrgSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOrgSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'orgId': json['org_id'] == null ? undefined : json['org_id'],
        'orgName': json['org_name'] == null ? undefined : json['org_name'],
        'planSlug': json['plan_slug'] == null ? undefined : json['plan_slug'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function UserOrgSummaryToJSON(json: any): UserOrgSummary {
    return UserOrgSummaryToJSONTyped(json, false);
}

export function UserOrgSummaryToJSONTyped(value?: UserOrgSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'org_id': value['orgId'],
        'org_name': value['orgName'],
        'plan_slug': value['planSlug'],
        'role': value['role'],
    };
}

