/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEventView
 */
export interface WebhookEventView {
    /**
     * 
     * @type {string}
     * @memberof WebhookEventView
     */
    accountId?: string;
    /**
     * RFC3339
     * @type {string}
     * @memberof WebhookEventView
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventView
     */
    eventType?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventView
     */
    id?: string;
    /**
     * RFC3339
     * @type {string}
     * @memberof WebhookEventView
     */
    processedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventView
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventView
     */
    status?: string;
}

/**
 * Check if a given object implements the WebhookEventView interface.
 */
export function instanceOfWebhookEventView(value: object): value is WebhookEventView {
    return true;
}

export function WebhookEventViewFromJSON(json: any): WebhookEventView {
    return WebhookEventViewFromJSONTyped(json, false);
}

export function WebhookEventViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEventView {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'eventType': json['event_type'] == null ? undefined : json['event_type'],
        'id': json['id'] == null ? undefined : json['id'],
        'processedAt': json['processed_at'] == null ? undefined : json['processed_at'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function WebhookEventViewToJSON(json: any): WebhookEventView {
    return WebhookEventViewToJSONTyped(json, false);
}

export function WebhookEventViewToJSONTyped(value?: WebhookEventView | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'created_at': value['createdAt'],
        'event_type': value['eventType'],
        'id': value['id'],
        'processed_at': value['processedAt'],
        'provider': value['provider'],
        'status': value['status'],
    };
}

