/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEventLedgerDetail
 */
export interface WebhookEventLedgerDetail {
    /**
     * 
     * @type {string}
     * @memberof WebhookEventLedgerDetail
     */
    accountId?: string;
    /**
     * RFC3339
     * @type {string}
     * @memberof WebhookEventLedgerDetail
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventLedgerDetail
     */
    dedupeKey?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventLedgerDetail
     */
    eventType?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventLedgerDetail
     */
    id?: string;
    /**
     * RFC3339
     * @type {string}
     * @memberof WebhookEventLedgerDetail
     */
    processedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventLedgerDetail
     */
    processingError?: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventLedgerDetail
     */
    provider?: string;
    /**
     * JSON object
     * @type {object}
     * @memberof WebhookEventLedgerDetail
     */
    rawHeaders?: object;
    /**
     * 
     * @type {Array<number>}
     * @memberof WebhookEventLedgerDetail
     */
    rawPayload?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof WebhookEventLedgerDetail
     */
    status?: string;
}

/**
 * Check if a given object implements the WebhookEventLedgerDetail interface.
 */
export function instanceOfWebhookEventLedgerDetail(value: object): value is WebhookEventLedgerDetail {
    return true;
}

export function WebhookEventLedgerDetailFromJSON(json: any): WebhookEventLedgerDetail {
    return WebhookEventLedgerDetailFromJSONTyped(json, false);
}

export function WebhookEventLedgerDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEventLedgerDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'dedupeKey': json['dedupe_key'] == null ? undefined : json['dedupe_key'],
        'eventType': json['event_type'] == null ? undefined : json['event_type'],
        'id': json['id'] == null ? undefined : json['id'],
        'processedAt': json['processed_at'] == null ? undefined : json['processed_at'],
        'processingError': json['processing_error'] == null ? undefined : json['processing_error'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'rawHeaders': json['raw_headers'] == null ? undefined : json['raw_headers'],
        'rawPayload': json['raw_payload'] == null ? undefined : json['raw_payload'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function WebhookEventLedgerDetailToJSON(json: any): WebhookEventLedgerDetail {
    return WebhookEventLedgerDetailToJSONTyped(json, false);
}

export function WebhookEventLedgerDetailToJSONTyped(value?: WebhookEventLedgerDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'created_at': value['createdAt'],
        'dedupe_key': value['dedupeKey'],
        'event_type': value['eventType'],
        'id': value['id'],
        'processed_at': value['processedAt'],
        'processing_error': value['processingError'],
        'provider': value['provider'],
        'raw_headers': value['rawHeaders'],
        'raw_payload': value['rawPayload'],
        'status': value['status'],
    };
}

