/* tslint:disable */
/* eslint-disable */
/**
 * smritea Control Plane API
 * SaaS Control Plane API for smritea AI memory system — user authentication, organization management, admin operations, and proxy forwarding to data-plane
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@smritea.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeightsApplied
 */
export interface WeightsApplied {
    /**
     * BM25Weight is the weight for keyword matching
     * @type {number}
     * @memberof WeightsApplied
     */
    bm25Weight?: number;
    /**
     * GraphWeight is the weight for graph-based results
     * @type {number}
     * @memberof WeightsApplied
     */
    graphWeight?: number;
    /**
     * VectorWeight is the weight for vector similarity
     * @type {number}
     * @memberof WeightsApplied
     */
    vectorWeight?: number;
}

/**
 * Check if a given object implements the WeightsApplied interface.
 */
export function instanceOfWeightsApplied(value: object): value is WeightsApplied {
    return true;
}

export function WeightsAppliedFromJSON(json: any): WeightsApplied {
    return WeightsAppliedFromJSONTyped(json, false);
}

export function WeightsAppliedFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeightsApplied {
    if (json == null) {
        return json;
    }
    return {
        
        'bm25Weight': json['bm25_weight'] == null ? undefined : json['bm25_weight'],
        'graphWeight': json['graph_weight'] == null ? undefined : json['graph_weight'],
        'vectorWeight': json['vector_weight'] == null ? undefined : json['vector_weight'],
    };
}

export function WeightsAppliedToJSON(json: any): WeightsApplied {
    return WeightsAppliedToJSONTyped(json, false);
}

export function WeightsAppliedToJSONTyped(value?: WeightsApplied | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bm25_weight': value['bm25Weight'],
        'graph_weight': value['graphWeight'],
        'vector_weight': value['vectorWeight'],
    };
}

